### ISSUE TITLE
中文显示问题 in column

### ISSUE THREAD

**Issue by Davidrjx** [ssy341/datatables-cn#10]
![capture](https://cloud.githubusercontent.com/assets/4284791/17473009/b24615c2-5d80-11e6-85e3-8035a5d834bb.JPG)
采用ajax objects数据源且数据来自数据库
其中，Titile列可能包含中文，但却是unicode编码显示。
请问大家，如何处理才能正常显示中文？谢谢

**Comment by ssy341** [comment]
这个应该和你服务器配置有关系，dt本身不会对字符进行编码，所以按照你的描述，dt在得到数据的时候就已经是编码了，你检查下配置

**Comment by Davidrjx** [comment]
thanks for your reply,
i will check it as you advised.
