### ISSUE TITLE
414 (Request-URI Too Long)

### ISSUE THREAD

**Issue by Jill-Wang** [ssy341/datatables-cn#101]
使用了显示行的附加信息api，它里面获取数据的方式是从一个txt文件中，如`"ajax": "../ajax/data/objects.txt"`,现在我把这个数据定义为一个变量var data = {...}，因为我后面要用的时候，数据是从后端传输过来的，不是一个文件，然后在控制台就报错信息为：`jquery.js:4 GET http://127.0.0.1/table/datatables1.html?0%5Bname%5D=Tiger+Nixon&0%5Bpositio…=2011%2F06%2F27&55%5Boffice%5D=Singapore&55%5Bextn%5D=5384&_=1491877080653 414 (Request-URI Too Long)`

**Comment by ssy341** [comment]
@Jill-Wang 
HTTP 414 错误 – 请求 URI 过长 (Request URI too long)

介绍
您的 Web 服务器认为，客户端（如您的浏览器或我们的 CheckUpDown 机器人）发送的 HTTP 数据流包含一个过长网址， 即字节太多。

通常 Web 服务器对真正的网址设置相当慷慨的限长， 例如高达 2048 或 4096 个字符。 如果您的网址特别长， 您 通常可以尝试缩短一些看看大致的限长是多少。 如果您的长网址确实是有效的， 那么可能需要重新设置 Web 服务器， 允许您的网址通过。 需要理解的是， Web 服务器必须设置一些合理的限制， 因为他们必须处理由客户端编程失败所造成的巨大的垃圾网址。

解决 414 错误 – 一般方法
这个错误在大多数网络传输中都少有发生，特别是当客户端系统是一个浏览器时就更不可能。 网址在这种情况下通常是网页上可见的标准超文本链接。 如果这些链接干脆就是错的， 即含有该链接的网页编程很糟， 则这些链接往往就会过长。

如果您的客户端系统不是一个浏览器，这个问题只有通过以下途径解决， 即先检查客户端在试图做什么，然后与您的 互联网服务供应商 (ISP) 商讨为什么 Web 服务器拒绝接受客户端所发送网址的大小。


你url里请求的东西检查下，如果参数多，就用post
```javascript
var table = $("#tableid").DataTable({
 ajax:{
    url:"",
   type:"post"
}
});
```

如果你需要测试，那么你可能需要如下的代码：
```javascript
var data = [{name:"datatables中文网",url:"datatables.club"},{name:"datatables中文网",url:"datatables.club"}]
var table = $("#tableid").DataTable({
data:data,
columns:[
{data:"name"},
{data:"url"}
]
});
```
