### ISSUE TITLE
datatable ajax 自定义搜索

### ISSUE THREAD

**Issue by lt090004114** [ssy341/datatables-cn#102]
自定义搜索条件，按搜索键ajax搜索数据，datatable中stateSave的状态是true，每次搜索的值都会定义到当前页，希望能从首页开始搜索

**Comment by ssy341** [comment]
@lt090004114  首先需要理解 statesave这个属性的含义 ，参考 [状态保存(stateSave) 选项(option) 参考(reference) Datatables 中文网:](http://datatables.club/reference/option/stateSave.html)
[状态保存(stateSave) 选项(option) 参考(reference) Datatables 中文网:](http://www.datatables.club/blog/2016/09/30/about-localStorage-of-stuff-for-DataTables.html)
如果使用statesave不是你的本意 那么看完之后应该可以解决你的问题

**Comment by lt090004114** [comment]
我使用statesave主要是为了在刷新的情况下能保存住当前分页；但是会有一个问题，我有自定义筛选条件，如果使用这个状态，每次筛选的时候就会把当前分页带去后台，这样对我来说数据的准确性就有问题了。

**Comment by ssy341** [comment]
@lt090004114  对，他不仅仅保存分页，所有的操作都会缓存，所以确定在使用这个参数前，你已经明白这个跟参数的含义，不然会造成很多不必要的问题

**Comment by lt090004114** [comment]
@ssy341 ，我就想知道有没有方法既能让我使用statesave这个参数，又能在某种情况下让statesave这个参数失效。

**Comment by ssy341** [comment]
@lt090004114  你试试自己控制他的状态保存，参考下面这几个

- [stateLoadCallback](http://datatables.club/manual/daily/2016/09/10/option-stateLoadCallback.html)
- [stateLoaded](http://datatables.club/manual/daily/2016/09/11/option-stateLoaded.html)
- [stateLoadParams](http://datatables.club/manual/daily/2016/09/22/option-stateLoadParams.html)
- [stateSaveCallback](http://datatables.club/manual/daily/2016/09/23/option-stateSaveCallback.html)
- [stateSaveParams](http://datatables.club/manual/daily/2016/09/25/option-stateSaveParams.html)
