### ISSUE TITLE
datatables选中行事件

### ISSUE THREAD

**Issue by qq125842427** [ssy341/datatables-cn#104]
默认选中表格第一行，并且可以获取到第一行的数据，当用户点击其他行时，获取选择相应行的数据。查了好久没查到，望解答，谢谢。

**Comment by mjwlking** [comment]
//点击数据表格中的行产生的动作
        $('.data-table tbody').on( 'click', 'tr', function () {
            //alert(Mytable.row( this ).data()['UserID']);
        } );
.data-table = 我是用class属性取的，你可以按照你的table属性来取。
Mytable = 我给我的datatables起的名字
.data()['UserID'] 数据表列的名字。
在Mytable中我定义了columns 这个属性

**Comment by ssy341** [comment]
@qq125842427 

···javascript
 var table = $('#example').DataTable();
 
    $('#example tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }
    } );
 
//默认选中第一行
     table.$('tr.eq(0)').addClass("selected");

···
