### ISSUE TITLE
怎么动态加载表头及表格内容？有时候可能会增加或减少关键字，只要后台数据库增加或减少，某个字段，我们可以自动渲染出来，因为数据模型不一样，columns都是一个个列出来的。。不知道怎么解决这个问题。。

### ISSUE THREAD

**Issue by wangmengting** [ssy341/datatables-cn#110]
$(document).ready(function() {
	     $('.panel-body').html( '<table cellpadding="0" cellspacing="0" border="0" class="display" id="example"></table>' );      	

	     $('#example').dataTable( {                                                                                           
	     	ajax: {
	     		url:'http://sso.op.kingnet.com/dev/login_log',
		        dataSrc:function(result){
		            return result.msg.list;
		        }
	     	},                                                                                                              
	        columns: [                                                             
	            { "data": "f_id" ,"title": "Engine" }, 
	            { "data": "f_equip_uuid" ,"title": "Engine" },                   	            
	            { "data": "f_account" ,"title": "Engine" },                           
	            { "data": "f_login_type" ,"title": "Engine" }        	        
			]
	    } );
} );

**Comment by ssy341** [comment]
@wangmengting  参考下这个#26
