### ISSUE TITLE
如何解决datatables中的ajax动态数据渲染问题

### ISSUE THREAD

**Issue by YYtianqiong** [ssy341/datatables-cn#112]
传过来参数后，还是显示原来的数据，怎样清空并加载新的数据，求代码！！！

**Comment by lyy176** [comment]
我用的是死办法，当需要更新数据时，先dataTables.destroy();，然后再重新$("#table").DataTable({ajax:{url:'XXXXXX'},columns:getNormalColumnArry()}),其中getnormalcolumnarry是我根据不同的数据生成不同数据的表的对应字段。

**Comment by 610492664** [comment]
dt.ajax.url( url ).load

**Comment by ssy341** [comment]
@YYtianqiong 如果是像 @610492664 说的那样，可以参考中文网首页的[例子](http://datatables.club)

**Comment by swocn** [comment]
回调函数成功，执行
table.ajax.reload();
就OK了，但要注意实例化时$('#tab').datatable与$('#tab').Datatable的区别，这个在说明里有

**Comment by ssy341** [comment]
@
table.ajax.reload() 是按照实例化时候给的url去读取数据
table.ajax.url(url).load();是按照你新给的地址去读取数据（数据格式需要和实例化时的数据保持一致）
