### ISSUE TITLE
datatables 有没有数据加载完成事件

### ISSUE THREAD

**Issue by fjdgl** [ssy341/datatables-cn#114]
我要把 table 数据加载完成后对表的内容进行统计

**Comment by occultskyrong** [comment]
所有的回调douz都在这。。你可以自己看下。。
![image](https://cloud.githubusercontent.com/assets/8370006/26314570/fd05e036-3f40-11e7-9db7-fc31d1dae86d.png)

你可能需要的是drawCallback，
> It can be useful to take an action on every draw event of the table - for example you might want to update an external control with the newly displayed data, or with server-side processing is enabled you might want to assign events to the newly created elements. This callback is designed for exactly that purpose and will execute on every draw.

每次draw完成调用回调。

https://datatables.net/reference/option/drawCallback
