### ISSUE TITLE
服务器模式后端支持python吗

### ISSUE THREAD

**Issue by Jill-Wang** [ssy341/datatables-cn#116]
服务器模式后端支持python吗？求一个完整例子，多谢！

**Comment by ssy341** [comment]
@Jill-Wang 后端语言不限制，我这里暂时没有python的例子，抱歉

**Comment by mxxlevel** [comment]
`start_index = int(request.POST['start'])
    page_size = int(request.POST['length'])
    draw = request.POST['draw']
    keyword = request.POST['search[value]']
    orderdesc = '-' if request.POST['order[0][dir]'] == 'desc' else ''
    ordername = request.POST['columns[' + request.POST['order[0][column]'] + '][data]']
    ordername = 'product_name' if ordername == '' else ordername
    orderstr = orderdesc + ordername

    status_opt = request.POST.get('columns[5][search][value]', '')
    status_opt = '' if status_opt == '' else status_opt[1:-1]
    salable_opt = request.POST.get('columns[6][search][value]', '')
    salable_opt = '' if salable_opt == '' else salable_opt[1:-1]`
