### ISSUE TITLE
服务器处理弹框

### ISSUE THREAD

**Issue by Jill-Wang** [ssy341/datatables-cn#117]
网站链接：[http://datatables.club/example/server_side/simple.html](http://datatables.club/example/server_side/simple.html)
弹框内容为：DataTables warning: table id=example - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
表格并没有加载成功。

**Comment by ssy341** [comment]
@Jill-Wang 这个是因为服务器不存在了，请求不到数据，所以提示这个，你可以参考此代码在本地自己弄一个看到效果
