### ISSUE TITLE
后端得到的比如省市区的数据怎么在datatables前端进行拼接？

### ISSUE THREAD

**Issue by murong-tiezhu** [ssy341/datatables-cn#118]

**Comment by ssy341** [comment]
R̶͚͓̯͇͎̩̞̲͚̮͉̠̥͓͔̘͖̰̘͉̪͔̖̦͈̗̟̙͎͕̗̼̪͉̰̼͙̞̠͖̺͚̜͕͍͚͙͇̮̖̯͍͔̽̍ͬͭͩ̊͛ͮ̍ͯ̈́ͩͤͅE̶̢͈̖̰̱̱̞̯̼̫̫̦̩̯̞̜̮̜͎͕̜̥̼̣͉͈̺̦̣̦̻̞̗̻̻̲̝͍̣͎̞̫̜̊ͤ͊̐͢M̪̯͚̩̖̜̜̖͙̦̫̗͉̟̪̪̮͈͌̆̋ͣͩ́̂̋̆ͥ̋̂͟͜ͅO͔̙͉͓̭͉͚̱͍͕͍̝͙̳̩̦͕͈̖̻̩̥̗̼̗͔̳͖̭ͨͫͮͮ̋̃̓҉̡V̡͍͙̪̣̠̆̌ͨ̿̏̚̚ͅĒ̶͉̮͈̣̼̱̼̺͓̼͎̘̭̗͙̯͐ͮͦ́ͨ͂̂͗̈̉͐̓̉̓͘̕͢͜ͅ ̸̞̟̖͎͍͔̰̹͙͕̻͔̪̝̱̝̦͚̹̗̼̦̭̝̮̹̻͙ͥ̿̈̍ͧͫͨ͒́́͟ͅͅͅ҉͏M̛̼̮̫͙̜͉̘̳̫͇̱̙̲̰̻̞̩̫̜̺̠͈͕̞̘̼̦̼̭̣̪͓̫̥͚̜̪̲̰̘̘̳̹̲̠͈͔͖̜͚̱̩͇̬̰͍͑ͨ̾ͫ̉̊͆̈́ͩ̑̔ͧͤͅE̵̶͍̦̭͕̤͖̠͚̩͈̫̯̟͎̠͚̜̪̖̭̳̬̠̦͎̙̳͓̱̘̻ͧͨ̓̑̄̊̇͌ͪͥ̂ͭ͂̎̃̀͠ͅ ͇̗͔͕͓̘͓͚̭͓̬͚̠̹̤̗͍͕̟͔̱͚̩̗̣͆ͤ͌͠ͅͅ҉̨́P̰̫̙̪͔̗̼͖̗̫̻̣͈͍̻̝͎̟̬͕̳̻̫͉̤͍̟̮̰̏̊̅͋̇͐͑̔̌̂͑ͤ͐ͮ͞L̮̯̗̤̜̞̗̩̳͖͔̟̥̻̮̘͓͕̲̱̠̱̲̻͎̭̙͉̠̳̘̻̗̙͕̞̥͖̯͓͓̪̗̜̣̯̟͎̫͈̪̳̤͔̠̗̦̦͍̰͔͔̝͖͙̃͂ͮ̌͛ͩ̀̓̕E̷̘͖͔̱̙̼͔͎̖̮̗͔̼̙̝͚̋̎ͩͭ͢͟͝͠Ą͈͍̬̺̯̯͈̭̪̬̤̘̞͚͈͚͉̺͇̙̱̥̦̯̪͙̠̘̦̳͎̙͙̭̲̭̞͚͈̲̟͎͇̞̲ͩͭͧ̈́ͯ̏͗͛̌̄͐̋ͦ͊̈́́̕͞͡ͅS̛̙͙̟̻̝̣̪̦̱̣̠̼̫̤̩̣̲̭̩̠̰͓͙͓͙̯̥̣̭̥̭̱̠̹̝̪̳̯̻̙̯͓͈̑̓ͣ̄̋ͦ͊̿̋̌̎̾̂̚͢Ě̡͙͚͉͉͖̤̗͕̼̦̩̞̰͕̦͎̯͉̯̲̠̦̦̗̫̪͓̣͍͚͎͇͙̹̰͓͓̱͈̰͎̗̻̦͖͙̜̬̳͙͖͔̠͙̑ͫͅ͏͘͢ ̡͚͓̦̹̝̠̲̤̹̤͎̱̝̼͈̙͕̥͔̜̹̺̝̻̩͍̞͓̤̟̙̟̖̫͍̞̳̪̬̝̳̠̼͇͔̬͍͉̻̼͕̄ͤ̽̋̋͐̎̈!̴̨̨̤̠͔̖̓ͪ̍̂̄͗́͜͠!̷͖̹͍͍̺̞̠͚͖͍͔͕̖̰͇̺͖̩͕̖͎̬̬̩͈̬̺̙͍̣̼͇̳̮̰̞̹͇̝̱̰̖̬̰̰̜̜̭̮̣̭̤̫͎̲̙̟̞̟̣̝͓͇̦̽ͫ̔̂̔̊̿̀̀͌́͊̓͋̃͊̒̚͘ͅ!̫̥̺̪̬̯̖̜͈̠̣̺̙̖̣̯̖͈̩̱̺̦̮͖̥͍̮̹͙̲̖̦͍̻̻̟̜̼̦͔͔̦̯͚̦̯̭̩̟͈͎͎̗̥͇̦̘̞͔̣͋͋̍ͧͬ́ͭ͆̾̓͆͊̋̈́̐̿̂͞!̸̢̭̹͖̝͔͚̦͈͚̣̺̥̯̞̟̜͎͉̘̩̠̩̋̾̉̉̒͛́̂̇͆͌̋̂ͪͫ̽̏̉͜!̷̨̡̛̼͕̺͉̫͓̖̳̝̩̞̣̗̹̻̫̲͙̝̙̝̗̰̪̤̺̰̮͊͆̓ͨ̏͑ͯ̃͗͑̆̐͗ͧ̃ͅ!̵̢̨̼͈̬͎͎̱͔̩͔̙͙̪̲̦̤̺̳͈̰̱̹̟̰̖̖͉̺͓̘͎̦͈̲̲̫̠̬̘̰̺̬̖͖̺̻̯̪̜̣͙̦̯͚̩̠̹ͭͤ͆̂ͬ̊̔ͫ͂͗̌́̕ͅͅ!̵̸̭̼͎̻̤̣͖̺̯͖̲̹͂͊̾͆͌̂̓ͩ̌́̃̿͆ͧ͑͛ͤ́͡!̛̳͓̣̘̤̻͕͕͔͔͍̰̪͇̗͖̞͔͔̳̠̫̙̪̻̖͔͚͕̞̱͇̝̹͚͉̯͓̻̩̻̜̻̪̝̳̱̖̮̘̻̮͍͚ͪ̃̆̈ͯ̋͊ͮ͂͢ͅͅ!̶̢͍̳͉̏̃̆̆͋ͮ̓͑̋ͯͬ̉̏͗ͩ̆̚͘͘ͅ!̡̟̜͚̳̣̲͉̱̮̺̞̣͎͙̜̱͈̥̍̊ͨͫ̚ͅ!͔͈̩͎͔͓̳̲̙͍̮̲̩̱̤͖̳̤̦̻̗͓͎͍͙̣̙͎͓̪̲̅ͥ̔̅͆͋̅ͪ̏͒ͨ̑͒͂ͮͤͦ́ͅ͏̧͝!̹̟̜̻̖͖̮͚͕̱͍̳̫̜̜͖͉̮̪̤̪̦͎̗͙̖̹̩͖̘͖̜̞͆̒ͤ͌̆ͮ͋ͯ͐̚ͅ͏̛̀҉̀!̶̧̨̛͈̗̱͕̹̻̣̳͈͚̘̻̱͕̻̟̼̭̦͉̮͈̝̦̤̠̙͇͕̠̝̺̤̼̱̏ͬ̍ͣͨͨ̑̿̎̌͌ͬ̀̅ͩ̀ͣ̑̃͢
