### ISSUE TITLE
后端得到的比如省市区的数据怎么在datatables前端进行拼接？

### ISSUE THREAD

**Issue by murong-tiezhu** [ssy341/datatables-cn#119]
![image](https://cloud.githubusercontent.com/assets/22267933/25466807/62a48cca-2b3d-11e7-847c-2e479e2027f8.png)
 类似于这种数据

**Comment by ssy341** [comment]
@murong-tiezhu 参考完[这个](http://datatables.club/manual/daily/2016/04/25/option-columns-render1.html) 你会得到答案
