### ISSUE TITLE
用管道式分页来加载序号

### ISSUE THREAD

**Issue by Liesport758** [ssy341/datatables-cn#12]
管道式用的是官网插件，地址是https://datatables.net/examples/server_side/pipeline.html，
服务器模式加载序号是参考是http://datatables.club/blog/2016/07/10/add-index-for-table.html
在 json.data.splice( 0, requestStart-cacheLower );时会报错，如何解决这个问题呢

**Comment by ssy341** [comment]
这还是需要提供你的代码，splice这个是js里的方法，一般这种情况出现，可能是因为json.data 本身为null或者 undefined ，你先自己打印下 json这个变量，应该能找到原因

**Comment by David5201** [comment]
我也是第一次用datatables。没有java的后端参考代码
