### ISSUE TITLE
关于dataTable行内编辑的问题

### ISSUE THREAD

**Issue by xiaochao520** [ssy341/datatables-cn#121]
请问dt有没有自带的那种行内编辑的插件！ 免费的，求资源，最好有demo ，谢谢各位大哥了

**Comment by ssy341** [comment]
@xiaochao520  这里有个比较全的例子，你可以参考下 [runjs代码地址](http://runjs.cn/code/dirmx2mi)
[代码介绍](http://datatables.club/blog/2016/06/09/datatables-for-tomato.html)
