### ISSUE TITLE
DT如何能够本地多条件搜索

### ISSUE THREAD

**Issue by 49839013** [ssy341/datatables-cn#123]
例如
$('#mytable').DataTable().search(
        //$('#global_filter').val()
        A+" "+B
    	).draw();
	}

我想搜索 既满足A条件，也满足B条件的，应该怎么处理，这么写不行呢。。。
求高手指导。。。

**Comment by ssy341** [comment]
```javascript
table
    .column(1)
    .search( this.value )
    .column(1)
    .search(value)
```
@49839013  试试这种看看

**Comment by 49839013** [comment]
@ssy341 
感谢收到你的回复，根据你的情况，我看了一下，应该只能支持单数据项，无法支持多数据项，以下是我的实现。

实际需求是需要满足  
第一列和最后一列支持查询框输入多个条件并且匹配。

   $.fn.dataTable.ext.search.push(
        function (settings, data, dataIndex) { 
            var strArr = $('#global_filter').val().split(","); 
            if(strArr!="")
            {
	            for(var i = 0;i<strArr.length;i++)
	            {
	            	//console.log(strArr[i]+"==="+data[0]);
	            	//console.log(data[0].indexOf(strArr[i]));
	            	//console.log(cloumsCount);
	            	if(data[0].indexOf(strArr[i])>=0||data[cloumsCount].indexOf(strArr[i])>=0)
	            	{
	            		return data[0].indexOf(strArr[i])||data[cloumsCount].indexOf(strArr[i]);
	            	}	     
	            	if(i+1==strArr.length)
	            	{
	            		return false;
	            	}
	            	//return (left.test(data));
	            }
            } 

            return true;
        }
    );
