### ISSUE TITLE
如何在列数小于10条的时候隐藏分页？大于10条的时候分页显示

### ISSUE THREAD

**Issue by UniqueSuccess** [ssy341/datatables-cn#124]
查了没有相应的配置项，当有数据且大于10条，显示分页，否则不显示分页，只显示数据

**Comment by chqpl** [comment]
用三目运算决定配置项的值 ， paging: data.length > 10 ? true : false

**Comment by ssy341** [comment]
@chqpl 这也是个办法，虽然不是那么优雅，但是能解决问题 👍
