### ISSUE TITLE
用 js 将两行数据交换位置

### ISSUE THREAD

**Issue by YH-Smile** [ssy341/datatables-cn#125]
我现在想做一个上下移位的功能，但是不知道该怎么做，求大神指点
功能描述：
点击上移按钮，则此行往上移动一行，点击下移则往下移动一行，并且能翻页上下移，不重新请求后台获取数据（即不刷新整个页面）

**Comment by cyyssly** [comment]
核心是splice方法：
var table = $('selecter').DataTable();
var index = table.row($(this).parents('tr')).index();
var data = table.data();
table.clear();
data.splice((index - 1), 0, data.splice(index, 1)[0]);
table.rows.add(data).draw();
