### ISSUE TITLE
DT行编辑之后，取出变化后的所有数据

### ISSUE THREAD

**Issue by yexueyouling** [ssy341/datatables-cn#126]
DT在表格中编辑之后，写一个function，取出变化的数据，存入全局变量

**Comment by ssy341** [comment]
@确保使用dt的api去更新数据，再用dt的api取数即可
参考 [cell().data()](http://datatables.club/reference/api/cell().data().html)
[column().data()](https://datatables.net/reference/api/column().data())
[row().data()](https://datatables.net/reference/api/row().data())
