### ISSUE TITLE
分页情况下请问怎样获取到所有选中的checkbox？

### ISSUE THREAD

**Issue by mr-likar** [ssy341/datatables-cn#128]
困惑如标题，感谢！

**Comment by Smaillife** [comment]
跨页的没做过，当前页的没啥难度，参考[http://datatables.club/blog/2016/06/10/multiple-columns-search.html](http://datatables.club/blog/2016/06/10/multiple-columns-search.html)

**Comment by mr-likar** [comment]
@Smaillife 当前页的我能获取到，但是跨页的chechbox获取不了，头疼

**Comment by ssy341** [comment]
@mr-likar 设置一个全局变量，每勾选一个往全局变量里push，最终获取全局变量里的值 ，这是最直接的办法

**Comment by mr-likar** [comment]
@ssy341 如果场景是全选的话你的这种方式不行哦，只能够全选到当前页面的checkbox哦，其他分页的checkbox选中不了，我现在遇到的就是这个问题

**Comment by ssy341** [comment]
@mr-likar 客户端模式数据全部到了前台，你还可能全选，服务端模式，一页10条数据，全选不可能，再回来说客户端，dt的实现方式是从内部数据渲染每一页，所以每次翻页都是重新渲染，全选的话，你就得用dt的api取出所有数据然后遍历

**Comment by aicerain** [comment]
@mr-likar ssy341 说的可以实现的  定义一个全局的数组  每次check 往数组里push unchecked 的话就移除出数组   翻页的时候判断下 数组是否存在当前面的值 如果存在就 对checkbox checked

**Comment by mr-likar** [comment]
@ssy341 @aicerain 我的场景是这样的，我用客户端模式实例化了一个dt，然后在第一页勾选全选的checkbox，可是选中的只有第一页的所有数据行，其他页面的数据行都没能选中

**Comment by ssy341** [comment]
@mr-likar 使用DT api 遍历所有数据 填充到全局变量里，比如
···JavaScript
//在你点击全选的方法里执行下面代码
//单选操作直接获取到选中行加入到全局变量
//全选操作使用下面代码
var checkList = []; //假设用来存放勾选数据的全局变量
var allData =table.data();
$(allData).each(function(i,o){
if(可以加上重复判断){
checkList.push(o);
}
})
···
