### ISSUE TITLE
安装DataTable时无法识别DataTable()函数

### ISSUE THREAD

**Issue by yyprime** [ssy341/datatables-cn#129]
`<link href="/Style/jquery.dataTables.css" rel="stylesheet" type="text/css"/>
    <script src="/Scripts/jquery.js" type="text/javascript" charset="utf-8"></script>
    <script src="/Scripts/jquery.dataTables.js" type="text/javascript" charset="utf-8"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#table_id_example').DataTable()**# ;//Uncaught TypeError: $(...).DataTable is not a function
                                                                   // at HTMLDocument.<anonymous> (DTPage:47)**
        });
    </script>`

**Comment by ssy341** [comment]
@yyprime  确认jquery.dataTables.js 的版本，1.10版之前初始化方式为 ` $('#table_id_example').dataTable()`注意d的小写
