### ISSUE TITLE
如何获取通过ajax得到的data数据

### ISSUE THREAD

**Issue by jmuchch** [ssy341/datatables-cn#131]
通过ajax获取到的数据，被dataTable所使用，但是我想在使用之前对data进行修改，该怎么办呢？

**Comment by ssy341** [comment]
@jmuchch 参考 [dataSrc](http://datatables.club/manual/daily/2016/04/20/option-ajax-dataSrc2.html)

**Comment by jmuchch** [comment]
可以通过ajax()获取，然后在由dataTable读取普通ajax获取到的数据；这样很灵活方便

**Comment by ssy341** [comment]
@jmuchch 参考这个[例子](http://datatables.club/example/user_share/mir/)
