### ISSUE TITLE
服务器端获取过来的数据不能进行 排序和搜索。

### ISSUE THREAD

**Issue by ciycy** [ssy341/datatables-cn#132]
如题。

**Comment by occultskyrong** [comment]
1、贴点你的代码。将能快速定位你的问题。一句话一般描述不清楚你遇到的问题。。
2、“服务器端获取过来的数据不能进行 排序和搜索。”
是指前端没法“排序和搜索”还是指后端？后端排序和搜索，需要在sql中完成，前端只是展示和调用。
前端排序和搜索，serverSide:false的时候开启ordering和searching。

具体查看
https://datatables.net/reference/option/ordering
https://datatables.net/reference/option/searching
