### ISSUE TITLE
求一个排序方法【问题】

### ISSUE THREAD

**Issue by 49839013** [ssy341/datatables-cn#133]
求一个排序方法
比如 
        A和B列不为空的   放在最上面 按照C列大小排序
        A列为空B列不为空的  放在中间  按照D列大小排序
        A和B都为空的  放在最底部  按照E列大小排序

这个怎么做。。。。。。。。求一个方法。。。。需要实时排序。。。过程中可能会有数据变更。

**Comment by occultskyrong** [comment]
你这是业务逻辑代码吧。。
直接问一下DBA好了。SQL里面直接实现。。。

**Comment by ssy341** [comment]
@49839013 你看看这个参数 [columns.orderData](http://datatables.club/reference/option/columns.orderData.html)
