### ISSUE TITLE
datatables 在加载数据后回调的函数怎么写

### ISSUE THREAD

**Issue by 13542202544** [ssy341/datatables-cn#135]
意思就是服务器模式下   点击下一页后在行内有个按钮   要给这个按钮家点击的监控事件怎么弄

**Comment by ssy341** [comment]
@13542202544 使用[drawCallback](http://datatables.club/reference/option/drawCallback.html)方法绑定事件
示例代码如下：这里是给表格中所有的button绑定点击事件，可以根据自己的需要绑定
```javascript
$('#example').dataTable( {
    "drawCallback": function( settings ) {
      $("#example tbody tr").on("click","button",function(){
                 //逻辑
      })
    }
} );
```
