### ISSUE TITLE
通过模板创建元素，然后绑定dataTable,在不刷新页面的情况下再次加载数据，此时dataTable相关操作报错

### ISSUE THREAD

**Issue by zhangjuanjuan01** [ssy341/datatables-cn#136]
如:
```html
<div></div>
<scritpt type="text/html" id="tmp-test-dataTable">
  <table id="test-dataTable"></table>
</script>
```
加载数据后将template写到div中，render时为test-dataTable绑定dataTable事件 ，数据发生变化时再次将template写到div中，同时再次为test-dataTable绑定dataTable事件，此时调用表格相关的事件出错

**Comment by ssy341** [comment]
@zhangjuanjuan01 看不到你贴的代码

**Comment by jmuchch** [comment]
实际上是对dataTable进行重新初始化操作，但是如何进行呢？我自己写了一个方法，但是不太完善：

	function refreshTableDom01(strID){
		var newTable = document.createElement("table");
		newTable.id=strID;
		newTable.className="display";
		//将新建的<table>元素放到id="content"的元素下方，作为其子元素
		var dom1 = document.getElementById(strID+"_wrapper");
		var parent_node = "";
		if(dom1){
			parent_node = dom1.parentNode;
			parent_node.removeChild(dom1);
			console.log(parent_node.id);//textContent
			parent_node.appendChild(newTable);//新建id="template_grid", class="display"的<table>元素
		}


	}

**Comment by jmuchch** [comment]
只要把你的dataTable的id字符串带进去即可；如refreshTableDom01("example");

**Comment by ssy341** [comment]
@zhangjuanjuan01 也没搞懂问了问题就不管了，没提供代码也不告诉报了什么错，我只能把问题关闭了
