### ISSUE TITLE
后台返回给前台的json数据一定是官方案例里面的吗

### ISSUE THREAD

**Issue by moonflower-wang** [ssy341/datatables-cn#137]
这种样式可以吗？
```javascript
{
"success":true,
  "data":{
    "draw":2,
    "total":129,
    "recordsFiltered":129,
    "recordsTotal":129,
    "rows":[

    ]
  }
}
```

**Comment by occultskyrong** [comment]
```
{
  "success": true,
  "data": {
  "draw": 2,
  "total": 129,
  "recordsFiltered": 129,
  "recordsTotal": 129,
  "rows": []
}
```
先注意你json中的语法错误，多了一个“}”。
可以使用 ajax.dataSrc进行数据转换。具体说明见 https://datatables.net/reference/option/ajax.dataSrc

不过建议你在外层key中直接使用 draw、data、recordsFiltered、recordsTotal。
因为如果你不使用自带的搜索的话，后两个值就是count。

这样你可以写成一个通用方法来处理response的逻辑代码。

**Comment by chqpl** [comment]
你这个也是官方案例之一哦。https://datatables.net/manual/ajax  里面的数据格式第三个：嵌套对象，你可以看看。顺便二楼可能看错了你的数据格式，你并没有多一个“}”，可能缩进不是很明显而已。

**Comment by ssy341** [comment]
提问人的代码格式我修改过，提issue前建议先阅读 #2 ，参考markdown语法 Syntax highlighting 部分，了解了markdown语法有利于描述问题，其他人也能很清楚的看明白代码
