### ISSUE TITLE
在dataTable已经加载数据的情况下，当数据变化时，需要重新加载数据，如何对dataTable重新初始化？

### ISSUE THREAD

**Issue by jmuchch** [ssy341/datatables-cn#138]
比如一个时间查询，选择时间2017.05.01  我点击查询后，dataTable加载并正常显示表格；
现在我把时间换成2017.05.23，然后点击查询，这时候就需要对dataTable 重新初始化，否则会出现错误；如何解决呢？
就是在dataTable已经存在的情况下，如何再次初始化呢？
我写了一个方法并不是很完善，不知道dataTable有没有专门的配置呢？
        my method:
功能为对tatble所在的dom删除并重建，然后再执行dataTable插件；
```javascript
function refreshTableDom01(strID){
		var newTable = document.createElement("table");
		newTable.id=strID;
		newTable.className="display";
		//将新建的<table>元素放到id="content"的元素下方，作为其子元素

			
	
		var dom1 = document.getElementById(strID+"_wrapper");
		var dom2 = document.getElementById(strID);
		var parent_node = "";
		if(dom1){
			parent_node = dom1.parentNode;
			parent_node.removeChild(dom1);
			console.log(parent_node.id);//textContent
			parent_node.appendChild(newTable);//新建id="template_grid", class="display"的<table>元素
		}
}
```

**Comment by swocn** [comment]
使用ajax动态查询不就行了，你这样写太复杂了

**Comment by jmuchch** [comment]
回复swocn：你是不知道情况，动态查询是没有效果的，第一：执行dataTable时他会对table所在的元素初始化，但发现这个元素已经被初始化后，就会发生错误；第二：假设能够动态ajax查询，但dataTable插件根本不理会你的数据发生变化，而是使用第一次的data数据源；

**Comment by swocn** [comment]
怎么可能，那是你还没有看懂说明书吧，把DataTables的说明，Options仔细阅读下。你时间更改时，使用ajax将数据post过去不就行了。没明白你的意思

**Comment by jmuchch** [comment]
不明白就不明白吧，我用自己的方式解决了，再次点击按钮时，把所有的dataTable嵌入到页面中的代码删掉，然后再通过继承的方式继承$('#example').DataTable({Object});中的{Object}就可以在再次点击查询按钮执行dataTable插件时对<table id="example">dom元素进行表格初始化了

**Comment by jmuchch** [comment]
不明白就不明白吧，我用自己的方式解决了，再次点击按钮时，把所有的dataTable嵌入到页面中的代码删掉，然后再通过继承的方式继承$('#example').DataTable({Object});中的{Object},创建一个新的{Object配置选项}就可以在再次点击查询按钮执行dataTable插件时对\<table  id = "example"\>dom元素进行表格初始化了

**Comment by jmuchch** [comment]
有的数据是直接ajax就可以了，但是有时候需要对返回的数据合并同类项等复杂操作的，这也不是当前问题的主旨

**Comment by swocn** [comment]
看了下，可能是你实例化的方式不一样。
我是这样使用的
var dt = $("#tableid").DataTable({……});
//再需要刷新的地方调用下面这个方法
dt.ajax.reload(null,false)

**Comment by jmuchch** [comment]
嗯嗯，谢谢，以前看的时候好像也见过这样的方式，后来没有找到

**Comment by swocn** [comment]
这样使用，可以使用回调函数，然后调用刷新DataTable，也不像你那样麻烦

**Comment by jmuchch** [comment]
是的

**Comment by swocn** [comment]
所以说，多看说明

**Comment by jmuchch** [comment]
是呀
