### ISSUE TITLE
datatables怎么在ajax中设置contentType='application/json;charset=UTF-8'

### ISSUE THREAD

**Issue by lusirbluesky** [ssy341/datatables-cn#14]
datatables怎么在ajax中设置contentType='application/json;charset=UTF-8'

**Comment by ssy341** [comment]
DataTables是基于jQuery的插件，所有它的ajax实际上就是$.ajax只是DataTables对此进行了扩展（加强）。
所以，能在$.ajax上使用的参数同样也可以在DT中使用，比如：
```
 $("#issueTable").DataTable({
        ajax: {
            url: "https://api.github.com/repos/ssy341/datatables-cn/issues"
            type:"post",
            contentType:'application/x-www-form-urlencoded; charset=UTF-8',
            ……
        }
 });
```
参考：

[jQuery.ajax](http://api.jquery.com/jQuery.ajax/)
[DT.ajax](http://datatables.club/reference/option/ajax.html)

**Comment by linkzyr** [comment]
见如下代码：
`"ajax": {
                type: 'post',
                url: url,
                contentType: "application/json",
                dataType: "json",
                data: function (data) {
                    data.parame = parame;//这里传一些自己需要传的参数
                    return JSON.stringify(data);
                }
            }`
