### ISSUE TITLE
dataTable第一页的td元素  对点击事件有响应，点击下一页，下一页的td元素对点击事件不再有响应

### ISSUE THREAD

**Issue by jmuchch** [ssy341/datatables-cn#142]
点击一个td元素，找到该td元素所在行的所有td元素，并列出与该行相关的详细信息，并把这些详细信息展示在同一页面的另一个dataTable表格里面，但是第一页可以响应点击事件，但第二页就不能响应点击事件代码如下：		
//表格插件	生成表格	
			var tempTable = $('#template_grid').DataTable(table1);//运行dataTable 表格插件;
		    $("#template_grid").colResizable({partialRefresh:true});//拖拽列改变列的宽度;	    
		    //table的 tr 或td点击事件    

**//表格的第二页无法响应下面的点击事件**
			$("#template_grid tbody tr td").on('click.dt', function(){
					//对详细表进行初始化
					if(tableReturn){//假如dataTable被查询过了，那么清除dataTable的数据，并保留原<table>元素
						tableReturn.destroy(false);
						$('#template_gridDetail').empty();
						tableReturn = "";////如果初始化过的table,再进行初始化，table元素也会被删除
					}
//对原始的data合并同类项
					var subTableData = [];
					console.log("td is being  clicked");
					var tdParentNode  = this.parentNode;
					console.log(tdParentNode.tagName);//显示td元素的父元素的标签名
					var tdSet = $(tdParentNode).find("td");
					//console.log(tableData);
					for(var i = 0; i<tdSet.length; i++){
						//console.log(tdSet[i].textContent);
						for(var k = 0, length = tableData.length; k<length; k++){
							//console.log(tableData[k]['GoodsName']);
							if(tdSet[i].textContent == tableData[k]['GoodsName']){
								subTableData.push(tableData[k]);
								//console.log("is right");
							}
						}
					}	
					//第二个表格
		 			var table2 = Object.create(table);
					//表格插件
					table2.data = newData;//重新赋予数据
					tableReturn = $('#template_gridDetail').DataTable(table2);//运行dataTable 表格插件;
			});

**Comment by ssy341** [comment]
@jmuchch  $("#template_grid tbody").on('click.dt'," tr td", function() 这样绑定事件
或者把代码写到 drawCallback 里

**Comment by jmuchch** [comment]
这种方法确实解决了问题，但是在官方文档中为什么找不到相关的说明呢？

**Comment by ssy341** [comment]
@jmuchch 你是采用哪种方式解决的呢？
- 第一种 属于jQuery的知识点，给当前页面的元素（可能还不存在）绑定事件 ，用on，具体你可以查看jQuery的api
- 第二种 [drawCallback](http://datatables.club/reference/option/drawCallback.html) ，如果你弄明白了第一种，这个就好理解了，drawCallback方法是在dt每次重绘都会执行的方法，比如翻页，排序，过滤，所以，把监听事件放在这里是没问题的，因为元素都已经存在了

**Comment by jmuchch** [comment]
这一种：$("#template_grid tbody").on('click.dt'," tr td", function() 这样绑定事件
     “”tr td"这里应该是点击" tr td"，而不是"#template_grid tbody"的意思；你这么一说，我才想起来有这种jquery用法，一般直接用click，所以没有想起来，我之前还以为是dataTable里面的用法呢；

原来是这种写法：$("#template_grid tbody tr td").on('click.dt', function(){
这种写法有什么不妥？

**Comment by ssy341** [comment]
@jmuchch 你提出的这种写法没有什么不妥，你弄清楚dom的创建先后顺序，如果你确保页面上的dom元素一定会在监听事件之前，这样写是没有问题的，但是当有动态绑定的情况（绑定事件的时候元素还不存在）就不能这样写。
$("#template_grid tbody").on('click.dt'," tr td", function() 而且一般不太推荐这种方式，因为从效率上来讲，他会遍历tbody所有的元素，去监听你要绑定的
总得来说这个需要根据自己的实际情况决定究竟使用哪种方式

**Comment by jmuchch** [comment]
thanks very much
