### ISSUE TITLE
关于排序的默认启用问题

### ISSUE THREAD

**Issue by HeavenZhangHr** [ssy341/datatables-cn#144]
当前tr里面有个五个td。
如图
![image](https://cloud.githubusercontent.com/assets/19979240/26687448/4e2748c2-4722-11e7-8bd6-d77c10afe395.png)
初始化刷新页面是以客运站进行排序，
有没有啥办法是以售票金额进行排序

**Comment by ssy341** [comment]
@HeavenZhangHr  [option order 设置排序列(去掉第一列的排序和小图标](http://datatables.club/manual/daily/2016/05/05/option-order.html)

根据你的表格，参考如下代码，第四列升序排列
```javascript
$('#example').DataTable( {
    "order": [[ 3, 'asc' ]]
} );
```

**Comment by HeavenZhangHr** [comment]
谢谢谢谢..真心感谢
