### ISSUE TITLE
datatables固定表头后如何拖动列宽

### ISSUE THREAD

**Issue by xiedaoyun** [ssy341/datatables-cn#145]
datatables固定表头后如何拖动列宽

**Comment by Gabrielkaliboy** [comment]
@xiedaoyun 同问，你的问题解决了吗。。。。

**Comment by CamilleLFL** [comment]
利用colResizable可实现拖动列宽

**Comment by Gabrielkaliboy** [comment]
@CamilleLFL 我用也以后也没有解决。。。。动态获取数据的时候datatable的tbody和thead不在一个table里面，如果写死的时候，这个可以实现。请问你的数据在后台获取过来的，也可以实现拖动码？

**Comment by zjl1985** [comment]
可以的

参考这里https://github.com/Silvacom/colResize

并不是很完美，但是基本实现了大部分的需求
