### ISSUE TITLE
水平滚动条

### ISSUE THREAD

**Issue by junozhou** [ssy341/datatables-cn#148]
当列太多的时候，设置水平滑动条（"scrollX": true,），表头单元格与数据单元格错位，并且在第一行显示排序的图标

**Comment by mawanli** [comment]
请问您这个问题现在已经解决了吗？我也有同样的问题

**Comment by ssy341** [comment]
@junozhou 错位的问题看是不是css样式冲突，用排除法，只引入dt的 css看是否还有问题，如果不能解决，参考 #9 这个
第一列显示排序图标，参考[这个](http://datatables.club/manual/daily/2016/05/05/option-order.html)

**Comment by junozhou** [comment]
后来没用datatables了，bootstrap-table大量列没有这样的问题http://bootstrap-table.wenzhixin.net.cn/zh-cn/documentation/
