### ISSUE TITLE
datatables页面展示有序号，但是导出csv时序号就变成了[object,object]

### ISSUE THREAD

**Issue by henanCaiyao** [ssy341/datatables-cn#15]
哪位知道，望大神指点

**Comment by ssy341** [comment]
@henanCaiyao 你的贴上代码才行 提问参考 #2

**Comment by Crosmile** [comment]
请问问题解决了吗？我是想把数据导出到excel表格，但是导出到excel表格的数据全部为[object,object] ，在网上没查到解决办法，求大神指点，谢谢！

**Comment by occultskyrong** [comment]
已归档到#356
