### ISSUE TITLE
ajax请求出错时的处理？

### ISSUE THREAD

**Issue by moonflower-wang** [ssy341/datatables-cn#156]
$.fn.dataTable.ext.errMode = function( settings, tn, msg){      // 覆盖掉警告弹框（如果有警告的话）
                // doing
};    
 table.on('xhr.dt',function (e, settings, json, xhr) {
                // doing
 });

这两个都是处理出错时的方法吗？它们有什么区别？在两个方法里需要分别判断哪些错误码？每个错误码又分别代表什么？这两个方法需要同时写吗？还是写一个就行？

**Comment by ssy341** [comment]
@moonflower-wang 
不用同时写，前者是改变错误的提示方式，后者是监听xhr事件，当有ajax请求的时候执行方法体
