### ISSUE TITLE
datatable布局先为none，然后再显示时，table表头混乱

### ISSUE THREAD

**Issue by jmycanfly** [ssy341/datatables-cn#157]
具体描述：有个tab切换，没个页面都有table，没有显示的页面display为none。问题在于，之前div为none的里面的table在显示的时候表头是混乱的。
自己试了先将div设为block，然后绑定datatable，然后在隐藏div，但是这样很麻烦。希望寻找另外一个解决方案。

**Comment by ssy341** [comment]
@jmycanfly  参考 #9

**Comment by jmycanfly** [comment]
能追问一下吗？参照 #9的写了，表头错位解决了，但是莫名表头显示了两次，如下图所示。
![image](https://user-images.githubusercontent.com/9840214/27420355-2b1360a0-5758-11e7-8538-77113e585821.png)
检查元素发现，有两个div里面都有table，正常的事第一个显示thead，而第二个的thead是隐藏的。采用了$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();之后，后面一个的thead也显示了，就造成了出现两次表头的问题
![image](https://user-images.githubusercontent.com/9840214/27420468-9206617c-5758-11e7-80c8-b7c9ef796018.png)
