### ISSUE TITLE
查询表格的时候能否将子列表，也就是加号点开之后里边的内容也一起查了？

### ISSUE THREAD

**Issue by zilingliyu** [ssy341/datatables-cn#164]
https://datatables.net/examples/api/row_details.html
各位大神，这个示例上边查询的时候只能查最外层，也是就是没点开加号外边的东西，有没有可能就是在查询的时候，即使不点开加号，也将加号里边的数据查了？

**Comment by ssy341** [comment]
@zilingliyu 一次性查出来和 点了之后再查完全是自己控制的，点开加号数据已经存在，这个取决你数据是从哪里获取，是ajax请求后台还是直接从返回的数据的其他对象里获取

**Comment by zilingliyu** [comment]
@ssy341 你好像理解错我的意思了，我说的不是点加号查数据是如何查的，而是，他不是有一个查询框嘛，在查询框里边输入东西他会过滤下边表格里边的东西，但是过滤的只是外层的东西，点开加号里边的东西不会进行过滤，就是有没有好的方法，在搜索框里边输入东西得时候将外层和加号里边的内层一起进行过滤？
我试着在查外层数据的时候将加号里边的数据也push进去，但是查询的时候还是不会对里边的数据进行过滤，所有还有没有其他的方法？

**Comment by ssy341** [comment]
@zilingliyu  这个还是有点复杂，因为Dt的过滤框是过滤自己内部的数据，你所谓push的数据是已经给了dt的还是，额外的数据，如果是额外的数据肯定是不能用dt自带的搜索框去过滤。我认为你的需求有点奇怪，一个看不到的数据也要做过滤，用户怎么知道？如果我还是理解错了，你再跟帖回复
