### ISSUE TITLE
求助，分页问题

### ISSUE THREAD

**Issue by HyOrange** [ssy341/datatables-cn#165]
我在页面上展示后台数据，点到后几页，然后查询，后台返回时，展示的是查询前的页码，怎样查询时变为第1页？后台将页码设为第1页，但还是查询前的页码？怎样解决

**Comment by ssy341** [comment]
@HyOrange 提问参考#2 关于服务器分页的参考[这里](http://datatables.club/manual/server-side.html)

**Comment by HyOrange** [comment]
@ssy341 请问下，表格重画后，怎样设置为从第1页开始，
$.extend(search, {nickname: myPannel.center.find('input[name="nickname"]').val()});
    	var oSettings = oTable.fnSettings();
    	oTable.fnDraw(oSettings);

**Comment by ssy341** [comment]
@HyOrange 1.9版之前的我不太清楚了，1.10+的  dt.draw();这样就是从第一页开始，在检查有没有使用stateSave这个参数，这个是缓存参数，会缓存表格的状态

**Comment by gyhkevin** [comment]
可以直接定位到第几页吗？比如：在第3页，点击进入一个页面后，返回到原来的页面

**Comment by ssy341** [comment]
@gyhkevin dt.page(3); 直接跳转到第三页
