### ISSUE TITLE
ie9下使用datatables怎么报Uint16Array未定义，有碰到过的没

### ISSUE THREAD

**Issue by jooejooe** [ssy341/datatables-cn#166]
SCRIPT5009: “Uint16Array”未定义 
datatables.js, 行24805 字符1
SCRIPT5007: 无法获取属性“defaults”的值: 对象为 null 或未定义 
dataTables.bootstrap.min.js, 行5 字符350

**Comment by ssy341** [comment]
@jooejooe 提问参考 #2
