### ISSUE TITLE
draw和ajax.reload方法有什么区别

### ISSUE THREAD

**Issue by jonnykay** [ssy341/datatables-cn#167]
比如，我需要改变选中行某个单元格的数据，改变后需要重绘调用了draw方法，但是这时候会调用ajax去后台重新取数据，和调用ajax,reload方法一样，有没有办法在重绘时不调用ajax，由于数据过多，只修改一个单元格的数据，在前端改变数据就可以了不需要再到后端去重新取数据，有大神何以解决吗？

**Comment by sagaxin** [comment]
可以
第一种方法，你可以在前端保存所有数据data1，修改了某个单元格数据之后，再保存修改后的所有数据data2，然后draw（data2）就可以了；
第二种方法，你修改了单元格数据之后，保存该行的修改后的整行数据，删除这行，然后row.add（修改后的行数据）就可以了

**Comment by zjl1985** [comment]
draw是重新绘制，前台dom
ajax。reload是走后台

你这种最好就是，row().data(rowdata).draw()

**Comment by ray-amoy** [comment]
可以尝试用server-side服务器端模式，即使draw重新刷新的也只是当前页的数据，并不会所有数据。
