### ISSUE TITLE
服务器模式时oLanguage设置取不到值

### ISSUE THREAD

**Issue by Jyokiyi** [ssy341/datatables-cn#168]
我启动了服务器模式，
"oLanguage": {
                "sLengthMenu": "每页 _MENU_ 条记录",
                "sZeroRecords": "没有符合条件的数据...",
                "sInfo": "显示 _START_ 到  _END_ 项, 共  _TOTAL_ 项 ",
                "sInfoEmpty": "显示 0 至 0 共 0 项 ",
                "sInfoFiltered": "( _MAX_ )"
            },
oLanguage设置中的 _START_ ，_END_ ，_TOTAL_ 和_MAX_ 都取不到值，_START_，_END_ ，_TOTAL_为0，_MAX_ 为NaN ,不知道为什么，求解

**Comment by ssy341** [comment]
@Jyokiyi 提问参考#2 ,服务器模式贴出服务器返回的数据，另外参考[服务器模式](http://datatables.club/manual/server-side.html)返回数据格式
