### ISSUE TITLE
怎么合并内容相同的列

### ISSUE THREAD

**Issue by tonysup** [ssy341/datatables-cn#169]
类似于excel里面的合并单元格。前两列，内容相同的合并。合并后如类似效果。
|        |           |A|   
|2017|一年级|B|
|        |           |C|

**Comment by tonysup** [comment]
问题已解决，现学现卖。解决方法：
datatables异步加载。
`"drawCallback": function ( settings, json ) {
            var rows = $("#example").dataTable().fnGetNodes();
       	    var first_instance = null;
            var rowspan = 1;
            for(var j=0;j < rows.length; ++j){
            	var dimension_td = $(rows[j]).find("td:eq(1)");
            	if (first_instance == null) {
                    first_instance = dimension_td;
                } else if (dimension_td.text() == first_instance.text()) {
                    dimension_td.remove();
                    ++rowspan;
                    first_instance.attr('rowspan', rowspan);
                } else {
                    first_instance = dimension_td;
                    rowspan = 1;
                }
        	}`

另外合并后的居中显示需要添加：
`table.dataTable tbody td{
 vertical-align:middle !important;
}`

**Comment by nemo733** [comment]
赞一个！！！

**Comment by zhisheng17** [comment]
这个合并使用的是这个drawCallback的，如果使用这个的话，需要禁用dataTables的选择每页显示条数、排序和搜索功能，因为这几项都会修改table的展示，每一次都会调用drawCallback，从而会造成table变形和数据丢失的情况。那么如果我需求要 合并单元格、搜索、排序这些功能都共存的话，楼主有什么解决的方法吗？

**Comment by Martin0126** [comment]
正好需要，棒棒

**Comment by huangjiaxiang** [comment]
> 这个合并使用的是这个drawCallback的，如果使用这个的话，需要禁用dataTables的选择每页显示条数、排序和搜索功能，因为这几项都会修改table的展示，每一次都会调用drawCallback，从而会造成table变形和数据丢失的情况。那么如果我需求要 合并单元格、搜索、排序这些功能都共存的话，楼主有什么解决的方法吗？

你好，找到共存的方式了吗
