### ISSUE TITLE
关于datatables搜索功能-时间段内

### ISSUE THREAD

**Issue by ILoveMyJay** [ssy341/datatables-cn#17]
input中输入开始时间2014-05-13和结束时间2016-06-23，怎么筛选时间段内的数据

**Comment by ssy341** [comment]
@ILoveMyJay  自定义过滤 - 范围搜索 API 示例 Datatables中文网: http://datatables.club/example/plug-ins/range_filtering.html

参考这个例子

**Comment by ILoveMyJay** [comment]
嗯，学习了 😊

2016-09-01 0:11 GMT+08:00 Keith <notifications@github.com>:
