### ISSUE TITLE
初次调用DT会发送两次请求到后台

### ISSUE THREAD

**Issue by luobocai** [ssy341/datatables-cn#170]
点击按钮，弹出框内加载表格，第一次点击时，DT往后台发送了两次请求（severSide），第一次请求没有参数(draw,start……),第二次请求才有参数。
另外，第一次点击按钮，第二次请求获取到数据，却没有把数据加载到table中。第二次点击按钮能正常读取数据。

**Comment by ssy341** [comment]
@luobocai 贴上代码，代码肯定有问题
