### ISSUE TITLE
想在表格右上角 加csv按钮，代码如下 但是结果却是一个 print按钮，求解答

### ISSUE THREAD

**Issue by Mark2hou** [ssy341/datatables-cn#172]
"buttons":[{
				"extend" : 'excel',
	            "text" : 'Save current page',
	            },{
	            	"extend" : "csvhtml5",
	            	"text" : "hahaha"
	            }
	            	]
			}

**Comment by ssy341** [comment]
@Mark2hou 简单的buttons文档[参考](http://datatables.club/extensions/buttons/)
[csv按钮例子](https://datatables.net/extensions/buttons/examples/initialisation/simple.html)
