### ISSUE TITLE
dataTable对json数据格式有没有什么要求？

### ISSUE THREAD

**Issue by geminiyu233** [ssy341/datatables-cn#173]
现在有一个json对象，里面有一个字段用来指定渲染数据时渲染到表头的指定列，而且表头是复杂表头，这种情况还能用dataTable渲染数据吗，复杂表头的排序和分页功能会不会失效？！！

**Comment by ssy341** [comment]
@geminiyu233 参考 [data](http://datatables.club/manual/data.html) ，根据你的描述，可能比较复杂，需要你提供代码和返回的数据样例及期望的展现样子
关于复杂表头，你[参考](http://datatables.club/example/basic_init/complex_header.html)
表头排序监听控制[参考](http://datatables.club/reference/option/orderCellsTop.html)
