### ISSUE TITLE
fnClearTable is not a function

### ISSUE THREAD

**Issue by breathless1992** [ssy341/datatables-cn#175]
清空表格的时候为什么会提示fnClearTable不是一个函数？求大神指点

**Comment by ssy341** [comment]
@breathless1992 提问参考#2 ，请提供初始化代码和使用的DT版本，已经报错代码 部分

**Comment by breathless1992** [comment]
[版本号是1.10.7
![1](https://user-images.githubusercontent.com/23231555/28096707-681c8410-66dd-11e7-807e-9cbe5ffbdd95.png)这是我初始化的地方.
![2](https://user-images.githubusercontent.com/23231555/28096729-962fd38e-66dd-11e7-82be-933a7c599bd1.png)
这是我调用的地方,清空的时候就报错了

**Comment by breathless1992** [comment]
跟版本应该没问题吧，下载官网的版本还是会报同样的错，不知道为什么

**Comment by ssy341** [comment]
@breathless1992 不对，你初始化那个参数错了，managementTable 这个 应该是  
```javascript
managementTable  = $("#example").DataTable({……});
managementTable.clear();//你的写法过时了，建议这种写法
managementTable.destroy();
···

**Comment by breathless1992** [comment]
var Classifications = $('#example');
Classifications.fnClearTable(); 
Classifications.fnDestroy(); 
iniTable(allJson,columns,Classifications,10);
我之前有个例子这样写的，就没有报错，第二个例子写的时候就报错不是一个函数了，写法是一模一样的啊

**Comment by ssy341** [comment]
@breathless1992 你又错了，是 var managementTable = $('#example').DataTable({……});这样

**Comment by breathless1992** [comment]
function iniTable(dataJson, columns, everyTables, num) {
    everyTables.DataTable({
        "aLengthMenu": [num, 25, 50, -1],
        "paging": true,
        "lengthChange": false,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "language": {
            "sProcessing": "处理中...",
            "sLengthMenu": "显示 _MENU_ 项结果",
            "sZeroRecords": "没有匹配结果",
            "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
            "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
            "sInfoFiltered": "(有 _MAX_ 项结果过滤)",
            "sInfoPostFix": "",
            "sSearch": "搜索:",
            "sUrl": "",
            "destroy":true,
            "sEmptyTable": "表中数据为空",
            "sLoadingRecords": "载入中...",
            "sInfoThousands": ",",
            "oPaginate": {
                "sFirst": "首页",
                "sPrevious": "上页",
                "sNext": "下页",
                "sLast": "末页"
            },
            "oAria": {
                "sSortAscending": ": 以升序排列此列",
                "sSortDescending": ": 以降序排列此列"
            }
        },
        "data": dataJson,
        "columns": columns,
    });
}
不是啊，我是写在这个方法里面，然后带了4个参数.
var managementTable = $('#table1');
managementTable.clear();
managementTable.destroy();
然后直接调用这个方法,里面带了四个参数啊
iniTable(resultAllJson,columns,managementTable,100);

**Comment by breathless1992** [comment]
var managementTable  = $("#table1").DataTable({
                    "aLengthMenu": [25, 50, 100],
                    "paging": true,
                    "lengthChange": false,
                    "searching": true,
                    "ordering": true,
                    "info": true,
                    "autoWidth": false,
                    "language": {
                        "sProcessing": "处理中...",
                        "sLengthMenu": "显示 _MENU_ 项结果",
                        "sZeroRecords": "没有匹配结果",
                        "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                        "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
                        "sInfoFiltered": "(有 _MAX_ 项结果过滤)",
                        "sInfoPostFix": "",
                        "sSearch": "搜索:",
                        "sUrl": "",
                        "destroy":true,
                        "sEmptyTable": "表中数据为空",
                        "sLoadingRecords": "载入中...",
                        "sInfoThousands": ",",
                        "oPaginate": {
                            "sFirst": "首页",
                            "sPrevious": "上页",
                            "sNext": "下页",
                            "sLast": "末页"
                        },
                        "oAria": {
                            "sSortAscending": ": 以升序排列此列",
                            "sSortDescending": ": 以降序排列此列"
                        }
                    },
                    "data": resultAllJson,
                    "columns": columns,
				});
                managementTable.clear(); 
                managementTable.destroy();
我这样的话，底下两个还是会报错不是一个函数

**Comment by breathless1992** [comment]
谢谢大神指点，问题解决了。
