### ISSUE TITLE
分页显示的问题

### ISSUE THREAD

**Issue by thatalltall** [ssy341/datatables-cn#178]
怎么让分页的图标显示左右箭头的形式，不用英文代替。
是利用jQuery UI 吗

**Comment by ssy341** [comment]
@thatalltall  参考这个：
 [language.paginate.last](http://datatables.club/reference/option/language.paginate.last)
 [language.paginate.next](http://datatables.club/reference/option/language.paginate.next)
 [language.paginate.previous](http://datatables.club/reference/option/language.paginate.previous)
 [language.paginate.first](http://datatables.club/reference/option/language.paginate.first)
