### ISSUE TITLE
AJAX怎么添加导出打印按钮这些啊？

### ISSUE THREAD

**Issue by w5882033wen** [ssy341/datatables-cn#18]

**Comment by ssy341** [comment]
@w5882033wen 提问参考 #2

**Comment by w5882033wen** [comment]
我解决了这个问题了！打印是没有问题的，但是导出不行，同样的配置放到普通的表单就是可以的！

**Comment by ssy341** [comment]
@w5882033wen  太模糊了，解决了 你最好说下你究竟遇到的是什么问题，导出不行又具体指的什么？
