### ISSUE TITLE
重写 render 后 排序功能不好用了

### ISSUE THREAD

**Issue by hezhenxue** [ssy341/datatables-cn#181]
columnDefs: [
        {
            render: function (data, type, row, meta) {
                var html = '<input  id= ' + row.ID + ' type="button" value="' + data + '"  style="width: 100%">                  </input>';
                return html;
            },
            targets: 8
        },

**Comment by ssy341** [comment]
@hezhenxue 
```javascript
$('#example').dataTable( {
  "columnDefs": [ {
    "targets": 4,
    "data": "description",
    "render": function ( data, type, full, meta ) {
      return type === 'display' && data.length > 40 ?
        '<span title="'+data+'">'+data.substr( 0, 38 )+'...</span>' :
        data;
    }
  } ]
} );
```
注意四个参数里的type类型，具体参考[这里](http://datatables.club/reference/option/columns.render.html)
也就是说，当作为显示的时候，是一种处理，当排序的时候是一种处理，当过滤的时候又是一种处理，这个就是DT的正交数据（我管他叫数据和显示分离）
