### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by chengduxiaohua** [ssy341/datatables-cn#183]
你好,我这边也出现了分页问题，分页按钮不管点击哪一个都会产生下一页的效果，比如我一直点第一页，他会自动的往下加页数`  serverSide: true,//分页，取数据等等的都放到服务端去
        processing: true,//载入数据的时候是否显示“载入中”
        pageLength: 10,  //首次加载的数据条数
        ordering: false, //排序操作在服务端进行，所以可以关了。
        pagingType: "full_numbers",
        autoWidth: false,
        stateSave: false,//保持翻页状态，和comTable.fnDraw(false);结合使用
        searching: false,//禁用datatables搜索`这是我的配置

**Comment by ssy341** [comment]
@chengduxiaohua 你说的增加是draw吗？这个参数参考[服务器模式](http://datatables.club/manual/server-side.html)
