### ISSUE TITLE
分页获取其他页的数据

### ISSUE THREAD

**Issue by shenqihailuoya** [ssy341/datatables-cn#187]
我在第一页勾选了三条数据，然后又在第二页勾选了两条数据。在点击提交的时候，我遍历了当前table中的checkbox，如果为选中状态就把这条数据放在一个数组中，但是我发现只有第二页中的两条数据。

**Comment by ssy341** [comment]
@shenqihailuoya 你数组要定义为全局变量，这样就能记录你每一页勾选的数据
