### ISSUE TITLE
datatables分页

### ISSUE THREAD

**Issue by ZMbenJ** [ssy341/datatables-cn#190]
通过ajax请求返回的数据中含有两层循环，即相当于检索店铺中的订单列表，每一个订单又包含产品列表，分页是在检索订单的时候进行，把数据显示在jsp上时怎么把产品的列表显示出来

**Comment by ssy341** [comment]
@ZMbenJ  你可能需要这样的例子 [row_details](http://datatables.club/example/api/row_details.html)
ajax的再参考#174
