### ISSUE TITLE
文档里的小瑕疵。

### ISSUE THREAD

**Issue by kongtianyi** [ssy341/datatables-cn#191]
http://www.datatables.club/manual/server-side.html
在这篇文档中，应为`serverSide`的地方都写成了`serverSideOption `，应为`ajax`的地方都写成了`ajaxOption ajax不定时一讲`，作者大佬一Ctrl+F便知。

**Comment by ssy341** [comment]
@kongtianyi 谢谢你指出该错误，实际上是css样式影响导致，目前已经修复了
