### ISSUE TITLE
当点击表格的行时，在这行的下面展示一个表格，该怎么弄啊，请求大神帮忙，这个点击事件咋触发啊？

### ISSUE THREAD

**Issue by HyOrange** [ssy341/datatables-cn#192]

**Comment by GQ-Jesse** [comment]
![image](https://user-images.githubusercontent.com/27001132/29206834-4510b374-7eb6-11e7-8ba2-8ab10744a237.png)
建议你用树表实现：tree-grid

**Comment by Ivernsky** [comment]
tree-grid 是怎么配置的，刚好需要

**Comment by HyOrange** [comment]
@GQ-Jesse 3q

**Comment by GQ-Jesse** [comment]
@Ivernsky 
你好，可以参考文档来配置。基本不用配置，将这个插件下载下来，引入到你的项目中就可以用的。只要注意数据格式要与文档示例中的数据格式保持一致即可。
这是基于JQ的文档：
http://maxazan.github.io/jquery-treegrid/
个人是基于AgularJS1.4版本开发过程中使用的tree-grid

**Comment by GQ-Jesse** [comment]
@Ivernsky 这是Angular的demo:
http://khan4019.github.io/tree-grid-directive/test/treeGrid.html

**Comment by ssy341** [comment]
@HyOrange 看中文网例子[显示行的附加信息](http://datatables.club/example/api/row_details.html)
