### ISSUE TITLE
使用服务器处理(Server-side processing)模式输入汉字出错的问题

### ISSUE THREAD

**Issue by 80xp** [ssy341/datatables-cn#194]
1.连接数据库建立表datatables_demo，并插入数据；
2.修改server_sideprocessing.php中数据库信息
3.刷新server_side.html可以正确显示数据库中数据，输入数字和英文字母进行搜索显示正常；
但输入汉字进行搜索时会报错，具体报错信息：
`DataTables warning:table id=example - An SQL error occurred:
SQLSTATE[HY000]:General error:1271 Illegal mix of collations for
operation 'like'`

求解决方法求指教。
我是新手，PHP都不太会只会最简单。

**Comment by ssy341** [comment]
@80xp 这个是后台问题，根据错误提示翻译为发生了一个sql错误，和DT没有关系
