### ISSUE TITLE
请问导出excel的样式可以设置吗

### ISSUE THREAD

**Issue by zs2402923847** [ssy341/datatables-cn#195]
按官网例子导出太丑了，另外能否设置某一表头对应那一列不导出？

**Comment by NijatInHIT** [comment]
导出的例子能给我发个链接么？

**Comment by zs2402923847** [comment]
@NijatInHIT   代码集成在项目里面了，而且现在我都改成后台导出excel，这个方便是方便，但是导出效果太差，http://blog.csdn.net/liuyuqin1991/article/details/74980616  之前我是参考的这篇文章最下面的例子

**Comment by ssy341** [comment]
@zs2402923847    参考[buttons.exportData()](https://datatables.net/reference/api/buttons.exportData())，设置指定的列导出，button限制很大，不太灵活，复杂的导出不推荐直接使用button，java可以用poi实现excel导出，满足更复杂的业务需求

**Comment by ssy341** [comment]
@NijatInHIT 例子可以参考[这个](http://datatables.club/extensions/buttons/examples/initialisation/simple.html)

**Comment by occultskyrong** [comment]
已归档到 #356
