### ISSUE TITLE
table内容如果很多，如何出现x轴的滚动条？设置sScrollX不起作用！

### ISSUE THREAD

**Issue by TerryLess** [ssy341/datatables-cn#197]
动态加载出来的html和数据，无法出现x轴的滚动条

<div id="mainTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
        <table class="table table-hover table-bordered table-datatable table-striped no-footer dataTable" id="mainTable" role="grid" aria-describedby="mainTable_info">
            <thead>
                <tr role="row">
                    <th class="sorting_disabled" rowspan="1" colspan="1">
                        <div class="th-dynamic">姓名</div>
                    </th>
                    <th class="sorting_disabled" rowspan="1" colspan="1">
                        <div class="th-dynamic">学号</div>
                    </th>
                    <th class="sorting_disabled" rowspan="1" colspan="1">
                        <div class="th-dynamic">班级</div>
                    </th>
                    <th class="sorting_disabled tab-cont-center base-score" rowspan="1" colspan="1">
                        <div class="data-dynamic">小学语文(6学分)<br><span style="font-weight:400;">（分数/补考）</span></div>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr role="row" class="odd">
                    <td>小巷3</td>
                    <td>G81610103</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score"><span class="red">51.45</span>/60.00</td>
                </tr>
                <tr role="row" class="even">
                    <td>小巷4</td>
                    <td>G81610104</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">70.30</td>
                </tr>
                <tr role="row" class="odd">
                    <td>小巷5</td>
                    <td>G81610105</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">73.55</td>
                </tr>
                <tr role="row" class="even">
                    <td>小巷6</td>
                    <td>G81610106</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">85.25</td>
                </tr>
                <tr role="row" class="odd">
                    <td>小巷7</td>
                    <td>G81610107</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">91.75</td>
                </tr>
                <tr role="row" class="even">
                    <td>小巷8</td>
                    <td>G81610108</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score"><span class="red">54.70</span>/66.00</td>
                </tr>
                <tr role="row" class="odd">
                    <td>小巷9</td>
                    <td>G81610109</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">82.65</td>
                </tr>
                <tr role="row" class="even">
                    <td>小巷10</td>
                    <td>G81610110</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">60.55</td>
                </tr>
                <tr role="row" class="odd">
                    <td>小巷11</td>
                    <td>G81610111</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">78.75</td>
                </tr>
                <tr role="row" class="even">
                    <td>小巷12</td>
                    <td>G81610112</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score"><span class="red">52.75</span>/63.00</td>
                </tr>
                <tr role="row" class="odd">
                    <td>小巷13</td>
                    <td>G81610113</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score"><span class="red">56.00</span>/68.00</td>
                </tr>
                <tr role="row" class="even">
                    <td>小巷14</td>
                    <td>G81610114</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">82.00</td>
                </tr>
                <tr role="row" class="odd">
                    <td>小巷15</td>
                    <td>G81610115</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">87.20</td>
                </tr>
                <tr role="row" class="even">
                    <td>小巷16</td>
                    <td>G81610116</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score">71.60</td>
                </tr>
                <tr role="row" class="odd">
                    <td>小巷17</td>
                    <td>G81610117</td>
                    <td>小学2016级1班</td>
                    <td class=" tab-cont-center base-score"><span class="red">59.90</span>/69.00</td>
                </tr>
            </tbody>
        </table>
    </div>

**Comment by ssy341** [comment]
@TerryLess 参考这个[例子](http://datatables.club/example/basic_init/scroll_xy.html)，当调整浏览器大小的时候，横向滚动条就会出现
