### ISSUE TITLE
请问如何控制ajax请求的发出？

### ISSUE THREAD

**Issue by kongtianyi** [ssy341/datatables-cn#198]
我希望能在ajax请求发出前做一个是否发出请求的判断，在某种条件下不发出请求。
点击按钮的时候可以很轻松的在按钮的onclick事件里先判断再ajax.reload()；但是在点击翻页按钮的时候，在后端分页模式下，自动向后台发送了ajax请求，我希望这个ajax请求也能被我控制，我该怎么做呢？

**Comment by thiethirdsun** [comment]
这个配置项可以满足你吧：deferLoading

**Comment by kongtianyi** [comment]
好像不可以，deferLoading是让DataTable不能进行初始请求，而是使用页面上已经存在的数据。我的问题在于我希望在每一次请求发出前都能做一个判断，如果不符合我的条件，我希望这个请求并不能被发出。

**Comment by ssy341** [comment]
@kongtianyi 你这个不是Datatables的范畴了，需要考虑业务为什么希望做到这种

**Comment by MonikaCY** [comment]
##

**Comment by wangyunfan418** [comment]
yes!
