### ISSUE TITLE
DataTables锁定列后，firefox里表头出现滚动条（IE、chrome不会出现），如何去掉？（不锁定列的话，表头不会出现滚动条）

### ISSUE THREAD

**Issue by cag2050** [ssy341/datatables-cn#20]
重现方法（打开下面网址）：在firefox浏览器里，将横向滚动条拖动最右边，表头出现滚动条，如何去掉？
示例代码：http://runjs.cn/code/gekre9nb
预览：http://sandbox.runjs.cn/show/gekre9nb
火狐下效果
![ff](https://cloud.githubusercontent.com/assets/1725705/18191748/4c8f9a30-7100-11e6-8a51-1513a960f99c.png)
chrome下效果
![chrome](https://cloud.githubusercontent.com/assets/1725705/18191752/52b42d72-7100-11e6-9066-dc0efc6f3b4e.png)

**Comment by ssy341** [comment]
@cag2050  看了下，火狐下是出现了表头里垂直滚动条，但实际是无法滚动，感觉像兼容性问题，FF走不寻常路线？

**Comment by Jandaes** [comment]
会不会是兼容性问题、或者是火狐版本太低！以前遇到过类似的、更新一下就可以了

**Comment by linkzyr** [comment]
试试这个`            $.fn.dataTable.tables({
                visible: true,
                api: true
            }).columns.adjust().draw();`

**Comment by cag2050** [comment]
@Jandaes 火狐是最新版48.0.2。

**Comment by cag2050** [comment]
问题解决了。给这个div加了样式。
.dataTables_scrollHead {
    border-right: 17px solid white !important;
    box-sizing: border-box;
}
