### ISSUE TITLE
reload的时候更改参数列表

### ISSUE THREAD

**Issue by elfasd** [ssy341/datatables-cn#201]
我的一个表格有70多个字段，调用destroy()方法的时候，ie 耗时4秒多, chrome耗时2秒多，所以我想采用reload的方式重新加载，但是查询条件带不进去，他一直用的是DT初始化的时候的参数，这个怎么修改下呢？
或者，怎么样提高destroy的效率呢？

**Comment by hbliyafei** [comment]
var name = $("#seName").val();
 var admin = $("#seAdmin").val();
var param = {
        "obj.name": name,
        "obj.admin": admin
};
table.settings()[0].ajax.data = param;
table.ajax.reload();

**Comment by elfasd** [comment]
通过下面的方法获可以解决了：
data: function (d) {
                var tmp = $("#"+innerFormId).serializeArray();
				var param = {};
                param.draw = d.draw;
                param.start = d.start;
                param.length = d.length;
                tmp.forEach(function (e) {
                    param[e.name] = e.value;
                    console.log(e.name);
                });
                return param;
            },
