### ISSUE TITLE
设置了中文语言， dom添加自定义元素无法显示

### ISSUE THREAD

**Issue by shaohui-wang** [ssy341/datatables-cn#202]
"dom": 'l<"#dataTables_toolbar.dataTables_toolbar">rtip',
// "language": {
// 	"url": "/vendors/datatables.net-language/Chinese.json"
// },

![image](https://user-images.githubusercontent.com/30097401/29448024-46eec6ba-8427-11e7-8c32-cf182b3c8f5f.png)

这个问题有解决方案吗？

**Comment by shaohui-wang** [comment]
应该是language异步加载的缘故，求大神支招

**Comment by ssy341** [comment]
@shaohui-wang 请把你的代码放在initComplete回调方法里去调用，确实是你说的异步的问题，参考[这里](http://datatables.club/reference/option/language.url.html)

**Comment by shaohui-wang** [comment]
谢谢 @ssy341
