### ISSUE TITLE
在所有列内容显示之前，添加一列。如何处理：该列会影响到数据列数据和字段对应关系？

### ISSUE THREAD

**Issue by hokyam** [ssy341/datatables-cn#210]
通过ajax从数据库获取到数据，想在数据显示时添加一列，该列是用来显示是否选择对应该行数据的。但是在操作中发现 原来数据对应关系混乱了 。
如果我将该列插入到数据列的最后，数据对应关系是正常的。

columnSet.push({data: null, defaultContent: '', className: 'select-checkbox', orderable: false }); 

columnSet为从数据库获取数据的字段名数组，

下为table页的初始化功能以及添加第一列的功能操作
    var tableOption = {
        dom: "Tlfrtip",       
        bAutoWidth: false,
        bInfo: true,
        bPaginate: true,
        bDestroy: true,
        scrollX: true,
        aaSorting: [[1,"desc"]],
        select:true,
        oLanguage: {
            sEmptyTable: "无记录",
            sZeroRecords: "无记录",
            sLengthMenu: "每页记录数: _MENU_",
            sSearch: "搜索:",
            sInfo: "显示 _START_ to _END_, 总记录: _TOTAL_",
            sZeroRecords: "没有匹配的记录",
            sInfoFiltered: "(从总共_MAX_条记录中筛选)",
            sInfoEmpty: "记录数:0",
            oPaginate: {"sFirst": "首页",sLast:"末页",sNext:"下一页",sPrevious:"上一页"}
        },
        columns:columnSet,
        tableTools:{
            sRowSelect: "os",
            aButtons: [
                {sExtends: "editor_create", editor: $editor, sButtonText: "添加", formButtons: ['确定', {label: '取消', fn: function(){this.close();}}] },
                {sExtends: "text", sButtonText: "消缺", fnClick: function ( nButton, oConfig, oFlash ) {  initDataStepShowTmp();}},
            ],
        }
    };     $table = $('#stationContainer').DataTable(tableOption);

    var str = $("<input type = 'checkbox' id = 'checkAll'>");
    $(".sorting_disabled").append(str);

添加选中列到尾部时（尾部插入选择元素到columnSet）
![image](https://user-images.githubusercontent.com/29119228/29851530-128ca862-8d67-11e7-8da8-5c95f62210d1.png)

添加选中列到第一列（头插入元素到columnSet）时效果图
![image](https://user-images.githubusercontent.com/29119228/29851432-9711c01e-8d66-11e7-8bda-483d83a728be.png)

比对两图发现从缺陷表单字段开始出现数据对应出错问题。

**Comment by ssy341** [comment]
@hokyam 添加checkbox的正确方式参考[这里](http://datatables.club/manual/daily/2016/04/25/option-columns-render1.html)

**Comment by hokyam** [comment]
@ssy341 谢谢！！！

**Comment by hokyam** [comment]
@ssy341  谢谢你的回复。我的问题是在render时出现的
