### ISSUE TITLE
怎么实现在客户端对当前页的数据排序

### ISSUE THREAD

**Issue by ch-masan** [ssy341/datatables-cn#214]
ajax动态获取数据，并进行服务端分页 "serverSide": true,    我怎么实现 在客户端对当前页的数据进行排序，不发送后台请求到数据库排序

**Comment by ssy341** [comment]
@ch-masan DT默认不支持

**Comment by ch-masan** [comment]
@ssy341 我修改了源码，实现了当前页排序功能，目前测试没有发现问题，你给评测一下是否合理可行

修改方法：_fnBuildAjax
修改前代码：
![1](https://user-images.githubusercontent.com/4328833/30092498-eba92aaa-92f1-11e7-8b55-5c579c986851.png)

修改后代码:
![22](https://user-images.githubusercontent.com/4328833/30092592-5941b8de-92f2-11e7-8ab2-11efe60b7057.png)


代码：

                        var jsonData_c = oSettings.json;
			if(jsonData_c){
				
				var data_c = jsonData_c.data; //上次请求获取到的数据列表， 只有在发送后台请求后才会有数据
				var draw_c = oSettings.json.draw; //draw 第几次请求
				/**
				 * 
				 * 1、draw 默认进来第一次不去查询数据库，前台列表显示为空
				 * 2、在点击 "查询" 按钮时去后台获取数据， 或者 第一次点击列排序，‘data_c’ 上次的数据列表为空时 去后台获取数据
				 * 3、在有数据的情况下，点击列 进行js排序，draw 加 1
				 * 
				 * */
				if(data_c.length > 0 && draw_c >= 2 ){ 
					
					jsonData_c.draw = (draw_c + 1);
					var orderBy_c = data.order; // 排序字段，是一个数组，可以多列排序
					var columns_c = data.columns; // 所有的列
					
					for(var i=0;i<orderBy_c.length;i++){
		                var columnName = columns_c[orderBy_c[i].column].data; //areaCode locCode
		                var sortDir = orderBy_c[i].dir; //asc desc
		                
		                console.log("columnName===",columnName, "   sortDir===",sortDir);
		                
		                data_c = _cDataSort(data_c, columnName, sortDir); //对数据进行排序
		            }
					jsonData_c.data = data_c; //重新赋值给 oSettings.json 对象
					
					callback( jsonData_c );
				}else{
					oSettings.jqXHR = $.ajax( $.extend( baseAjax, ajax ) );
				}
			}else{
				oSettings.jqXHR = $.ajax( $.extend( baseAjax, ajax ) );
			}
			
			// Object to extend the base settings
			//oSettings.jqXHR = $.ajax( $.extend( baseAjax, ajax ) );
			
			// Restore for next time around
			ajax.data = ajaxData;

排序方法：

   
       function _cDataSort(listData, columnName, sortDir) { 

        var orderColumn = new Array();

        for(var i=0;i<listData.length;i++){
            var columnValue = listData[i][columnName];
            orderColumn.push({
                index: i,
                columnValue: columnValue
            });
        }

        orderColumn.sort(function (a, b) {
            var valueA = a.columnValue;
            var valueB = b.columnValue;
            if(valueA==null){
                valueA = '-1';
            }
            if(valueB==null){
                valueB = '-1';
            }
            var sortVal = 0;
            if (valueA > valueB) {
                sortVal = 1;
            }
            if (valueA < valueB) {
                sortVal = -1;
            }
            if (sortVal !== 0 && sortDir === 'desc') {
                sortVal = sortVal * -1;
            }
            return sortVal;
        });
        var sortData = new Array();
        for(var j=0;j<orderColumn.length;j++){
            sortData.push(listData[orderColumn[j].index]);
        }
        return sortData;
    }

**Comment by ssy341** [comment]
@ch-masan 首先不得不佩服的是你通过自己的方法实现了最终的效果，点个赞。不过一般来讲，不推荐修改源码达到效果，针对这个当前页排序的 ，在之前也有很多小伙伴提到过，个人觉得这个和自己 的业务紧密相关，通常情况下排序 指的是对所有数据进行排序，而且会事先在数据库排序好后再把数据返回（物理分页）。而在特殊情况下，即目前你需要的，我觉得不应该放在DT初始化上，这样就限制了排序方式，应该以大众的为主，即默认就是所有数据排序，给出另外的开关，或者什么操作来控制，是否进行当页按照某一列排序

**Comment by qiezis** [comment]
@ch-masan 能分享下修改后的代码文件么
