### ISSUE TITLE
<>符号无法search出来

### ISSUE THREAD

**Issue by JianiYang** [ssy341/datatables-cn#216]

**Comment by JianiYang** [comment]
<>同事出现大于小于号就会有

**Comment by occultskyrong** [comment]
前端 `urlEncode ` 下 ，使用 `JavaScript` 的 `encodeURI` 方法
后端接收到之后自行`decode`下

> https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

```
encodeURI('<>')
"%3C%3E"
```
