### ISSUE TITLE
checkbox 表头  全选/全不选

### ISSUE THREAD

**Issue by a51764579** [ssy341/datatables-cn#217]
columnDefs: [ {
			orderable: false,
			className: 'select-checkbox',
			targets:   0
		} ],select: {
			style:    'os',
			selector: 'td:first-child,th:first-child'
}
使用该配置初始化datatables时，无法在thead中对应列添加checkbox以及对应的样式和事件(全选/全不选)，是需要自己封装吗？

**Comment by ssy341** [comment]
@a51764579 关于在列中怎么添加checkbox可以参考[这里](http://datatables.club/manual/daily/2016/04/25/option-columns-render1.html)，thead添加checkbox是需要自己手动添加，DT没有提供
