### ISSUE TITLE
我本地的数据源， 如何重新赋值？？？

### ISSUE THREAD

**Issue by minterjiang** [ssy341/datatables-cn#220]
我本地的数据源， 如何重新赋值？？？

**Comment by liwei511** [comment]
table设置属性：destroy: true,

**Comment by ssy341** [comment]
@minterjiang 麻烦贴出现有的初始化代码

**Comment by ssy341** [comment]
@minterjiang 你是本地的数据源，你需要结合这几个方法 [rows.add()](https://datatables.net/reference/api/rows.add())，[draw()](https://datatables.net/reference/api/draw())和[data()](https://datatables.net/reference/api/data())
- `rows.add()` 用来添加数据到表格中
- `draw()` 改变数据后，需要调用此方法重绘表格（也就是你所谓的刷新）
- `data()` 用来获取表格的结果集
