### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by huangcunqing** [ssy341/datatables-cn#221]
怎么控制在刷新页面的时候保留当前页的界面不会回到第一页，如：现在我在第五页  刷新页面的时候我希望还是在第五页。。。。求大神帮忙看下有没这个配置

**Comment by ssy341** [comment]
@huangcunqing [stateSave](http://datatables.club/reference/option/stateSave.html)这个参数应该是你需要的

**Comment by ssy341** [comment]
@huangcunqing [stateSave](http://datatables.club/reference/option/stateSave.html)这个参数应该是你需要的
