### ISSUE TITLE
设置列宽无效

### ISSUE THREAD

**Issue by HyOrange** [ssy341/datatables-cn#222]
![image](https://user-images.githubusercontent.com/24643805/30264277-ae928be4-970a-11e7-973c-e37f3ac10d65.png)
![image](https://user-images.githubusercontent.com/24643805/30264299-bd63dae2-970a-11e7-845c-736c897f93e8.png)
设置了bAutoWidth为false,怎么还是不能设置列宽？？？？

**Comment by a51764579** [comment]
难道没有解决办法吗？

**Comment by devilRj** [comment]
we can use a callback , called 'initComplete', to solve this problem. In this function we could use jQuery to get <td> tab which you want resize it‘s width. then use ".css()" method to change its width.

> eg.
`'initComplete: function(){
    
> get your <td> tabs
   var tds = $(this).find('tr td');

> change their's style
 tds.css('wdith', ‘50px’);

}'`

**Comment by devilRj** [comment]
Use **'columnDefs'** as param to DataTable constructor. There is a example that I want my **first colum** have a **width** as  **10%**：
>"targets" indicate which column you want specific
`"columnsDefs": [`
`         {"targets": [0], width: "10%"}` 
`         ...`
`]`
You  can also find API here: [https://datatables.net/reference/option/columns.width](url)
