### ISSUE TITLE
页面在加载时会闪一下才初始化,如何解决，如下图

### ISSUE THREAD

**Issue by beautifuldays** [ssy341/datatables-cn#223]
![qq 20170912111832](https://user-images.githubusercontent.com/29110181/30306700-50e75de2-97ac-11e7-90f4-6bd6be5e776b.png)
![qq 20170912111907](https://user-images.githubusercontent.com/29110181/30306699-50e54ffc-97ac-11e7-8b79-3b917d922fbd.png)

**Comment by ssy341** [comment]
@beautifuldays 方便贴出初始化代码么？这个是在页面弹出新的页面还是tab标签还是什么情况？需要详细说明下
