### ISSUE TITLE
请问该控件有没有通过参数配置在当前ajax返回结果成功前阻止其他ajax请求发送的参数设置

### ISSUE THREAD

**Issue by chengwengao** [ssy341/datatables-cn#226]
现在有个问题，当后台数据量大时，查询和表格渲染的时间比较慢，如果快速切换查询条件，多个ajax请求返回结果会混乱，比如我刚开始筛选温州市的数据，温州市的数据还未加载渲染完我立刻选择宁波市的数据，表格显示的最终条数确实是宁波市的数据条数，但是表格数据却是温州市和宁波市的数据，请问如何能控制当前ajax数据未加载完成组织另外的ajax请求发送，只有当当前ajax请求的数据渲染完成后，才开始请求新的？
![datatables ajax](https://user-images.githubusercontent.com/25266894/30468118-ee357572-9a1b-11e7-9dde-ffbe37a7920e.png)

**Comment by ssy341** [comment]
@chengwengao 这个应该是不会发生的，通过以下方式确定是显示错误而不是数据错误，在network里查看两次ajax请求，数据是否是你期望的那样，如果不是则可能是后台返回 数据的问题，如果返回的数据没有问题，再看看你的初始化代码，通过这两个方法确认问题
麻烦把返回的数据和初始化代码贴上来，以便更详细的分析

**Comment by chengwengao** [comment]
@ssy341 你好，按照你说的看了一下，network里的请求返回结果是对的，表格渲染的结果不对，所有代码和返回数据均已上传

![network](https://user-images.githubusercontent.com/25266894/30527325-dc1f3eaa-9c59-11e7-9283-9922bf7cbf7c.png)
[表格初始化代码.txt](https://github.com/ssy341/datatables-cn/files/1309562/default.txt)
![default](https://user-images.githubusercontent.com/25266894/30527326-dc250a4c-9c59-11e7-9a9c-2b637c061cf3.png)
[宁波市数据返回结果.txt](https://github.com/ssy341/datatables-cn/files/1309563/default.txt)
[温州市数据返回结果.txt](https://github.com/ssy341/datatables-cn/files/1309564/default.txt)
[浙江省数据返回结果.txt](https://github.com/ssy341/datatables-cn/files/1309565/default.txt)

**Comment by ssy341** [comment]
@chengwengao 少了draw参数，服务器模式必要的四个参数`draw`，`recordsTotal`,`recordsFiltered`,`data`

**Comment by chengwengao** [comment]
按照你的提示修改确实解决了这个问题。不过中间有点小曲折，在这里写出来以免其他人在使用draw参数的时候踩坑。异步加载表格时，如果每次都将表格destroy()掉再initTable()，这样会导致每次返回给前端的draw值都是1，达不到想要的效果，如果请求很频繁，数据会错乱，必须使用reload()函数才能加载正确的draw值，下面部分代码展示正确的代码：
```
#前端js初始化表格部分代码
serverSide : true,// 分页，取数据等等的都放到服务端去
deferRender : true,// 当处理大数据时，延迟渲染数据，有效提高Datatables处理能力
searching : false,// 是否开启搜索
draw:true,//请求序号,服务器模式必要的四个参数draw，recordsTotal,recordsFiltered,data，确保Ajax从服务器返回的是对应的（Ajax是异步的，因此返回的顺序是不确定的）

```
```
//java后台部分代码
//后台分页方法需要获取前端的draw属性
@RequestParam(required = false, value = "draw", defaultValue = "1") Integer draw,
@RequestParam(required = false, value = "start", defaultValue = "0") Integer start,
@RequestParam(required = false, value = "length", defaultValue = "10") Integer pageSize

Map<String, Object> map=new HashMap<String, Object>();
map.put("data", buildingList);
map.put("recordsFiltered", page.getTotalCount());
map.put("recordsTotal",page.getTotalCount());
//后台分页需要把draw返回给前端
map.put("draw",draw);
return map;
```
代码修改好后我们看看在浏览器的network调试一番：
![network draw](https://user-images.githubusercontent.com/25266894/30584699-1f1b500a-9d5d-11e7-9d26-486b24e68bcf.png)
此时发现draw属性已经正常返回，且每次访问一次，draw都有对应的值返回，这样ajax返回的结果就会始终与请求的参数想要获取的结果保持一致。
具体说明请看下面的官方文档解释：
![datatables 4](https://user-images.githubusercontent.com/25266894/30584996-09482b58-9d5e-11e7-98c5-61a3ebbeb67d.png)

在这里也附上之前错误的异步刷新表格代码：
![default](https://user-images.githubusercontent.com/25266894/30585217-b0864f1c-9d5e-11e7-83cb-0ba05d1929b4.png)

上图的reloadTable()是我自定义的表格刷新方法，可以参考官网的,官网地址：

部分代码如下：
```
#动态传参数
//初始化表格
var oTable = $("#example").DataTable({
    ajax: {
        url: "dataList.action",
        data: {
            args1: "我是固定传参的值，在服务器接收参数[args1]"
        }
    }
});
 
//当你需要多条件查询，你可以调用此方法，动态修改参数传给服务器
function reloadTable() {
    var name = $("#seName").val();
    var admin = $("#seAdmin").val();
    var param = {
        "obj.name": name,
        "obj.admin": admin
    };
    oTable.settings()[0].ajax.data = param;
    oTable.ajax.reload();
}

```
感谢作者的耐心解答！

**Comment by ssy341** [comment]
@chengwengao 能帮你解决问题就行了，同样也谢谢你这么认真的总结，文档要有不足之处还请指出，DataTables中文网有你更精彩
