### ISSUE TITLE
请问分页效果无法生效要如何处理

### ISSUE THREAD

**Issue by linzhangzhen** [ssy341/datatables-cn#228]
分页配置
 "lengthMenu": [5,10,20],    //代表你可以把表格设置为每页 5/10/20 条数据显示
 "paging": true,   //数据做分页显示设置，默认为true
 "info":     true,   //分页辅助信息，第几条到第几条，默认为true

服务器返回的数据
data:[{auth_id: "1", auth_name: "****", auth_a: "", auth_c: "", auth_route: null, auth_level: "0",…},…]
draw:"3"
recordsFiltered:"5"
recordsTotal:"7"

**Comment by ssy341** [comment]
@linzhangzhen 你使用了serverSide参数了么？麻烦你贴出完整的初始化代码

**Comment by ZhouMaoz** [comment]
问题解决了嘛？

**Comment by linzhangzhen** [comment]
已经解决了，是我对参数理解有误。

**Comment by ZhouMaoz** [comment]
var setDataTable = function (theadData,flag){
    //查询按钮点击事件
    console.log('...............................',filterData.sendFilterData)
    //  定制列
    var otable = $('.appList').DataTable({
      "columns": theadData,//直接把表头的数组放这里就可以渲染数据
      "processing" : true, //开启读取服务器数据时显示正在加载中……特别是大数据量的时候，开启此功能比较好
      "serverSide" : true,//服务器处理分页，默认是false，需要服务器处理，必须true
 
      "sAjaxSource" : "table-data.json",
      "fnServerData" : retrieveData,

      "destroy": true,//重新加载
      //禁用自动列宽度的计算
      "bAutoWidth": false,
      "bPaginate": true, //翻页功能
      "bStateSave" : true,
      "lengthChange": true,
      "sPaginationType" : "full_numbers", //详细分页组，可以支持直接跳转到某页
      "aaSorting" : [[0, "asc"]], //默认的排序方式，第1列，升序排列
      "iDisplayLength" : 10,// 指定一屏显示的数据条数，需要开启分页器，默认为10
      // "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "所有"]],
      // 支持多选
      select: false,
      // f 搜索框
      // l 显示页数
      // i 左下角页数信息
      // p 分页
      dom: '<"datatable-scroll-wrap"t><"datatable-footer"pl>',
      //  className 添加类名
      //  targets 当前列的下标
      //  searchable 搜索功能
      //  orderable 排序功
      columnDefs: [
        {
          targets: 0,
          orderable: false,
          searchable:false
        },
        {
          targets: 1,
          render: function(data){
            return data
          }
        },
        {
          targets: 2,
          render: function(data){
            return data
          }
        }
      ],
      language: {
        search: '_INPUT_',
        lengthMenu: '<span>显示:</span> _MENU_',
        // 左下角显示信息
        info: '_START_-_END_ of _TOTAL_',
        infoFiltered: '(从 _MAX_ 条数据中检索)',
        // 右下角分页
        paginate: {'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;'},
        // 搜索无内容时显示
        zeroRecords: '无搜索记录',
        sEmptyTable: '表中数据为空',
        // 无内容时左下角显示信息
        infoEmpty: '没有数据',
        sLoadingRecords : "载入中..."
      },
      "oAria" : {
        "sSortAscending" : ": 以升序排列此列",
        "sSortDescending" : ": 以降序排列此列"
      },
      // 移动列
      //colReorder: true
      // 绘制后回调函数
      drawCallback: function (settings) {

      },
      "fnFooterCallback": function(nFoot, aData, iStart, iEnd, aiDisplay) {
console.log(nFoot, aData, iStart, iEnd, aiDisplay)
      }

    });
    console.log('............................',otable)
    function retrieveData(sSource, aoData, fnCallback) {

      $.ajax({

        "type": "GET",

        "contentType": "application/json",

        "url": sSource,

        "dataType": "json",

        "data": JSON.stringify(aoData),

        "success": function(resp) {
          // $('.appList').dataTable().fnClearTable(); //清空表格
          // $('.appList').dataTable().fnAddData(packagingdatatabledata(data),true); //刷下表格
          fnCallback(resp); //服务器端返回的对象的returnObject部分是要求的格式
        },
        error: function (XMLHttpRequest, textStatus, errorThrown) {
          console.log("查询失败");
        }

      });
    }

    otable.on('xhr.dt', function (e, settings, json, xhr) {
      console.log("重新加载了数据")

      console.log(json);
    });

    $.fn.dataTable.ext.errMode = 'none';
 

  };

**Comment by ZhouMaoz** [comment]
我这样初始化之后发现，翻页点击，能获取到请求的数据，翻页页码没变，数据table不更新  您知道是什么原因吗？

**Comment by ssy341** [comment]
@linzhangzhen 问题解决了也不来说明一下，问题一直处于打开状态，既然提问，那就有始有终，不管有没有结果，而且还码解决了，不说要总结什么，起码自己把问题关了吧？
