### ISSUE TITLE
关于分页的页码跳转问题

### ISSUE THREAD

**Issue by jojolfy** [ssy341/datatables-cn#233]
看到官网的例子http://datatables.club/example/user_share/mir/ 中有页码跳转的功能，就是在paginate中配置jump字段就行，可是我配置以后没有，是为什么？高版本取消这个了吗？如果我要自己写的话，点击跳转后要执行什么功能呢？望各位指导，新手不胜感激！

**Comment by ssy341** [comment]
@jojolfy 你可以参考这个[例子](http://datatables.club/plug-ins/pagination/input/index.html)还有[这个](http://datatables.club/plug-ins/pagination/extjs/index.html)

**Comment by jojolfy** [comment]
@ssy341 谢谢回复，刚试了一下，结果它就把自带的分页替换掉了，我想保留自带分页的simple_numbers风格，然后再加上页面跳转，要怎么配置？麻烦指导，谢谢

**Comment by ssy341** [comment]
@jojolfy 自己实现一个分页插件
