### ISSUE TITLE
请问怎么获得当前分页的数据呢？

### ISSUE THREAD

**Issue by Waterdroppp** [ssy341/datatables-cn#236]
有很多分页，有什么方法可以获得当前分页的数据而不是全部数据吗？

**Comment by ssy341** [comment]
@Waterdroppp 如果是服务器分页 table.data()即为当前分页的数据 如果是客户端处理，table.data()获取的是所有的数据

**Comment by Waterdroppp** [comment]
谢谢，我想要的是当前页面columns的数据，已通过table.columns({page:'current'}).data()解决
