### ISSUE TITLE
单元个内容超过单元格宽度显示点点的时候,如何设置鼠标移上显示完整信息

### ISSUE THREAD

**Issue by hbliyafei** [ssy341/datatables-cn#239]
单元格里面的内容超过单元格的宽度,  只显示了前面一部分,后面使用点点显示, 如何设置, 在鼠标移动到该单元格的时候显示出完整的信息.(就是那个 html 标签的 title 属性).

**Comment by ssy341** [comment]
@hbliyafei http://datatables.club/manual/daily/2016/04/28/option-columns-render4.html
