### ISSUE TITLE
页面上下页错位

### ISSUE THREAD

**Issue by hekui1994** [ssy341/datatables-cn#244]

**Comment by hekui1994** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>管理员后台 广告联盟</title>
		<link rel="stylesheet" href="../../business/style.css" media="all" type="text/css">
			<link rel="stylesheet" href="../../business/modal.css" media="all" type="text/css">
				<script type="text/javascript" src="../../business/jquery-1.7.min.js"></script>
				<script type="text/javascript" src="../../business/jquery.validate.js"></script>
				<script type="text/javascript" src="../../business/jquery.cookie.js"></script>
				<script type="text/javascript" src="../../business/function.js"></script>

	<script type="text/javascript" src="../../plugins/datatables/jquery.dataTables.js"></script>
	<script type="text/javascript" src="../../plugins/datatables/dataTables.bootstrap.min.js"></script>
	<script type="text/javascript" src="../../js/control.js"></script>
	<script type="text/javascript" src="../../js/string.js"></script>
 <script type="text/javascript">
 
    var table;
    base_url = get_baseurl();
    
    $(document).ready(function() {
        table = $('#dt_inbox').DataTable({
            language: {
                search:         "搜索&nbsp;:",
                lengthMenu:     "_MENU_",
                emptyTable: "还是资料不存在",
                zeroRecords: "还是资料不存在",
                paginate: {
                    first:      "第一页",
                    previous:   "上一页",
                    next:       "下一页",
                    last:       "最后一页"
                },                    
            },
            "serverSide": true,
            "processing": true,
            "stateSave": true,
            "paging": true,
            "ordering":false,
            "info": false,
            "bFilter": false,
            "lengthChange": true,
            "searching": false,
            "autoWidth": false,
            "ajax": {
                "url": 	base_url + "/plans/list",
                "type":	"POST",
                "data": function (param ) {
                  param.pId = $("#pId").val();
                    param.pageIndex = param.start / param.length + 1;
                    param.pageSize = param.length;
                },
                "dataType": "json", 
            },
            "drawCallback": function(settings) {
              /*   if ($('#progress_tip').prop('visibility') != 'hidden')
                    $('#progress_tip').css('visibility','hidden'); */
            },
            "columnDefs": [
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 0,
                    "render": function(data, row, meta) {
                        if (data.isdelete) {
                            return data.isdelete;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 1,
                    "render": function(data, row, meta) {
                        if (data.createtime) {
                            return data.createtime;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 2,
                    "render": function(data, row, meta) {
                        if (data.name) {
                            return data.name;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 3,
                    "render": function(data, row, meta) {
                        if (data.type) {
                            return data.type;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 4,
                    "render": function(data, row, meta) {
                        if (data.pageview) {
                            return data.pageview;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 5,
                    "render": function(data, row, meta) {
                        if (data.hits) {
                            return data.hits;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 6,
                    "render": function(data, row, meta) {
                        if (data.hitsagain) {
                            return data.hitsagain;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 7,
                    "render": function(data, row, meta) {
                        if (data.effectamount) {
                            return data.effectamount;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 8,
                    "render": function(data, row, meta) {
                        if (data.bucklequantity) {
                            return data.bucklequantity;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 9,
                    "render": function(data, row, meta) {
                        if (data.balanceamount) {
                            return data.balanceamount;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 10,
                    "render": function(data, row, meta) {
                        if (data.crt) {
                            return data.crt;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 11,
                    "render": function(data, row, meta) {
                        if (data.payable) {
                            return data.payable;
                        } else {
                            return "";
                        }
                    }
                },
                {
                    "data": null,  
                    "searchable": false,
                    "orderable": false,
                    "targets": 12,
                    "render": function(data, row, meta) {
                        if (data.profit) {
                            return data.profit;
                        } else {
                            return "";
                        }
                    }
                }
            ]
        } );
        
    } );
	
</script>
</head>

<body>
	
	<div class="row-fluid">
		<h3 class="heading">
			效果报表 <span class="h3span"> <a href="http://union.mzwl.cc/manage/index.php?e=admin/stats.down_execl&amp;action=plan_list&amp;searchtype=&amp;searchval=&amp;plantype=&amp;sortingtype=&amp;timerange=2017-10-12_2017-10-12" style="width: 110px; text-align: left; padding-left: 10px"><i class="n_excel"></i> 导出Excel</a></span>
		</h3>
		<div class="tab users">
			<div class="tab-header-right left">
				<a href="planning-data.html" class="tab-btn  planstats tab-state-active">计划报表</a> <a href="stationmaster.html" class="tab-btn userstats "> 站长报表</a> <a href="advertise.html" class="tab-btn adsstats "> 广告报表</a> <a href="advertising-space.html" class="tab-btn zonestats "> 广告位报表</a> <a href="http://union.mzwl.cc/manage/index.php?e=admin/ip.get_list" class="tab-btn ip "> IP报表</a>
			</div>
		</div>
		<div class="dataTables_wrapper ">
			<div class="tb_sts" style="margin-bottom: 10px;">
				<div class="span6">
					<div class="dataTables_filter" id="dt_outbox_filter">
						<form method="post" action="http://union.mzwl.cc/manage/index.php?e=admin/stats.plan_list">
							搜索：
							<input type="text" class="input_text " name="searchval" value="" style="width: 80px"> <select name="searchtype">
									<option value="planid">计划ID</option>
									<option value="uid">站长ID</option>
									<option value="recommend">查询下线</option>
									<option value="adsid">广告ID</option>
									<option value="zoneid">广告位ID</option>
							</select> <select name="sortingtype" class="select" id="select2">
									<option value="">默认排序</option>
									<option value="day">日期</option>
									<option value="views">浏览量</option>
									<option value="num">结算数</option>
									<option value="deduction">扣量</option>
									<option value="clicks">二次点击</option>
									<option value="effectnum">效果数</option>
									<option value="sumpay">应付金额</option>
									<option value="sumprofit">盈利</option>
							</select> <select name="plantype" class="plantype" id="plantype">
									<option value="">所有类型</option>
									<option value="cpc">Cpc类型</option>
									<option value="cpm">Cpm类型</option>
									<option value="cpv">Cpv类型</option>
									<option value="cps">Cps类型</option>
									<option value="cpa">Cpa类型</option>
							</select> <select name="timerange" id="timerange" style="width: 200px;">
									<option value="2017-10-12_2017-10-12">
                2017-10-12 至 2017-10-12                </option>
									<option value="">所有时间段</option>
									<option value="2017-10-12_2017-10-12" selected="">今天</option>
									<option value="2017-10-11_2017-10-11">昨天</option>
									<option value="2017-10-06_2017-10-12">最近7天</option>
									<option value="2017-9-13_2017-10-12">最近30天</option>
									<option value="2017-9-1_2017-9-30">上个月</option>
							</select> <img src="" align="absmiddle" onclick="__C(&#39;timerange&#39;,2,&#39;r&#39;)" style="margin-bottom: 3px;"> <input name="_s" type="image" src="../../business/sb.jpg" align="top" border="0" style="margin-left: 20px;">
						</form>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="span6">
					<div id="dt_outbox_length" class="dataTables_length">
						批量操作： <select size="1" name="choose_type" id="choose_type">
							<option value="">请选择</option>
							<option value="del">删除</option>
						</select>
						<button class="rowbnt" type="submit" id="choose_sb">提交</button>
					</div>
				</div>
			</div>
			<table id="dt_inbox"  name="dt_inbox" class="dataTable">
				<thead>
					<tr role="row" class="row_w">
						<th><input type="checkbox" name="isdelete" id="isdelete"></th>
						<th>日期</th>
						<th>计划名称</th>
						<th>类型</th>
						<th>浏览数</th>
						<th>点击数</th>
						<th>二次点击</th>
						<th>效果数</th>
						<th>扣量</th>
						<th>结算数</th>
						<th>CRT</th>
						<th>应付</th>
						<th>盈利</th>
					</tr>

					<tr role="row">
						<th>汇总</th>
						<th>&nbsp;</th>
						<th>&nbsp;</th>
						<th>&nbsp;</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th>0%</th>
						<th>￥0</th>
						<th><span class="status">￥0</span></th>
					</tr>

				</thead>
				<tbody role="alert" aria-live="polite" aria-relevant="all">
				</tbody>
			</table>
			<div class="row"></div>
		</div>
	</div>
	

	<div class="popover right">
		<b>◆</b> <span>◆</span>
		<div class="popover-title">
			<div style="float: left">操作</div>
		</div>
		<div class="popover-content"></div>
	</div>
	<div style="height: 60px"></div>
	<div id="add_user_form" style="display: none">
		<form action="http://union.mzwl.cc/manage/index.php?e=admin/user.add_post" id="form_v" method="post">
			<div class="txt-fld">
				<label for="" class="tit">用户角色</label> <input type="radio" name="type" value="1" checked="checked"> 网站主 <input type="radio" name="type" value="2"> 广告商 <input type="radio" name="type" value="3"> 联盟客服 <input type="radio" name="type" value="4"> 联盟商务 
			</div>
			<div class="txt-fld">
				<label for="" class="tit">用户名</label> <input id="username_ajax" name="username" type="text">
			</div>
			<div class="txt-fld">
				<label for="" class="tit">用户密码</label> <input id="" name="password" type="text">
			</div>



			<div class="txt-fld">
				<label for="" class="tit">联系人</label> <input id="" name="contact" type="text">
			</div>
			<div class="txt-fld">
				<label for="" class="tit">QQ</label> <input id="" name="qq" type="text">
			</div>
			<div class="btn-fld">
				<button type="submit">提交 »</button>
			</div>
		</form>
	</div>
	
</body>
</html>

**Comment by ssy341** [comment]
@hekui1994 重新把代码整理下，参考我的格式 这个我都不好再次编辑  
```javascrip
//这里面放js代码
```

```html
<!-这里面放html代码-->
```
![image](https://user-images.githubusercontent.com/1725705/31807572-85ff04c2-b5a1-11e7-8325-2c74e6b35616.png)
