### ISSUE TITLE
定时刷新表格或表格的某一列

### ISSUE THREAD

**Issue by jinleli** [ssy341/datatables-cn#253]
表格中有两列数据是随时变动的，现在通过
`        setInterval(function(){
            oTable.ajax.reload(null,false);
        },3000)`
来定时刷新，但是这样有个问题如果请求返回比较慢的时候，第一次请求应该返回1，第二次返回2，表格还没重绘好，后请求的先得到，先请求的后到，那么会不会本来表格展示为2，结果展示为1，所以想问问大家是怎么做的定时刷新表格数据

**Comment by ssy341** [comment]
@jinleli 你返回数据肯定有问题，datatables在请求上加了draw来区分每次请求，两次请求不可能会混，请贴上代码和返回的数据
