### ISSUE TITLE
When I configured php-cs-fixer, the following error occurred. 

### ISSUE THREAD

**Issue by ltqTest** [ssy341/datatables-cn#254]
The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option in section "Executables" (near the top) in subsection "PHP-CS-Fixer" labelled "Path" in Atom-Beautify package settings.
  How to solve?

**Comment by ssy341** [comment]
@ltqTest I am sorry I can‘t help you. I think your issue is not about jQuery DataTables plugin.
