### ISSUE TITLE
使用language.thousands 千分位分隔符为什么没有效果？

### ISSUE THREAD

**Issue by olivivian** [ssy341/datatables-cn#257]
我想让datatables表格里的数据千分位以逗号隔开要怎么做？如1234567==>123,456,7。

**Comment by ssy341** [comment]
@olivivian 这个里有点误解，我一开始和你一样的想，但实际他是告诉dt，123,456,7这样的数字是按照千分位分隔的 不是字符串而是数字，而不是说。我想把数字 1234567==>123,456,7。
参考
http://datatables.club/reference/option/language.decimal.html
http://datatables.club/reference/option/language.thousands.html
如果要达到你说的效果，你需要使用[formatNumber](http://datatables.club/manual/daily/2016/05/03/option-formatNumber.html)
