### ISSUE TITLE
scrollX 横向滚动条 问题

### ISSUE THREAD

**Issue by documentgetElementIdDaydreamer** [ssy341/datatables-cn#258]
因为设置了表格宽度100%，当我在大屏幕看，宽度足够的时候，是没有滚动条，
但是因为左侧边有宽度可变的导航栏，在导航宽度增加的时候，表格宽度改变，宽度变小。
表头部分没有宽度100%，表格部分宽度100%。导致表头宽度不变，表格宽度减小。
表头与表格错位。
我又不能用div超出出现滚动条，因为表格下有添加组件。

请问有什么解决的办法，可以让表头和表格的宽度一致而且不错位么。

**Comment by skjanyou** [comment]
我用的是
`$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();`
来重新计算所有datatables表格的宽度,你可以在导航栏的回调里面触发这个函数,但是我觉得这是治标不治本的方法，现在正在研究有没有更好的方法。

**Comment by Camelliaguoqian** [comment]
我也遇到这个问题，是在弹出框关闭后，页面中点击下一页，下一页中的表格td就和表头th错位了
