### ISSUE TITLE
求求你们给个解答吧，jsonp问题

### ISSUE THREAD

**Issue by wgkflyit** [ssy341/datatables-cn#261]
跨域访问时分页数据如何传输，例如当前页，每页显示的数据量 ，还有search里面的信息，这些信息如何通过jsonp的方式传递到服务器？

**Comment by guoqiang998** [comment]
你说的问题是服务端提供数据的问题，跟datatables没有关系，也就是说datatables该怎么用还怎么用，唯一不同的是你用的是jsonp跨域请求数据。
