### ISSUE TITLE
datatable 如何实现某一列数据过长,只显示部分数据

### ISSUE THREAD

**Issue by 15662105908** [ssy341/datatables-cn#262]
datatable 如何实现某一列数据过长,只显示部分数据

**Comment by ssy341** [comment]
@15662105908 参考http://datatables.club/manual/daily/2016/04/25/option-columns-render1.html

**Comment by cgoooook** [comment]
这是解决了吗？datatable 如何实现某一列数据过长,只显示部分数据，不是这个吗
