### ISSUE TITLE
新手求教，ajax在一个页面调用另一个datatables的页面

### ISSUE THREAD

**Issue by lsc476200** [ssy341/datatables-cn#268]
ajax在一个页面调用另一个datatables的页面，在点击显示该页面的链接中，databales的页面的css和js有时加载成功，有时又没有
![default](https://user-images.githubusercontent.com/26186276/32952126-38dd1bdc-cbe7-11e7-8477-9834b51923c7.png)
![default](https://user-images.githubusercontent.com/26186276/32952159-538cdaa8-cbe7-11e7-8c14-740bb6cbbf19.png)
![default](https://user-images.githubusercontent.com/26186276/32952190-6b30e640-cbe7-11e7-9947-4517f0c37224.png)
![default](https://user-images.githubusercontent.com/26186276/32952218-840eb3f4-cbe7-11e7-8842-69a21ecca8ee.png)
![default](https://user-images.githubusercontent.com/26186276/32952230-8e4d4038-cbe7-11e7-8f2c-961e9848d61d.png)
![default](https://user-images.githubusercontent.com/26186276/32952552-9a5a47b2-cbe8-11e7-8ed5-241164e353ac.png)

**Comment by yhhzhengyi** [comment]
这些东西看不出什么，我只能猜测了：
问题的原因应该不在于datatables插件，而是在于没有找到dom对象。建议在调用插件之前先测试下有没有找到表格对象。
let $table = $('#example')
调试看下$table的值
