### ISSUE TITLE
bootstrap的modal里有个datatable，显示modal时datatable表头缩在一起

### ISSUE THREAD

**Issue by jackleexp** [ssy341/datatables-cn#269]
bootstrap的modal里有个datatable，显示modal时datatable表头缩在一起。使用tab去除表头缩在一起的方法。
<code>
            $('#modal').on('show.bs.modal', function () {
                table.columns.adjust().draw();
            })
            $('#modal').on('shown.bs.modal', function () {
                table.columns.adjust().draw();
            })
</code>
还是不行，modal显示的时候还是会看到缩在一起的情况，虽然马上又展开了

**Comment by ssy341** [comment]
@jackleexp 参考 #9
