### ISSUE TITLE
请问在显示数据之前将数据库里的数据先筛选一遍，功能该怎么写

### ISSUE THREAD

**Issue by heather9829** [ssy341/datatables-cn#27]
有数据库名position
数据表
id   name   position      year
1     nick       staff             1
2     nick       superviser 1
3     mary     staff              2
从表中可以看出，有的人（mary）仅有一条记录,有的人（nick）有多条记录,现在我想用一条select记录把表中所有的人记录选择出来，如果像nick这样有多条记录的，就选id大的那条记录,就是说同一人仅选择出一条记录。
以上面数据表为例选择结果是
2     nick       superviser 1
3     mary     staff              2
请问应该怎么写
是在server_side里的ssp.class.php里面改吗
还是改javascript?
ssp.class.php那个文件我实在不会改

**Comment by ssy341** [comment]
这是数据库额事情，
```sql
select max(id),name,position,year from position group by name
```

**Comment by heather9829** [comment]
server_processing.php:
$columns = array(
 
	**_array( 'db' => 'max(id)', 'dt' => 'ID'),_**
	
	);

// SQL server connection information
$sql_details = array(
	'user' => 'root',
	'pass' => '',
	'db'   => 'sdms',
	'host' => 'localhost'
);


require( 'ssp.class.php' );

echo json_encode(
	SSP::simple( $_GET, $sql_details, $table, $primaryKey, $columns )
);
ssp.class.php:	
static function simple ( $request, $sql_details, $table, $primaryKey, $columns,$default = false )
	{
		$bindings = array();
		$db = self::sql_connect( $sql_details );
		// Build the SQL query string from the request
		$limit = self::limit( $request, $columns );
		$order = self::order( $request, $columns );
		$where = self::filter( $request, $columns, $bindings,$default );
		// Main query to actually get the data
		$data = self::sql_exec( $db, $bindings,
			"SELECT SQL_CALC_FOUND_ROWS `".implode("`, `", self::pluck($columns, 'db'))."`
			 FROM `$table`
			 $where
			 $order
			 $limit **_group by Staff_name_**"
		);
是这样改的吗

**Comment by ssy341** [comment]
@heather9829 php我不熟悉，没有环境，我不清楚，建议自己运行调试
