### ISSUE TITLE
table高度充满div，高度如何自适应？

### ISSUE THREAD

**Issue by liwei511** [ssy341/datatables-cn#272]
![20171124172201](https://user-images.githubusercontent.com/18389869/33203749-16a5a7a0-d13c-11e7-9101-94f869488740.jpg)
datatables和flex布局结合，如何实现如图布局？
我知道可以设置scrollY: '270px',或者scrollY: '70vh',。但这都满足不了table充满div的需求。

**Comment by liwei511** [comment]
scrollY不支持 %，怎么解决？

**Comment by gaiyabing** [comment]
我的做法是用setting.dom给表格头部、底部、主体分别添加class名，然后手动添加css样式，高度用calc
