### ISSUE TITLE
设置datatable的提示信息

### ISSUE THREAD

**Issue by skjanyou** [ssy341/datatables-cn#274]
datatable初始化参数language中有一个参数emptyTable可以设定数据为空的时候的提示信息，但是需求要求在没有开始查询导致的数据为空的情况不能使用那个提示信息.例如:打开页面进去,默认datatable初始化时不查询数据,所以提示信息应该为"请点击查询",然后进行了查询操作后,若还是没有数据,应当显示"无记录"。
所以想问一下有没有大神知道实现这个需求的datatable的原生方案。在这里先谢谢大家了。

**Comment by zzhp** [comment]
如果是是使用ajax获取数据，是不是可以在进行ajax请求之前将emptyTable中的提示内容改为“请点击查询”，ajax获取数据之后再改回来呢。。。。emmmmmmm个人思路

**Comment by ssy341** [comment]
@skjanyou 邮件也回复你了，应该是你发的，提的是相同的问题，没有原生的解决方案，要实现也不是没有办法，@zzhp 说的方法也是可行的，通过加载初始化数据然后使用rowcreated回调方法把信息弄成一行的样子
或者，两个表格，没有点击查询之前是一个表格，点击查询之后 初始化新的表格，加载数据

建议换个角度去思考这个问题，而不是需求是那样就一定要做成那样

**Comment by skjanyou** [comment]
@zzhp @ssy341 好的，多谢两位
