### ISSUE TITLE
请指教  datatable  列表分页问题

### ISSUE THREAD

**Issue by qingyuun** [ssy341/datatables-cn#276]
按datatable中文网示例 写的一个ajax请求列表分页数据展示没有问题，从第一页一直向后点击加载数据没有任何问题，但是想返回查看上一页数据或者调整一下每页展示多少条数据后ajax请求发送成功数据返回，但这时问题出来了，返回数据不加载，展示的还是请求之前的数据；
datatable初始化一些设置如下：
![image](https://user-images.githubusercontent.com/20103991/33476582-6ffcafc0-d6bd-11e7-8be3-98ce8e7a1d1d.png)
datatable 初始化+数据请求
![image](https://user-images.githubusercontent.com/20103991/33476956-d3c048cc-d6be-11e7-9541-502f8fee0bfc.png)
1、数据修改显示条数改动后不起作用，ajax请求发出后返回数据后不展示，分页同样会受到影响后不展示
2、分页正常向后展示可以使用，如想再次查看前一页ajax请求发出返回数据后不展示，分页收到影响向后查看也展示数据
是什么原因造成，请指教

**Comment by ssy341** [comment]
@zheng18633149754 ajax 改写的  参考这个例子http://datatables.club/example/user_share/mir/
贴出返回的数据会帮助分析问题，只看代码 不太清楚
