### ISSUE TITLE
一个相同值，按照不同多列排序的问题

### ISSUE THREAD

**Issue by 49839013** [ssy341/datatables-cn#278]
比如有A列，B列,C列，D列
首先按照A列内容排序，有1,2,3,4组（多行）
然后相同数字的行，比如A列等于1的行全部按照B列排序，A等于2的行，全部按照C列排序
如何做这个？

A           B             C          D 
1           0.5
1            1
2            0
3            0           0.5         
3                         0.6
4                                    0.1
...........................................................

**Comment by 49839013** [comment]
![default](https://user-images.githubusercontent.com/24695465/33534963-b0253688-d8e5-11e7-88ef-b2bfb50cadd5.png)


看一下图片，上面一个提问重复了，格式有问题

**Comment by ssy341** [comment]
@49839013 你这个是多列排序 http://datatables.club/reference/option/orderMulti.html
