### ISSUE TITLE
如何实现每页固定10行数据，不足10行用空行代替

### ISSUE THREAD

**Issue by creek1990** [ssy341/datatables-cn#279]
求大神指导。。。

**Comment by kingfive555** [comment]
datatable初始化的时候把 这个参数写成这样pageLength: 10,就能保证每页10行，不足的用空行代替，你可以向你的数据里面加入空数据，凑成10的整数倍就可以了

**Comment by ssy341** [comment]
@creek1990
http://datatables.club/manual/daily/2016/05/05/option-scrollCollapse.html
