### ISSUE TITLE
table项排序的问题

### ISSUE THREAD

**Issue by flychao4837** [ssy341/datatables-cn#28]
表格排序是按字母顺序排序的，遇到用百分比显示的就会出错 100% 会比90%小
这种情况下能否提供用户自定义排序的功能

**Comment by ssy341** [comment]
自定义排序方法即可，参考[https://datatables.net/plug-ins/sorting/](https://datatables.net/plug-ins/sorting/)

**Comment by flychao4837** [comment]
多谢
