### ISSUE TITLE
手动调整Datatable宽度

### ISSUE THREAD

**Issue by skjanyou** [ssy341/datatables-cn#280]
在手动调整Datatable表格的宽度时
无论是使用:
`$("#display-table").DataTable().columns.adjust()`
或是使用:
`$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust()`
都会对表格列的宽度进行重新调整.但是问题在于多次触发这两个函数的时候,列的宽度不会固定下来，会一直调整,而且是越靠近两侧的列获得的宽度越大,这样一来原本正常的表格就变得很怪异了，请求大神解答一下，这个问题有没有好的解决方法。

**Comment by swallow-liu** [comment]
我 最近也是想更改dataTable里面的table的 宽度，我发现他的宽度都是 计算出来的 并且 是写在style里面的。我想去掉 这些style样式不知道该怎么弄
