### ISSUE TITLE
Page Question

### ISSUE THREAD

**Issue by Johnsonheng** [ssy341/datatables-cn#283]
I Have a Question.Now Look
![image](https://user-images.githubusercontent.com/21253371/33752948-b577723a-dc1f-11e7-924e-2ca061317b19.png)
why Page Style about this change?
My Code`"oLanguage": {
                        "sProcessing": "<img src='/images/datatable_loading.gif'>  努力加载数据中.",
                        "sLengthMenu": "每页显示 _MENU_ 条记录",
                        "sZeroRecords": "抱歉， 没有找到",
                        "sInfo": "从 _START_ 到 _END_ /共 _TOTAL_ 条数据",
                        "sInfoEmpty": "没有数据",
                        "sInfoFiltered": "(从 _MAX_ 条数据中检索)",
                        "sZeroRecords": "没有检索到数据",
                        "sSearch": "模糊查询:  ",
                        "oPaginate": {
                            "sFirst": "首页",
                            "sPrevious": "前一页",
                            "sNext": "后一页",
                            "sLast": "尾页"
                        }
                    }`
Datatables versions is 1.10.15

**Comment by Johnsonheng** [comment]
![image](https://user-images.githubusercontent.com/21253371/33753143-c65425c0-dc20-11e7-841f-7fb526ed6082.png)

**Comment by ssy341** [comment]
@Johnsonheng 纯css样式问题，分为两行显示了
