### ISSUE TITLE
请教关于datatables自定义搜索的问题

### ISSUE THREAD

**Issue by cxc282752012** [ssy341/datatables-cn#285]
我创建了一个弹窗使用datatable加载数据，还加了一个自定义搜索，搜索的内容是表格内的一个字段，为什么当我点击搜索按钮的时候，弹窗就消失了，而且url地址显示请求了后台，页面也刷新了。不使用弹窗就没有这个问题，搜索跟自带的搜索效果是一样的？请问这是什么问题？

**Comment by ssy341** [comment]
@cxc282752012 贴出关键代码，方便分析
