### ISSUE TITLE
reload 後 table 清空

### ISSUE THREAD

**Issue by emily800326** [ssy341/datatables-cn#287]
var  select= $("#xxx").DataTable(.... );
使用 select.ajax.url(baseurl).load();
reload data後 點擊tr觸發select事件 還是一直存取之前的select tr的資料
$("#xxx").dataTable().fnClearTable(); 也無法清乾淨

**Comment by occultskyrong** [comment]
1、注意 `.dataTable()` 和 `.DataTable()` 的区别。
2、请详细描述遇到的问题，提供以下信息：

    
#### 1. 使用DataTables的源（CDN地址、本地源文件）

#### 2. DataTables的版本

#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图

#### 6. 其他你认为可以帮助解决问题的信息
