### ISSUE TITLE
dt 1.10.8 不显示"加载中.."信息

### ISSUE THREAD

**Issue by skjanyou** [ssy341/datatables-cn#289]
查看文档得知datatable可以通过"loadingRecords"或者"processing"这两个属性给dt添加"加载中"信息,但是实际使用中发现并没有

**Comment by ssy341** [comment]
@skjanyou  f12 审查元素 看是不是其他样式影响到这个div的显示

http://datatables.club/reference/option/processing.html
http://datatables.club/reference/option/language.processing.html
