### ISSUE TITLE
发现一个bug无法解决（oLanguage.sInfoThousands 老版本参数 | language.thousands 新版本参数）

### ISSUE THREAD

**Issue by 1076572358** [ssy341/datatables-cn#292]
技术介绍：datatables版本：DataTables 1.10.12 ，bootstrap
 问题表现：由于项目大规模使用datatables 所以使用	
```javascript
$.extend( $.fn.dataTable.defaults, {
 "oLanguage" : {//国际语言转化
						"oAria" : {
							"sSortAscending" : " - click/return to sort ascending",
							"sSortDescending" : " - click/return to sort descending"
						},
						"sProcessing" : "处理中...",
						"sLengthMenu" : "显示 _MENU_ 项结果",
						"sZeroRecords" : "没有匹配结果",
						"sInfo" : "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
						"sInfoEmpty" : "显示第 0 至 0 项结果，共 0 项",
						"sInfoFiltered" : "(由 _MAX_ 项结果过滤)",
						"sInfoPostFix" : "",
						"sUrl" : "",
						"sEmptyTable" : "表中数据为空",
						"sLoadingRecords" : "",
						"sProcessing": "",    
						"sInfoThousands" : ",",
						"oPaginate" : {
							"sFirst" : "首页",
							"sPrevious" : " 上一页 ",
							"sNext" : " 下一页 ",
							"sLast" : " 尾页 "
						}
					},
                                        "processing" : true, //打开数据加载时的等待效果
					"bSort" : false, //是否支持排序功能
					"searching" : false,//屏蔽datatales的查询框
					"bLengthChange" : false,//屏蔽tables的一页展示多少条记录的下拉列表
					"autoWidth" : false,//自动宽度
					"scrollCollapse" : true,
					"bScrollCollapse" : true,
})
```
来减少代码量  其中"sInfoThousands" : ",",这个属性在字类没用 子类页面显示为：显示第 1 至 100 项结果，共 2undefined736 项  中间这个逗号为undefined ，
我尝试在子类代码加上"sInfoThousands" : ",",问题得以解决，希望能解决看下这个问题。

**Comment by 1076572358** [comment]
这个问题场景在
 数据为千分位 
使用$.extend 优化代码sInfoThousands" : ",",没用，
子页面显示为显示第 1 至 100 项结果，共 2undefined736 项

**Comment by ssy341** [comment]
@1076572358 这个不是bug，我查询了 sInfoThousands 是老板的写法，作者做了识别替换，也就是说你的父类的参数他是没有做替换操作，但是在你的子类做了替换操作，所以你把父类的参数名改为thousands 即可

> oLanguage.sInfoThousands  老版本参数 | language.thousands  新版本参数

建议你的参数都改为新版的，避免其他问题

**Comment by 1076572358** [comment]
首先谢谢您的解答：官网文档中说明了 Datatables 1.10.x在命名上与1.9.x的有区别，新版的使用的是驼峰的命名规则，而之前的是采用匈牙利命名规则 。
而这里我的版本是1.10也就是旧版本，且这里存在的问题是 我把公共代码抽出来  只有sInfoThousands这个无效 其他参数在父类定义后在子类都有效 所以我只能确定这是bug 这个参数的bug 不然无法解释为什么其他参数都有效 只有这个参数无效 。

**Comment by ssy341** [comment]
@1076572358 1.10是新版本。1.9.x 才是旧版本，更换之后是否解决了问题呢？
