### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by SmallNanGua** [ssy341/datatables-cn#293]
The first column of dataTables is set to not sort, but the first one always shows the sorting icon, and it will disappear when clicked once.
I want to no sort of the first column and no show the sorting icon first-time.
What can i do?
Please help me,thank you!

**Comment by ssy341** [comment]
@SmallNanGua 
I am not sure this is a bug or not, but you just need add below code to solve your problem
```javascript
 "order": [[ 1, 'asc' ]] //set the second Column sort by asc 
```
because the plugin set the first Column as sort column by default
