### ISSUE TITLE
新手初学dom定位,项目为thymeleaf模板，在学习文档dom定位的例子报错

### ISSUE THREAD

**Issue by zhangLuuuulu** [ssy341/datatables-cn#294]
$(document).ready(function() {
    $('#example').dataTable( {
        "dom": '<"top"i>rt<"bottom"flp><"clear">//该语句报错：元素内容必须由 格式正确字符数据或标记组成，
    } );
} );
照文档的写法，小白求指教，只求能先入门

**Comment by ssy341** [comment]
@zhangLuuuulu 
```javascript
"dom": '<"top"i>rt<"bottom"flp><"clear">'
```
和thymeleaf模板没有关系，看你贴的代码少了一个右单引号
http://datatables.club/example/basic_init/dom.html
