### ISSUE TITLE
datatable发送ajax在返回数据如何回调，文档里说，ajax:{} 要么ajax:function()，怎么办

### ISSUE THREAD

**Issue by zdx999** [ssy341/datatables-cn#299]
ajax: {
            url: pageUrl,
            type: "POST",
            data: function (d) { // 动态的更新提交的参数
                d.advertiserId = $advertiserId.val();
                d.creativeType = $creativeTypesId.val();
                return $.extend( {}, d, {
                    "search[type]": $('#searchTypeSelectId').val()
                } );
            },
        },
        
        "ajax": function (data, callback, settings) {
             
            callback(
                alert()
            );
        },

**Comment by ssy341** [comment]
@zdx999 
```javascript
ajax: {
        url: pageUrl,
        type: "POST",
        dataSrc: function () {
        }
    },
```
更详细的参考这里http://datatables.club/reference/option/ajax.dataSrc.html

**Comment by zdx999** [comment]
@ssy341 dataSrc有问题。我后端返回了一个json
   renderJson(new DataTablesPage(dataParam, null,
                        null,list , "按ID你还不输数字！"));
                return;
。我并没有处理它，然后浏览器会弹出DataTables warning: table id=table - 按ID你还不输数字！。然后才会debugger进入datasrc方法。

**Comment by ssy341** [comment]
@zdx999 表格只接受数据 显示数据，没有数据就显示为空 有数据就直接显示数据，这些东西你应该在不破坏他本身的结构上附加上这些信息，到dataSrc里去处理
