### ISSUE TITLE
列顺序拖拽和列宽度拖拽，请问有例子嘛？活着主要参数有啥，

### ISSUE THREAD

**Issue by niuchunling** [ssy341/datatables-cn#3]
关于列顺序拖拽，看了又扩展，但是列的宽度拖拽，完全没有头绪，求帮助

**Comment by ssy341** [comment]
@niuchunling 
首先，很高兴在这里回答问题，你是第一个在这里提问的小伙伴，我给你点赞，希望你在学习DT的路上顺顺利利。
其次，对于你的问题，你可以参考这个例子 [ui（绿色风格） 网友共享 示例 Datatables中文网](http://datatables.club/example/user_share/yuui.html)

关于列宽的拖动，我暂时也只有这个例子，还没有发现官方提供插件，如果你有新的发现，欢迎继续跟帖回答。

最后，谢谢你的支持！
