### ISSUE TITLE
为什么start参数和length一样的？

### ISSUE THREAD

**Issue by iter520** [ssy341/datatables-cn#30]
![360 20161009153105609](https://cloud.githubusercontent.com/assets/14831163/19218791/7ef459b4-8e35-11e6-9f0e-44c6ec30ccfe.jpg)

![Uploading 360截图20161009153219031.jpg…]()

**Comment by ssy341** [comment]
@iter520   意思是，从第5条数据开始，每页条数为5，如果我没猜错，你这是第二页
