### ISSUE TITLE
fnClearTable报错

### ISSUE THREAD

**Issue by Asiasouth** [ssy341/datatables-cn#301]

**Comment by occultskyrong** [comment]
请提供以下信息，包括但不限于：

    
#### 1. 使用DataTables的源（CDN地址、本地源文件）

#### 2. DataTables的版本

#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图

#### 6. 其他你认为可以帮助解决问题的信息
