### ISSUE TITLE
如何重新排序列？

### ISSUE THREAD

**Issue by 595415454** [ssy341/datatables-cn#302]

**Comment by occultskyrong** [comment]
如果是动态显示列问题，请参照  #4 

如果我理解错了，请补充以下信息：

    
#### 1. 使用DataTables的源（CDN地址、本地源文件）

#### 2. DataTables的版本

#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图

#### 6. 其他你认为可以帮助解决问题的信息

**Comment by ssy341** [comment]
@595415454 拖拽列顺序，通过api排序列参考 https://datatables.net/extensions/colreorder/
