### ISSUE TITLE
样例中有一个问题，关于固定列的

### ISSUE THREAD

**Issue by 49839013** [ssy341/datatables-cn#303]
https://datatables.net/extensions/scroller/examples/initialisation/fixedColumns.html

这是一个滚动加载+固定列的样例，当拖动到下方，然后随便点击一个列头排序，就会有问题，横向滚动条没有了，固定列也无法体现了。。。
这个问题如何解决。。。。

**Comment by occultskyrong** [comment]
横向滚动条出现的原因。。。是某行`Country`的值超出宽度导致的横向滚动。
这是css的范畴，把`width`调大即可。
至于你说的“横向滚动条没有了”，是因为排序后的`Country`的length比较短，不需要横向滚动即可全部呈现。

而“固定列也无法体现了”，未发现此情况？？

如有问题，请追加描述~
