### ISSUE TITLE
表头和表格内容错位，不对齐。

### ISSUE THREAD

**Issue by yelett** [ssy341/datatables-cn#304]
设置了
`"scrollY": "400px",
"scrollCollapse": true,
 "scrollX": "500px",
"autoWidth" : false,`
还有设置了每一列的列宽
`"columnDefs": [
            {
                "targets": [ 0 ],
                "width": "5%"
            },{
                "targets": [ 1 ],
                "width": "35%"
            },{
                "targets": [ 2 ],
                "width": "40%"
            },{
                "targets": [ 3 ],
                "width": "20%"
            }]`
![image](https://user-images.githubusercontent.com/15226428/34807630-d30d938c-f6c4-11e7-93f1-d13b5dc183a8.png)

怎样对齐？

**Comment by whyNotHide** [comment]
我也遇到同样的问题了，请问解决了吗

**Comment by yelett** [comment]
不知道官方解决方法怎么设定，我是手动将表头第一列宽度设大的。

**Comment by DitaHua** [comment]
$.each($.fn.dataTable.tables(true), function(){
		      $(this).DataTable().columns.adjust();
		   });

**Comment by whyNotHide** [comment]
楼上的方法是可行的，但是要在模态框shown之后调用才有效

**Comment by lmhb** [comment]
我也被这个问题困扰，在bootstrap弹框中使用datatable的。
是因为初始化的顺序不对，弹出层弹出来的时候，宽度还没有设置，弹出后才设置。
在弹框弹出后事件中再渲染表格，就可以了。

**Comment by 1joker** [comment]
var table = $.fn.dataTable.fnTables(true); //防止tab切换后的表头错位
						if(table.length > 0) {
							$(table).dataTable().fnAdjustColumnSizing();
						};
