### ISSUE TITLE
分页查询的情况下怎样全量导出（有接口获取全量数据）？

### ISSUE THREAD

**Issue by aFlappyPig** [ssy341/datatables-cn#307]

**Comment by occultskyrong** [comment]
### 提供一个解决思路

#### 前端
1. 把对应的“导出”按钮做成一个链接
2. 点击按钮，跳转到对应链接 `/source/download` ，其为静态资源地址，此时浏览器会自动开启下载

#### 后端
3. 后端拦截到 `/source/download` 的路由请求后，
    将链接对应的数据（链接中可以带一定的参数来完成查询SQL的拼接，诸如`offset/limit`等）整合成一个所需格式(`excel`、`xls`等)的文件 `/public/download/xxx.xls` 
4. 然后转发(`redirect`) `/source/download` 链接请求到 `/public/download/xxx.xls`

### 几点说明：
1、 **一定、不要**在前端完成全量数据的拼接，数据拉取过程中极有可能`timeout`。
2、因为是分页服务端`server-side`模式，每次的数据量都是小量，一旦全量下载，后端拼装完成后的`excel`文件大小和传输方式（文件流）比前端使用`ajax`或其他下载方式美好太多。。。

**Comment by occultskyrong** [comment]
已归档到#356
