### ISSUE TITLE
row().data()  获取行数据或者设置行数据，获取不到undefined

### ISSUE THREAD

**Issue by yelett** [ssy341/datatables-cn#309]
row().index() 和 row().data() 都是undefined，官网给的方法，什么原因？

![image](https://user-images.githubusercontent.com/15226428/35079591-842f9768-fc43-11e7-9f12-9278dd13301f.png)

**Comment by TheMonsterSTAN** [comment]
试试这个
var index = table.row($(this)).index();
var data= table.row($(this)).data();

**Comment by occultskyrong** [comment]
如还有问题，请追加下说明，复现条件。
