### ISSUE TITLE
java datatables分页的问题

### ISSUE THREAD

**Issue by SssJava** [ssy341/datatables-cn#311]
在datatables分页的时候需要返回已经分好页的数据，还有总条数，但是我用了两次查询，

第一次查询了分页好的数据，第二次查询总的条数
感觉比较耗费效率，
有没有比较好的方法呢？

**Comment by occultskyrong** [comment]
这个跟你使用服务端ORM有关系吧？

比如我用的`NodeJS`的`sequelize` 有个方法`findAndCountAll` 会在结果集中给出 `{count:0,rows:[]}`数据。

这个地方，服务端理论上就是需要查询两次，如你所述：第一次获取分页数据，第二次查询总条数。
目的是为了在总条数发生变化时，即时反馈到页面端展示。
你如果把总条数缓存。。会导致`count(*)`数据变化时前端未即时响应，尤其是根据`createdAt`排序时，新增的数据显示到页面上，然后总条数没变，就很尴尬了。。而且总条数的目的是为了 `count/length` 计算分页数量使用，`count`非实时会导致页数错误。
