### ISSUE TITLE
新版的DataTables的dataSrc中如何为td添加class？

### ISSUE THREAD

**Issue by JohnGene** [ssy341/datatables-cn#312]
"dataSrc": function ( json ) {
      for ( var i=0, ien=json.data.length ; i<ien ; i++ ){
	        json.data[i][0] =json.data[i].logid ;
	        json.data[i][1] = i+1;
		 json.data[i][2] =json.data[i].title;
	 }
	 return json.data;
}

**Comment by ssy341** [comment]
添加class属于渲染，不应该放在datasrc里处理，你可以参考：http://datatables.club/manual/daily/2016/04/25/option-columns-render1.html
http://datatables.club/reference/option/columns.createdCell.html
