### ISSUE TITLE
这个插件是开源的吗

### ISSUE THREAD

**Issue by empty-back** [ssy341/datatables-cn#314]
[datatables首页](http://datatables.club/)写着支持各式各样的扩展: Editor, TableTools, FixedColumns ……免费开源 ([MIT license](https://datatables.net/license/mit))
但是[Editor](https://editor.datatables.net/purchase/index)不是15天免费得花钱的吗，求解

**Comment by wthahaha** [comment]
围观

**Comment by ssy341** [comment]
editor是收费的，其他都是开源
