### ISSUE TITLE
如何动态显示列数

### ISSUE THREAD

**Issue by huangshuijin** [ssy341/datatables-cn#315]
表格的列的条数根据数据来变化

**Comment by xiaoquanquanxin** [comment]
请求到数据以后,销毁原来的datatables,再次实例化datatables

**Comment by HACLANG** [comment]
我的出现"No matching records found"一点击排序表里的数据就全部没了

**Comment by HACLANG** [comment]
sorry,是No data available in table

**Comment by pumpkin123** [comment]
//设置第三列为不可见（默认从0开始计数）
var columnOne = mytable.column(2);
columnOne.visible(false);

**Comment by ssy341** [comment]
@huangshuijin 参考 #4
