### ISSUE TITLE
datatables请求数据量过大的问题

### ISSUE THREAD

**Issue by lgh611** [ssy341/datatables-cn#317]
使用ajax请求，要统计recordsTotal这个数据时过慢，有什么方法去优化这个问题？或者不需要统计这个值，从而实现分页？

**Comment by HACLANG** [comment]
我的出现"No matching records found"

**Comment by hyytime** [comment]
我的方法就是做分页加载

**Comment by lgh611** [comment]
怎么分页加载？

**Comment by ssy341** [comment]
@lgh611 页数是根据每页显示的条数和总记录数计算出来，目前没有办法，你可以去掉总数和页数，只有上一页，下一页，这样就不需要你查询总记录数，但是这需要你自己去实现，默认的方式是需要总记录数的
