### ISSUE TITLE
在分页状态下 怎么把当前页的最后一行和下一页的第一行交换位置

### ISSUE THREAD

**Issue by TheMonsterSTAN** [ssy341/datatables-cn#320]
![image](https://user-images.githubusercontent.com/30610541/35911003-789b874a-0c33-11e8-82ff-5b49d88c0415.png)
如图，当前页的行顺序都能交换，但是当前页的最后一行和下一页的第一行怎么交换位置呢，能否从dataTable中获取未显示的页的信息，btw 因为数据量不会很大的关系 我是通过html直接绑定的dataTable的

**Comment by Thomsonxu** [comment]
修改dom不可以吗
