### ISSUE TITLE
关于datatables使用server_side模式时搜索汉字报错的问题：

### ISSUE THREAD

**Issue by 80xp** [ssy341/datatables-cn#321]
**[由于无法上传图片，我把描述与截图放在了word文档里，请大家到 
【http://www.kj58.com/TMP/test/关于datatables使用server_side汉字报错的问题.docx】  下载。**

关于datatables使用server_side模式时搜索汉字报错的问题：

首先说明我使用的阿里云的免费的空间和数据库。
数据库的show variables like 'character%';如下图所示：
 
当我从datatables.club下载了以后,通过使用examples/server_side/scripts/mysql.sql来创建了表datatables_demo_gbk并插入了57条数据,创建表时指定了DEFAULT CHARSET=gbk; 创建后表的属性如下图所示：
 
各表字段均显示属性如下图：
 
表中包含汉字的数据如下图：
 
配置好server_processing.php文件后在exsamples/data_sources/server_side.html中直接显示为空，如下图：
 
经F12调试查看，只要为汉字的字段就为null，如下图：
 
使用server_side.html右上角的search搜索英文正常，但搜索汉字无结果，如下图：
 
调试截图：
 
求指教原因与解决方法，感谢。

另我在本地调试：
本地数据库属性均为utf8格式:
 
建立的表datatables_demo_gbk属性如下图：
 
且经检查各字段均为：
 
页面可以显示：
 
但搜索汉字会报错：
 
F12调试的：
 
经检查server_processing.php 格式为gbk格式，server_side.html也为gbk格式。

在本机建立表datatables_demo_utf8，并指定DEFAULT CHARSET=utf8;
当server_side.html和server_processing.php均为gbk格式时报错加载正常，但search汉字报错：
 
更改server_side.html和server_processing.php均为utf8格式加载也正常显示，但search汉字也同样报错：
 

求解决方法！对这个不熟悉，请各位大侠指点啊！

**Comment by ssy341** [comment]
@80xp 不知道报什么错，一起贴出来看看，我使用汉字是没有问题的

**Comment by 80xp** [comment]
![image](https://user-images.githubusercontent.com/25603138/36515554-f0dba1cc-17b4-11e8-97ff-ca35810d3570.png)

感谢回复，上边写的有些乱。初始化的时候显示没问题，但是使用右上角的搜索的时候输入汉字就会报这个错，输入字母数字是没有问题的。
如果可以麻烦加我QQ271407838 ，谢谢了。

**Comment by 80xp** [comment]
我以为不能上传图片的，原来直接粘贴进来就可以了。

**Comment by 80xp** [comment]
我想使用网页格式为utf8的格式的，应该注意一些什么才可以？如数据库参数是否有关系？建表语句中的格式是否需要制定gbk还是utf8？还有网页的格式需要改吗？默认下下来的server_processing.php是gbk的。还有那个ssp.class.php也是。

如果可以能否帮忙留下QQ号码？我的271407838，谢谢了。
