### ISSUE TITLE
中英文显示自由切换

### ISSUE THREAD

**Issue by ghost** [ssy341/datatables-cn#323]
我需要让datatables的中英文显示自由切换，我需要大家的帮助，尝试了多种方法都不行

**Comment by ssy341** [comment]
目前来说只能重新初始化：

```javascript
var table = $("#tableid").DataTable({
    retrieve:true, //允许重新初始化
    language:{
        search:"search"
    }
});

 $("#tableid").DataTable({
    language:{
        search:"搜索"
    }
});

```

**Comment by occultskyrong** [comment]
搜索关键词  `dynamically change language strings`

参考：
> https://github.com/DataTables/DataTables/issues/264
>
> https://github.com/DataTables/DataTables/issues/536
>
> https://stackoverflow.com/questions/14370715/datatables-change-language-dynamically

> This issue will be updated when there is a change, but it is unlikely dynamic i18n options will be coming soon.
