### ISSUE TITLE
Datatables怎么制作月历表头

### ISSUE THREAD

**Issue by Arvin9264** [ssy341/datatables-cn#324]
怎么制作月历表头，从本月第一天起至今天。
![default](https://user-images.githubusercontent.com/33503979/36627222-a7ea5ad6-197a-11e8-976e-c2667f56b426.png)

**Comment by occultskyrong** [comment]
建议

- 使用`JQuery`自行构造月历的1-n日对应的`html`
- 然后填充到`table`的`thead`
- 仅用`DataTables`填充`tbody`部分
