### ISSUE TITLE
局部刷新时 table 出现嵌套加载

### ISSUE THREAD

**Issue by skyofsea** [ssy341/datatables-cn#325]
页面引入了datatable 插件，并在table 上引用了datatable 的搜索，分页，排序等table功能。同时页面涉及到局部刷新（局不刷新不包含table表单在内），当触发局部刷新时，table上的分页，排序，搜索，页面显示量就会嵌套显示第二个

**Comment by 4198222025** [comment]
你好，你的问题解决了吗，我可能遇到了和你一样的问题


![error](https://user-images.githubusercontent.com/10584117/40820440-253ab1e8-6593-11e8-9067-1ddbc0a9fdbc.png)
