### ISSUE TITLE
复制按钮的语言设置无效

### ISSUE THREAD

**Issue by Max-Qiu** [ssy341/datatables-cn#326]
![image](https://user-images.githubusercontent.com/30647194/36786117-28c3fc6e-1cc0-11e8-92cc-adc631de9e0e.png)
上图所示区域，在语言配置文件中添加下图红框内的代码后，语言设置直接全部失效，求解
![image](https://user-images.githubusercontent.com/30647194/36786184-6124366e-1cc0-11e8-9ccf-452916238222.png)
注：datatables版本1.10.16

**Comment by ssy341** [comment]
https://datatables.net/reference/button/copyHtml5
https://datatables.net/reference/button/copyFlash
@Max-Qiu 参考以上两个链接，html5和flash是不同的参数名，
html5

```javascript
{
    copy: 'Copy',
    copySuccess: {
        1: "Copied one row to clipboard",
        _: "Copied %d rows to clipboard"
    },
    copyTitle: 'Copy to clipboard',
    copyKeys: 'Press <i>ctrl</i> or <i>\u2318</i> + <i>C</i> to copy the table data<br>to your system clipboard.<br><br>To cancel, click this message or press escape.'
}
```

flash
```javascript
$('#myTable').DataTable( {
    language:
        buttons: {
            copyTitle: 'Data copied',
            copyInfo: {
                _: 'Copied %d items',
                1: 'Copied a single item'
            }
        }
    },
    buttons: [
        'copyFlash'
    ]
} );
```
是否这个地方有问题？
