### ISSUE TITLE
datatable怎么在vue中使用

### ISSUE THREAD

**Issue by HeTian666** [ssy341/datatables-cn#327]
通过datatables文档采用npm的方式下载了datatables插件，但是应该怎么在vue中使用呢，新手求教，，拜谢

**Comment by occultskyrong** [comment]
参考
> https://datatables.net/forums/discussion/42571/datatables-with-vue-js
> 
> 原作者给出一个npm module
> https://www.npmjs.com/package/vue-datatables
> 另一个 module
> https://github.com/OneWayTech/vue2-datatable

具体的解决方案，去找下vue的社区问下。

如还有问题，即时反馈~
