### ISSUE TITLE
如何获取某列所有值，列表分页

### ISSUE THREAD

**Issue by huangshuijin** [ssy341/datatables-cn#329]

**Comment by occultskyrong** [comment]
参考
> https://datatables.net/forums/discussion/13810/how-to-get-all-of-the-values-in-a-single-column
> 
> https://datatables.net/plug-ins/api/fnGetColumnData (PS:此插件已弃用)
>
> https://datatables.net/reference/api/column().data()
>

直接使用 `column().data()`即可
```
var table = $('#example').DataTable();
 
alert( 'Column 4 sum: '+
    table
        .column( 4 )
        .data()
        .reduce( function (a,b) {
            return a + b;
        } );
);
```

**Comment by huangshuijin** [comment]
谢谢



huang_shui_jin@163.com
 
发件人： sky91.cn
发送时间： 2018-04-12 16:46
收件人： ssy341/datatables-cn
抄送： 黄水金; Author
主题： Re: [ssy341/datatables-cn] 如何获取某列所有值，列表分页 (#329)
参考
https://datatables.net/forums/discussion/13810/how-to-get-all-of-the-values-in-a-single-column
https://datatables.net/plug-ins/api/fnGetColumnData (PS:此插件已弃用)
https://datatables.net/reference/api/column().data()
直接使用 column().data()即可
var table = $('#example').DataTable();
 
alert( 'Column 4 sum: '+
    table
        .column( 4 )
        .data()
        .reduce( function (a,b) {
            return a + b;
        } );
);
