### ISSUE TITLE
datatables在IE8下面body内容无法显示

### ISSUE THREAD

**Issue by pq771271668** [ssy341/datatables-cn#33]
datatables在IE8下面body内容无法显示
![image](https://cloud.githubusercontent.com/assets/9813224/19632906/320550cc-99de-11e6-9d77-093c3e5be4c1.png

**Comment by ssy341** [comment]
@pq771271668 提问参考 #2

**Comment by macoluoer** [comment]
DataTables是否支持ie8浏览器？
