### ISSUE TITLE
[新手求助]Uncaught TypeError: Cannot read property 'nTable' of null

### ISSUE THREAD

**Issue by ghost** [ssy341/datatables-cn#330]
![1](https://user-images.githubusercontent.com/21291399/37386124-ff945690-2791-11e8-89d9-ad5e15bc0482.png)
一直找不到原因，请大佬指出错误所在，谢谢！

**Comment by occultskyrong** [comment]
贴一下你使用DT的config代码。

**Comment by ssy341** [comment]
@liuxu379 还需要贴你初始化代码，从你的错看出，你的$("#tableid").DataTable();  tableid 并不是一个table标签，你检查下
