### ISSUE TITLE
如何为DataTables增加异常处理

### ISSUE THREAD

**Issue by langzf** [ssy341/datatables-cn#333]
当后台出现异常时，前端页面无法接收异常信息，并中断请求

**Comment by occultskyrong** [comment]
### DataTables serverside 错误处理

**以下内容请注意对应DataTables版本**

后台出现异常，是指服务端API处理逻辑出错，此时后端应中断请求，记录错误日志。
同时，服务端向前端返回api内容，api内容可以如下：
```
/* chrome-extension://pkgccpejnmalmdinmhkkfafefagiiiad/template/fehelper_jsonformat.html */
{
    "data": [],
    "recordsTotal": 0,
    "recordsFiltered": 0,
    "draw": 1,
    "error": ""
}
```
其中 `draw` 应为 `request` 中的 `draw` 参数，`error` 为错误信息。

前端处理，因 `total`为0，此时`DataTables`会在页面中显示 [language.infoEmpty](https://datatables.net/reference/option/language.infoEmpty) 配置的信息

如需更直接的提示用户，可使用 [$.fn.dataTable.ext.errMode](https://datatables.net/reference/option/%24.fn.dataTable.ext.errMode)

或参考 [Returned data - error](https://datatables.net/manual/server-side#Returned-data)

> Optional: If an error occurs during the running of the server-side processing script, you can inform the user of this error by passing back the error message to be displayed using this parameter. Do not include if there is no error.

或参考[Error event ](https://datatables.net/reference/event/error)
