### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by 943885179** [ssy341/datatables-cn#335]
放在script下直接可以初始化，但是放在$(function(){})里就无法初始化
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script type="text/javascript" src="~/Scripts/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script src="~/Scripts/datatables.min.js"></script>
<script type="text/javascript" language="javascript">
   //$('#myTable').DataTable();//放在外面就初始化成功
    $(function () {
       $('#myTable').DataTable();//放在里面就初始化失败，报错not a function
    })
</script>

**Comment by ssy341** [comment]
@943885179 贴点代码，还有控制台报错的信息
