### ISSUE TITLE
Buttons中有一个配置项columns，可以过滤显示的列头，此处有疑问

### ISSUE THREAD

**Issue by xzdm** [ssy341/datatables-cn#337]
```
new $.fn.dataTable.Buttons(table, {
    buttons: [
        {
            extend: 'colvis',
            columns: ':gt(0)'
        }
    ]
});
```
例子中 `columns: ':gt(0)'` 表示显示大于0的列头项，同理 `‘:lt(20)’` 表示显示小于20的列头项，但是我想这两个条件同时满足，貌似没找到怎么解，有了解的吗？谢谢了

**Comment by chenbin731307423** [comment]
你这个问题是jquery选择元素匹配问题了。:lt(index) 和 :gt(index) 是你说的这样没错，但是要获取在什么范围区间的，没有现成的between，我想了下，应该可以换种思路，给你要选择的那些列头项加上一个统一的class，用.className  或者 用：not() 去匹配   请自己查看jquery 选择器

**Comment by xzdm** [comment]
OK，谢谢了。经过简单测试，可直接使用（.showCols是自定义的class）：
` buttons: [
        {
            extend: 'colvis',
            columns: '.showCols'
        }
    ]`
但是使用jq的not('.showClos')貌似不行的；
