### ISSUE TITLE
如何设置scrollX：true的情况下，，th中的含有sort不换行

### ISSUE THREAD

**Issue by AndyChen146** [ssy341/datatables-cn#344]
你好！ 我在table中加了scrollX：true属性，th和td都加了white-space: nowrap; th中全是文字的时候可以实现不换行。但是th中有sort(排序)箭头的时候，箭头就会换行，如何可以实现不换行？

**Comment by occultskyrong** [comment]
请提供以下信息，包括但不限于：
    
#### 1. 使用DataTables的源（CDN地址、本地源文件）

#### 2. DataTables的版本

#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图

#### 6. 其他你认为可以帮助解决问题的信息
