### ISSUE TITLE
使用 .DataTable().column(0).visible(false)后，只对thead里的单元格隐藏了，不是一整列隐藏

### ISSUE THREAD

**Issue by Tengjungui** [ssy341/datatables-cn#345]
## 使用 .DataTable().column(0).visible(false)后，只对thead里的单元格隐藏了，不是一整列隐藏

**Comment by occultskyrong** [comment]
请提供以下信息，包括但不限于：
    
#### 1. 使用DataTables的源（CDN地址、本地源文件）

#### 2. DataTables的版本

#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图

#### 6. 其他你认为可以帮助解决问题的信息
