### ISSUE TITLE
如何同时初始化两个结构不相同的DT

### ISSUE THREAD

**Issue by ghsqzy** [ssy341/datatables-cn#348]
我想同时初始化两个不同结构的表格，然后根据条件显示其中的一个，那么该怎样进行初始化

**Comment by occultskyrong** [comment]
初始化时是否有数据？
初始化时是否需要展示数据？
“同时初始化”是否意味着两者数据源相同？
“然后根据条件显示其中的一个”，既然只需要显示一个，为何要“同时初始化两个”？

使用单独的`ajax`拿到数据，根据条件来判断哪个`table`需要使用DT来进行初始化，这种是否更合理？

初始化DT后销毁，参见 [destroy() - Destroy the DataTables in the current context](https://datatables.net/reference/api/destroy())
