### ISSUE TITLE
datatables如何自定义导出数据啊？

### ISSUE THREAD

**Issue by huanglinq** [ssy341/datatables-cn#35]
有没有详细的案例，？还是说它只能导出当前显示页面的数据？？

**Comment by ssy341** [comment]
@huanglinq datatables的导出比较简单，复杂的导出不推荐使用，java的推荐使用poi实现导出操作，更灵活，更强大。

**Comment by huanglinq** [comment]
想过用poi来写，其实就是想用datatables自带的偷点赖，没有就自己写咯。

**Comment by occultskyrong** [comment]
已归档到#356
