### ISSUE TITLE
datatables的每列求和，并根据过滤后结果，动态变化

### ISSUE THREAD

**Issue by wendyShao0129** [ssy341/datatables-cn#350]
jquery datatables每列求和，并根据过滤后结果，动态变化

**Comment by summernian** [comment]
var col = [3,4];//需要计算的列，需要是数组
		var $tr = $('#main_table1_wrapper .dataTables_scrollBody tbody tr'),
			$trLength = $tr.length,
			colLength = col.length,
			arr = [];
		if (Array.isArray(col)) {
			for (var i = 0; i < colLength; i++) {
				var colItem = Number(col[i]);
				if (isNaN(colItem)) {
					continue;
				}
				setText(col[i])
			}
		} else {
			setText(col)
		}
		function setText(col) {
			for (var i = 0; i < $trLength; i++) {
				var $td = $tr.eq(i).find('td').eq(col);
				if ($td) {
					var num = Number($td.text());
					if (isNaN(num)) {

					} else {
						arr.push(num)
					}
				}
			}
			if (arr.length <= 0) {
				$('#main_table1_wrapper div.dataTables_scrollFoot tfoot tr th').eq(col).html(
					'<span style="color:red"></span>'
				);
			} else {
				if (typeof Number.prototype.add == 'undefined') {
					self.addNum();
				}
				var last = arr.reduce(function (a, b) {
					return a.add(b)
				})
//				console.log(last)
				$('#main_table1_wrapper div.dataTables_scrollFoot tfoot tr th').eq(col).html(
					'<span class="text-danger"  title = "' + last.toFixed(2) + '" >' + last.toFixed(2) + '</span>'
				);
			}
			// 计算完后清空arr里面的值
			arr = [];
		}
