### ISSUE TITLE
如何给td添加title属性

### ISSUE THREAD

**Issue by MaWenYan0810** [ssy341/datatables-cn#352]
给td添加超出长度后用...代替，但是希望鼠标悬停到td时可以显示全部内容

    
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

**Comment by occultskyrong** [comment]
`google` 搜 [`datatables add title to td`](https://www.google.com.hk/search?source=hp&ei=YHAPW7aICIWj0gTiv53gCA&q=datatables+add+title+to+td&oq=datatables+add+title+to+td&gs_l=psy-ab.3...95.95.0.413.2.1.0.0.0.0.0.0..0.0....0...1.2.64.psy-ab..2.0.0.0...0.2itUnIll9h8)

> https://datatables.net/forums/discussion/28162/is-it-possible-to-add-a-title-or-other-attribute-to-an-individual-cell-using-columns-render
