### ISSUE TITLE
DataTables排序的iSortingCols怎么一直都是1呢，没有排序的时候默认都是第一列排序，

### ISSUE THREAD

**Issue by shenlw2005** [ssy341/datatables-cn#354]
DataTables排序的iSortingCols怎么一直都是1呢，没有排序的时候默认都是第一列排序，

**Comment by occultskyrong** [comment]
#### 1. 使用DataTables的源（CDN地址、本地源文件）

#### 2. DataTables的版本

#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图

#### 6. 其他你认为可以帮助解决问题的信息
