### ISSUE TITLE
如果想要，点击某行，该行的tr可以进行行内编辑，不点击，不可以进行行内编辑应该如何做

### ISSUE THREAD

**Issue by freegg** [ssy341/datatables-cn#36]

**Comment by ssy341** [comment]
@freegg 参考 
行内编辑（php） 网友共享 示例 Datatables中文网:http://datatables.club/example/user_share/inline_edit.html#

行内编辑 不使用插件实现（php） 网友共享 示例 Datatables中文网:http://datatables.club/example/user_share/inline_edit_no_plugin.html#
