### ISSUE TITLE
有关分页的问题

### ISSUE THREAD

**Issue by abbbbXd** [ssy341/datatables-cn#363]
开发语言、框架为（NodeJs、JQuery）

#### 4. 使用DataTables的配置信息

``` javascript
$('#example2').DataTable({
            // data: res,
            columns: [
                { title: 'no' ,data: 'no' },
                { title: 'name' ,data: 'name' },
                { title: 'count' ,data: 'count' },
                { title: 'bid' ,data: 'bid' },
                { title: 'amount' ,data: 'amount' },
                { title: 'price' ,data: 'price' },
                { title: 'category' ,data: 'category' },
                { title: 'date' ,data: 'createTime' },
                { title: 'remark' ,data: 'remarks' },
                { title: 'weight(kg)' ,data: 'weight(kg)' },
                { title: 'thickness(cm)' ,data: 'thickness(cm)' },
            ],
            "language": {
                lengthMenu: "每页 _MENU_ 条记录",
                zeroRecords: "没有找到记录",
                info: "第 _PAGE_ 页 ( 总共 _PAGES_ 页 )",
                infoEmpty: "无记录",
                infoFiltered: "(从 _MAX_ 条记录过滤)",
                search: "搜索：",
                paginate: {
                    next: "下一页",
                    previous: "上一页"
                }
            },
            processing: true,
            serverSide: true,
            ordering: false,
            ajax: {
                url: 'xxxxxxxxxxxxxxxxx',
                type: 'GET',

            }
        });
```

因为数据量比较大的关系，所以用到服务器处理的分页。

想实现的效果是这样的：根据页码和每页显示的数量去数据库查数据，通过后端返回总页数和当前页数来显示前端的一些当前页数和总页数这些参数，不知道该如何实现。

请各位大佬指点一二，先谢谢了

**Comment by creazy412** [comment]
我这边实现了，只是有一点不完美的瑕疵，现一同探讨求解：
ajax 请求服务端的函数如下：
`    public function datatableAction()
    {
        header('Content-type: text/html; charset=utf8');
        $res = $_POST;

        $start = 0; // 起始索引  
        $length = 0; // 分页长度  
        $jsonarray = $res;

        foreach ($jsonarray as $key => $value) {   
            if ($key == "draw") {  
                $draw = intval($value);  
            }
            if ($key == "start") {  
                $start = $value;  
            }
            if ($key == "length") {  
                $length = $value;  
            }
        }
        
        $data = array();  
        $newArray = Array();   
        $mysqli = new mysqli("xxx.xxx.xxx.xxx:3306","root","123456","tttt");
        $mysqli->query("SET NAMES utf8mb4");
        if (mysqli_connect_errno()) {
            printf("Connect failed: %s\n", mysqli_connect_error());
            exit();  
        }
        // 后续改成 pdo 形式
        $sql = "select * from country limit $start, $length ";
        $result = $mysqli->query($sql);
        $count = $mysqli->query("select * from country")->num_rows;
        while ($row = $result->fetch_array()) {
            $data = array(
                $row["code"],
                $row["code"],
                $row["name"],
                $row["population"]	
            );// ,$row["ip"],$row["device_type"],$row["create_time"] 
            array_push($newArray, $data);   
        }
        $json_data = array(
            'draw' => $draw,
            'recordsTotal' => $count,
            'recordsFiltered' => $count,
            'data' => $newArray,
            'error' => ''
        );//按照datatable的当前页和每页长度返回json数据  
        $obj = json_encode($json_data);
        
        echo $obj;
        die;
    }`

页面js代码：

$('.table-sort').dataTable({
		"processing": true,
		"aaSorting": [[ 2, "desc" ]],//默认第几个排序
		"statesave": false,//状态保存
		"aoColumnDefs": [ // 控制列的隐藏显示
		  {
			"visible": false, 
			"targets": [ ]
		  }
		],
		//{"orderable":false,"aTargets":[0,8,9]}// 制定列不参与排序
		"searching": true,
		"serverSide": false,  // 启用服务器端分页，即开启后端分页
		"lengthMenu": [ // 自定义分页长度
            5, 50, 100 // [5, 50, 100],[10, 20, 30]
		],
		"ajax": {
		    url: "datatable",
			type: "POST",
		}
	});

**问题遗留点：
目前这种方式是可以展现数据的，只是有些固定列（多选框列、操作列）总是被覆盖，无法自定义展现数据？？**

上面的代码是使用了H-ui模版，从其中拷贝修改粘贴出来的，有需要可以去官网http://www.h-ui.net/index.shtml寻求代码

**Comment by creazy412** [comment]
有了解到使用 autofill.columns:option 选择去开启和定义固定列，可就是无法实现！

**Comment by creazy412** [comment]
**想主意解决了：**
`/**
     * datatable 的基础之上修改
     * 
     */
    public function datatable4Action()
    {
        header('Content-type: text/html; charset=utf8');
        $res = $_POST;

        $start = 0; // 起始索引  
        $length = 0; // 分页长度  
        $jsonarray = $res;

        foreach ($jsonarray as $key => $value) {   
            if ($key == "draw") {  
                $draw = intval($value);  
            }
            if ($key == "start") {  
                $start = $value;  
            }
            if ($key == "length") {  
                $length = $value;  
            }
        }
        
        $newArray = Array();
        $data = '{
            "success": true,
            "data": {
                "pageUnit": 10,
                "pageNums": 1,
                "total": 10,
                "list": [{
                    "id": "root_fada474d8d1ed014a783a2d0f4dde238_11012",
                    "title": "诨衫滋偷捍瞎涣妒廖凰",
                    "summary": "2018\/04.04f=224铰蒙耐28b7d<span>e<\/span>c5坟柯乇诿挖陕籽涎https:\/\/w<span>e<\/span>ibo.com\/p\/1005056517786696?2018\/04.04x=xu8禄乒蓝854a70c5纶拔辰技亢狗教崭https:\/\/w<span>e<\/span>ibo.com\/p\/1005056517788511?2018\/04.04c=7ov豆垂姆f<span>e<\/span>3f5b90淹擦团系亿煌却秩",
                    "sentiment": "中立",
                    "relevance": 10,
                    "datetime": "2018-04-04 04:19"
                }, {
                    "id": "root_a36e4768a68e6fc47dc42fd4d41b82f1_11140",
                    "title": "天下彩网6349cc天空彩票与你同行|s5566cc蠃彩网与你同行|赢彩网1149.cc天下与你同行",
                    "summary": "如今传统的直板手机已经无法带来太多的突破,根据韩媒消息三星年底将会带来一次新的屏幕改革!@daimoi透漏今年底的三星note8x作为note系列的一个分支,会首次尝试采用双拼<span>科技<\/span>,如果说如今的三星s8的曲面已经将单一手机屏幕可见性做到了极致,那么接下来的双屏<span>科技<\/span>将会是一个飞跃.医师说,",
                    "sentiment": "中立",
                    "relevance": 0,
                    "datetime": "2018-04-03 07:02"
                }]
            }
        }';
        $data = json_decode($data, true);
        $count = count($data['data']['list']);
        $listData = $data['data']['list'];
        $listData = array_slice($listData, $start, $length);

        foreach ($listData as $key => $value) {
            $list = array(
                $value['id'],
                $value['title'],
                $value['summary'],
                $value['sentiment'],
                $value['relevance'],
                $value['datetime']
            );
            array_push($newArray, $list);
        }
        
        $json_data = array(
            'draw' => $draw,
            'recordsTotal' => $count,
            'recordsFiltered' => $count,
            'data' => $newArray,
            'error' => ''
        );
        //按照datatable的当前页和每页长度返回json数据  
        $obj = json_encode($json_data);
        
        echo $obj;
        die;
    }`

主要是在 **$('.example').dataTable({})** 里面增加了这个选项：
columnDefs: [ {
            orderable: false,
            className: 'ml-5',
            targets: [6], // 重定义此列
            data: null,
            // 默认去覆盖
            defaultContent: "<a href='javascript:;' onclick=" 
			+ "member_edit('" + '编辑' + "'," + "'index/add?" + 'task_id=1' + "'" + ",this" + ",''" + ",'410'" + ")" + 
			" class='ml-5'" + " style='text-decoration:none'" + "> " + " <i class='Hui-iconfont'>编辑</i> </a>"
