### ISSUE TITLE
设置列宽后，列宽没有改变

### ISSUE THREAD

**Issue by MaWenYan0810** [ssy341/datatables-cn#369]
![image](https://user-images.githubusercontent.com/34049863/42609280-60e1337a-85be-11e8-801e-6961032fc708.png）
表格加载时给第一列指定宽度，但是没有效果；css文件中设置样式，也没有效果

**Comment by zjuncd** [comment]
看不到你的图片

不过，我之前类似的问题是是因为在 DataTable 初始化的时候 AutoWidth 选项没有设置，这个默认是true的，要手动改为false，否则你在Column定义的宽度无效的
```
$("#TableID").DataTable({
    autoWidth: false,
    ...
})

**Comment by MaWenYan0810** [comment]
谢谢你，这个方法我试过了，，还是解决不了。。我这个表格的表头是动态生成的，所以可能是这个原因吗？？

**Comment by guoqiang998** [comment]
先定义列的css样式：
`.column-0 {  
    width: 100px;  
}`  

然后在js初始化datatables时使用它：
`columnDefs: [{  
      targets: 0,  
      class: 'column-0'  
    }...]`

**Comment by gongel** [comment]
columns初始化之前渲染，
columnDefs初始化之后渲染
