### ISSUE TITLE
怎么获取筛选后的表格数据？

### ISSUE THREAD

**Issue by zhuyinjing** [ssy341/datatables-cn#370]
请教大家，我在项目里使用这个方法进行表格的数据筛选显示，
`$.fn.dataTable.ext.search.push`
筛选后，我怎么能获取到筛选后的表格数据？
我获取的都是所有的表格数据，这并不是我想要的。
谢谢🙏

**Comment by CatherineYF** [comment]
请问您得到解决方法了吗？我也遇到同样问题
