### ISSUE TITLE
怎么样关闭datatable的分页和搜索

### ISSUE THREAD

**Issue by iverliu** [ssy341/datatables-cn#375]
#### 1. 使用DataTables的源（CDN地址、本地源文件）

[jquery.dataTables.js.zip](https://github.com/ssy341/datatables-cn/files/2216064/jquery.dataTables.js.zip)

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 6. 其他你认为可以帮助解决问题的信息
尝试过网上提供的几种方案都不行，请帮忙看下，谢谢

**Comment by occultskyrong** [comment]
建议先阅读配置文档

> http://datatables.club/reference/option/

其中关于 `paging`和`searching`的说明

> http://datatables.club/reference/option/paging.html
>
> http://datatables.club/reference/option/searching.html
