### ISSUE TITLE
Ajax 使用时"Uncaught TypeError: Cannot read property 'length' of undefined" jquery.dataTables.min.js (48)

### ISSUE THREAD

**Issue by SureCheung** [ssy341/datatables-cn#376]
http://www.datatables.club/example/ajax/objects.html 
在复现上标网页功能时出现错误，无法加载数据
错误码如下
"Uncaught TypeError: Cannot read property 'length' of undefined"	/ceshi/DataTables-1.10.15/media/js/jquery.dataTables.min.js (48)
HTML代码如下
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
 

		<script type="text/javascript" language="javascript" src="//code.jquery.com/jquery-1.12.4.js"></script>
		<script type="text/javascript" language="javascript" src="DataTables-1.10.15/media/js/jquery.dataTables.min.js"></script>
 

		<script>
   		$(document).ready(function() {
           $('#example').DataTable({
        	"ajax": "data/objects.txt",
        	"columns": [
            { "data": "name" },
            { "data": "position" },
            { "data": "office" },
            { "data": "extn" },
            { "data": "start_date" },
            { "data": "salary" }
     	   ]
    	  });
    	  });
		</script>
	</head>
	<body>
		<table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Office</th>
                <th>Extn.</th>
                <th>Start date</th>
                <th>Salary</th>
            </tr>
        </thead>
 
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Office</th>
                <th>Extn.</th>
                <th>Start date</th>
                <th>Salary</th>
            </tr>
        </tfoot>
    </table>
	</body>
</html>

**Comment by xiaolouluo2813** [comment]
ajax不是这么用的吧，我也不是很会这个，你可以看看

```JavaScript
    "ajax": {
        url: '/serviceCostDetail/list',
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        data: function (d) {
            var params = $('#param_form').serializeArray();
            var s = "";
            for (var i in params) {
                var name = params[i].name;
                var value = params[i].value;
                if (value != "") {
                    s += name + ":\"" + value.trim() + "\",";
                }
            }
            if (s.length > 1) {
                s = s.substring(0, s.length - 1);
                s = "{" + s + "}";
            }
            // 传参给服务器
            d.param = s;
        },
        dataSrc: function (result) {
            return result.data;
        }
    }
```

**Comment by occultskyrong** [comment]
建议阅读 `Datatables.club`的`FAQ`

> http://datatables.club/faqs/
>
> 6，控制台报错 Cannot read property 'length' of null 或者 Cannot read property 'length' of undefined 是怎么回事
> 这个一般是返回的数据有问题，
> 比如应该返回`{data:[……]}`而不是`{tabledata:[……]}`，
> 或者数据为空应该返回`{data:[]} `而不是`{data:null}`、`{data:""}`，dt识别不了所以报此错误 
> 正确返回的数据格式为` {data:[{name:"datatables中文网",url:"datatables.club"}]}`
