### ISSUE TITLE
在进行数据排序时，排序数据不准确，完全是胡乱排序

### ISSUE THREAD

**Issue by guohui123** [ssy341/datatables-cn#379]
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图
![image](https://user-images.githubusercontent.com/20037800/43389628-bf782baa-941e-11e8-924f-83be17c23533.png)
![image](https://user-images.githubusercontent.com/20037800/43389665-da6e801c-941e-11e8-8335-91afcc914203.png)

**Comment by zhuyinjing** [comment]
你这一列的数据类型是 number吗

**Comment by occultskyrong** [comment]
#417
