### ISSUE TITLE
把 columns 里的 data 改成其它的就不行了吗？

### ISSUE THREAD

**Issue by fjdgl** [ssy341/datatables-cn#38]
"columns": [  
		            { "data": "productName" }, 
		            { "data": "productLength" }, 
		            { "data": "productWidth" }, 
		            { "data": "productHeight" },  
		            { "data": "productWeight" },  
          ]

**Comment by ssy341** [comment]
@fjdgl  这个columns.data  就好比是dt内部使用的变量， 他获取到配置后，取值，如果你把data变了，dt内部还怎么去取值呢，这是规则，况且这个不影响你什么，为什么要去更改他呢？
