### ISSUE TITLE
dataTables导出excel，复杂表头显示不全

### ISSUE THREAD

**Issue by SXJ13674930837** [ssy341/datatables-cn#380]
表格是复杂表头，合并后的单元格在页面显示正确，但是导出表格时，显示不全，在excel中取消合并单元格数据可以展示，其中，第一行的colspan是动态的，第二行的pm10/pm25/co等是动态渲染出来的，各位大神怎么解决？请大神指点！

![a4fef0e4-64a0-437a-ab12-2b9ed0f330b5](https://user-images.githubusercontent.com/41094753/43497532-3b0ab786-9575-11e8-894e-c431043fce7b.png)

**Comment by occultskyrong** [comment]
这大概是官方的回应。。。
> https://datatables.net/forums/discussion/comment/138174/#Comment_138174

原文如下
> No - the is no workaround (other than adding the feature and submitting it as a pull request :)).
> Currently, yes, you need to wait until I get a chance to work on this.

你可以根据底下抛出的答案来实现下

> https://github.com/rstudio/DT/issues/418

**Comment by occultskyrong** [comment]
已归档到#356
