### ISSUE TITLE
当表格里的某一行中的某一列数据没有时，怎么隐藏这整行数据

### ISSUE THREAD

**Issue by JinYeChao** [ssy341/datatables-cn#382]
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

**Comment by xxxx518** [comment]
是ajax数据源吗?  如果是ajax数据源可以在ajax设置里设置dataSrc, 在里面处理要显示的数据  例如
  ajax: {
                        url: 'xxx.json',
                        dataSrc: function (json) {
                            var reJson = [];
                            $.each(json,function(i,v){
                               if(v.name!=''){
                                  reJson.push(v);
                               }
                            });
                        return reJson;
                        }
                    },

**Comment by JinYeChao** [comment]
问题已解决,谢谢您的解答
