### ISSUE TITLE
官网表格如何实现

### ISSUE THREAD

**Issue by MemoryBen** [ssy341/datatables-cn#387]
我翻遍手册，只找到这个
https://datatables.net/examples/api/row_details.html
然而这个并不是将多出来的列进行隐藏
求大神解答

**Comment by guoqiang998** [comment]
columnDefs = [ {
			"targets" : 0,
			**"visible" : false**
		} ... ];

另外页面记得隐藏的列也需要加上对应的`<th></th>`

**Comment by ssy341** [comment]
官方页面首页的例子使用[responsive](https://datatables.net/extensions/responsive/)插件，初始化代码如下
```javascript
		$(document).ready( function () {
			$('#example')
				.addClass( 'nowrap' )
				.dataTable( {
					responsive: true,
					columnDefs: [
						{ targets: [-1, -3], className: 'dt-body-right' }
					]
				} );
		} );	
```
