### ISSUE TITLE
添加多选框，切换页面，选中状态失效了

### ISSUE THREAD

**Issue by zhuyinjing** [ssy341/datatables-cn#392]
大家好，在使用datatables的时候遇到了这个问题：
服务端进行分页，在第一列添加了多选框，当我在第一页选中几行后，切换页面再回来，之前选中的都变成了没选中的状态，请问怎么才能记住这个状态呢？谢谢！
部分代码：
```
"aoColumns" : [ {
                "sClass": "text-center",
                 "data": "ID",
                 "render": function (data, type, full, meta) {
                     return '<input type="checkbox" value="' + data + '" />';
                 },
                 "bSortable": false
```

**Comment by occultskyrong** [comment]
cookie 或者 localstorage 存储下选择的行对应的一个唯一标记，id或者其他字段均可。

然后在行render多选框的时候，indexof一下这个已经存储的数组。。

当然，记得及时的把这个数组的内容给销毁或者clear

**Comment by occultskyrong** [comment]
具体的实现参见

> https://datatables.net/forums/discussion/comment/23742/#Comment_23742

**Comment by zhuyinjing** [comment]
这个问题我已经通过代码实现了。

**Comment by lyjgk** [comment]
怎么解决的
