### ISSUE TITLE
根据后端的数据 动态加载表格的thead 以及 tbody

### ISSUE THREAD

**Issue by zhuyinjing** [ssy341/datatables-cn#398]
大家好，
请问大家有没有可能，
表格采用服务端分页的同时，表格的表头不是固定写死的，表格里的内容也是动态生成的？
就相当于在html代码里只写
`<table id="table"></table>`
那如果想让每列显示不同的东西，是不是还要加上判断？
谢谢！

**Comment by zhuyinjing** [comment]
@occultskyrong

**Comment by occultskyrong** [comment]
具体的判断逻辑跟DT本身是无关的。
因为你的业务逻辑导致columns中数据组织方式的不同。
你可以在业务逻辑加载之后，生成对应的columns，再使用DT去实例化一个DataTables实体。
具体参见 
> https://datatables.net/forums/discussion/49652

**Comment by zhuyinjing** [comment]
谢谢 @occultskyrong 
这个问题已经实现了

**Comment by beautifuldays** [comment]
想知道怎么实现的
