### ISSUE TITLE
点击某个单元格，获取它所对应的表头信息

### ISSUE THREAD

**Issue by zhuyinjing** [ssy341/datatables-cn#399]
大家好，
请问大家，当我点击某个单元格的时候，我想获取它所对应的表头，也就是它的 key 的名字，有什么办法吗？
谢谢。
@ssy341 
@occultskyrong

**Comment by zhuyinjing** [comment]
目前实现的是将它的 `key` 赋值给 该单元格的 `value` 属性，然后点击的时候 获取它的 `attr("value")`
```
"mDataProp": d,
              "mRender" : function(data, type, full) {
                  let template = '<span value="'+d+'"class="text-decoration cursor-pointer datalink">' +  data + '</span>'
                  return data === 0 ? data : template
              }
```
想知道 DT 有没有 直接获取点击的单元格所对应的表头的 api？谢谢。

**Comment by occultskyrong** [comment]
`get column name`
搜索结果
> https://datatables.net/forums/discussion/46445

=====

所以，把`columns name`按顺序存起来，然后通过[`cell().index()`](https://datatables.net/reference/api/cell().index())获取到index，在找到对应的name

当然，可以直接用dt的option里面的columns。。。扔到全局变量即可。

**Comment by zhuyinjing** [comment]
谢谢。
