### ISSUE TITLE
如何解决固定列后，查看行明细时,固定列无法展开行明细，右侧活动栏正常展开问题。

### ISSUE THREAD

**Issue by weberloser** [ssy341/datatables-cn#402]
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图
![lnq0 us04522 kulyfhzo6](https://user-images.githubusercontent.com/39765862/45526479-d0acc480-b809-11e8-9c0d-0cb74b955cb0.png)

**Comment by zhaoxiaohui06** [comment]
我也遇到了这个问题，请问你解决了吗？

**Comment by weberloser** [comment]
> 我也遇到了这个问题，请问你解决了吗？

我改用了easyui插件 的treegrid实现了目前需要的功能。

**Comment by zhuyinjing** [comment]
在 on 之前 off 一下
```
$('#patients tbody').off('click', 'tr td.details-control');

$('#patients tbody').on( 'click', 'tr td.details-control', function () {
```

**Comment by zhaoxiaohui06** [comment]
试了一下，不管用呢
你能否帮我看下这个滚动条的问题？谢谢了，滚动条跑到合计上面了
[https://github.com/ssy341/datatables-cn/issues/408](url)
