### ISSUE TITLE
如何实现行嵌套详细内容的展开与折叠

### ISSUE THREAD

**Issue by ZGUIZ** [ssy341/datatables-cn#406]
#### 6. 其他你认为可以帮助解决问题的信息
一个table里面详细信息展开之后是一个table，此table需要再次展开

**Comment by guoqiang998** [comment]
[http://datatables.club/example/api/row_details.html](http://datatables.club/example/api/row_details.html)

**Comment by ZGUIZ** [comment]
> http://datatables.club/example/api/row_details.html
