### ISSUE TITLE
怎么获得分页的最后一页？

### ISSUE THREAD

**Issue by AiYeyeye** [ssy341/datatables-cn#407]
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

**Comment by occultskyrong** [comment]
```JavaScript
const table = $('#example').DataTable();
```

如果你想知道一共有多少页，然后来确定最后一页的值，使用`table.page.info(). pages - 1`，具体查看 
> https://datatables.net/reference/api/page.info()

如果你想跳转到最后一页，使用` table.page( 'last' ).draw( 'page' );`，具体查看
> https://datatables.net/reference/api/page()
