### ISSUE TITLE
datatables 的列太多被折叠了。但是我不想让折叠有什么参数让他不折叠的吗？

### ISSUE THREAD

**Issue by yangyaru0108** [ssy341/datatables-cn#415]

**Comment by fpx006** [comment]
$.get("/xxxx/", function (cur_data) {
            {#alert("Data Loaded: " + cur_data);#}
            $('#dataTable').DataTable({
                data: eval(cur_data),
                "scrollX": true
            });
        });
添加参数"scrollX": true

**Comment by yangyaru0108** [comment]
谢谢您的答复，但是我调试了这个参数对我没有效果

**Comment by yangyaru0108** [comment]
> $.get("/xxxx/", function (cur_data) {
> {#alert("Data Loaded: " + cur_data);#}
> $('#dataTable').DataTable({
> data: eval(cur_data),
> "scrollX": true
> });
> });
> 添加参数"scrollX": true

谢谢您的答复，但是我调试了这个参数对我没有效果

**Comment by watwohaha** [comment]
请问现在解决了吗？我也碰到相同的问题。
