### ISSUE TITLE
整型数据怎么排序呀，默认按字符串排序呢

### ISSUE THREAD

**Issue by rickzuo** [ssy341/datatables-cn#417]
![image](https://user-images.githubusercontent.com/22383362/47546055-07eeb500-d922-11e8-99aa-543718ea34ce.png)

**Comment by occultskyrong** [comment]
## 简单说：`ASCII`

## 复杂点

官方对于`sort()`的说明

> https://datatables.net/reference/api/sort()

> In this case, this method is a proxy for the Javascript Array.prototype.sort method and is provided as a utility method for the DataTables API. 
> For more information about the original method, please refer to the Mozilla MDN documentation for sort.

`JavaScript`的`sort`方法的说明见

> https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description

```doc
如果没有指明 compareFunction ，那么元素会按照转换为的字符串的诸个字符的Unicode位点进行排序。
例如 "Banana" 会被排列到 "cherry" 之前。
当数字按由小到大排序时，9 出现在 80 之前，
但因为（没有指明 compareFunction），比较的数字会先被转换为字符串，所以在Unicode顺序上 "80" 要比 "9" 要靠前。
```

所以，如果你希望数字按照数字排序，请使用`a-b`的方式来实现。
