### ISSUE TITLE
新人请教：导出数据到EXCLE只能导出当前页，怎么取到全部数据

### ISSUE THREAD

**Issue by FCHCX** [ssy341/datatables-cn#418]
<script type="text/javascript">
					$(document).ready(function() {
					    $('#example-6').DataTable( {
					    	dom : "<'row'<'col-sm-5'l><'col-sm-7'Tf>r>"
								+ "t"
								+ "<'row'<'col-xs-6'i><'col-xs-6'p>>"
					    } );
					    excel = new ExcelGen({
					        "src_id": "example-6",
					        "show_header": true,
							 "file_name": "个人工单列表.xlsx"
					    });
					    $("#generate-excel").click(function () {
					        excel.generate();
					    }); 
					} );
					</script>

**Comment by occultskyrong** [comment]
参见 #356
