### ISSUE TITLE
datatables如何内嵌echarts？

### ISSUE THREAD

**Issue by zhaoecho** [ssy341/datatables-cn#419]
需要在datatables的单元格中嵌入一张饼图，用来暂时百分比数据，饼图打算用echarts生成，不知道如何内嵌。

尝试过createRow回调，取不到页面元素，无法初始化echarts。

1. 使用DataTables的源：
本地源文件

2. DataTables的版本：
1.10.18

3. 开发语言、框架：
JQuery

4. 使用DataTables的配置信息

5. 错误信息或截图

6. 其他你认为可以帮助解决问题的信息

**Comment by ssy341** [comment]
@zhaoecho  查询 [createdCell](http://datatables.club/reference/option/columns.createdCell.html) 参数的使用，通过对cell的操作，当DT创建cell的时候，初始化echarts即可
