### ISSUE TITLE
插件没有根据输入数字跳转对应具体页面的功能

### ISSUE THREAD

**Issue by w745784780** [ssy341/datatables-cn#421]
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

**Comment by occultskyrong** [comment]
## 使用`page()`或`page.len()`实现

> https://datatables.net/reference/api/page()
> https://datatables.net/reference/api/page.len()

```javascript
const pageNumber=1;
// TODO: 确认pageNumber小于总页数
table.page(pageNumber).draw( 'page' );
```

注意是要确认你翻页的页数不大于总页数，否则会出现问题，具体查看方法的说明。
