### ISSUE TITLE
关于一个DOM定位

### ISSUE THREAD

**Issue by xiangxingze** [ssy341/datatables-cn#429]
![image](https://user-images.githubusercontent.com/13271663/49015942-852a7580-f1bf-11e8-99f6-ced02dd697e9.png)
怎么在一行显示而不是现在这样换行

**Comment by occultskyrong** [comment]
使用bootstrap的栅格，控制宽度px或者百分比
具体见 
>  **COPY FROM** https://datatables.net/reference/option/dom

```JavaScript
"<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
"<'row'<'col-sm-12'tr>>" +
"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
```

341©写的示例
> http://datatables.club/manual/daily/2016/05/11/option-dom.html
