### ISSUE TITLE
关于表头样式问题

### ISSUE THREAD

**Issue by xiangxingze** [ssy341/datatables-cn#431]
表头列过多，无法自动宽度，关闭自动宽度，使用自定义宽度也无效，使用js 渲染的表格
![image](https://user-images.githubusercontent.com/13271663/49059958-69b67d80-f246-11e8-8fa4-c41c79790e2e.png)
无法居中对齐
![image](https://user-images.githubusercontent.com/13271663/49059981-805cd480-f246-11e8-9a0a-0164ef1036a3.png)

**Comment by occultskyrong** [comment]
自定义宽度可用的前提是你屏幕的宽度大于所有自定义列宽度的和，否则会按照比例压缩列宽度。

具体`css`中`table`宽度的计算参见 

> [css table自动布局下宽度计算](https://blog.csdn.net/qq_27090183/article/details/47702201)
