### ISSUE TITLE
为什么我的datatable不能排序？

### ISSUE THREAD

**Issue by heyapeng123** [ssy341/datatables-cn#432]
<#import "../../layout/global.ftl" as global />

<div class="row">
	<div class="col-md-12">
		<div class="portlet light">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-social-dribbble font-blue-sharp"></i> 
					<span class="caption-subject font-blue-sharp bold uppercase">数据列表</span>
				</div>
				<div class="col-md-4" style="float: right;">
					<div id="sample_1_filter" class="dataTables_filter" style="float: right;">
						<label>
							<input id="startDate" type="text" 
								class="form-control input-sm input-small input-inline" 
									placeholder="选择开始时间" aria-controls="sample_1" onkeydown="getPage();">
						</label>
						<label>
							<input id="endDate" type="text" 
								class="form-control input-sm input-small input-inline" 
									placeholder="选择结束时间" aria-controls="sample_1" onkeydown="getPage();">
						</label>
					
					</div>
				</div>
			</div>
			<div class="portlet-body">
				<table
					class="table table-striped table-bordered table-hover table-checkable order-column table-scrollable "
					id="bee_table" data-url="<@global.api 'xyout/Bill/selectAll'/>"
					data-check="false" cellspacing="0">
					<thead>
						<tr>
							<th data-field="partner">公司名称</th>
							<th data-field="passway_name">通道名称</th>
							<th data-field="information">信息费</th>
							<th data-field="settlement">结算比例(%)</th>
							<th data-field="settlement_cycle">结算周期</th>
							<th data-field="income">收入</th>
							<th data-field="expend">支出</th>
							<th data-field="profit">利润</th>
							<th data-field="profitMargin">利润率(%)</th>
						</tr>
					</thead>
					 
				</table>

			</div>
		</div>
	</div>

</div>

<form id="searchForm" style="display: none;">
	<input type="text" name="search_passwayName"> 
	<input type="text" name="search_partner"> 
	<input type="text" name="startDate"> 
	<input type="text" name="endDate">
	<input type="text" name="settlement_cycle">
</form>

<script type="text/javascript">

  
	var dataTable = $("#bee_table").beeTables();
	 
	var tab = document.getElementById("bee_table");
	var bb = tab.rows[1].cells[0].innerHTML;
	if (bb == "表中无指定条件数据存在！") {
		document.all("bee_table").rows[1].cells[0].innerText = "请选择条件查询";
	}
	
	
   

	$("div.row div.col-md-6.col-sm-6")
			.eq(1)
			.append(
					'<div id="sample_1_filter" class="dataTables_filter">'
							+ '<label><input name="search_passwayName" id="search_passwayName" type="search" class="form-control input-sm input-small input-inline" placeholder="通道名称" aria-controls="sample_1" onkeydown="getPage();" ></label>'
							+ '<label><input name="search_partner" id="search_partner" type="search" class="form-control input-sm input-small input-inline" placeholder="CP名称" aria-controls="sample_1" onkeydown="getPage();"></label>'
							+ '<label><input name="settlement_cycle" id="settlement_cycle" type="search" class="form-control input-sm input-small input-inline" placeholder="结算周期" aria-controls="sample_1" onkeydown="getPage();"></label>'
							+ '<button class="btn btn-sm green" style="margin-left: 10px;"><i class="fa fa-check"></i>查询</button>'
							+ '&nbsp;<button class="btn btn-sm green 1"><i class="fa fa-print"></i>导出数据</button></div>');

	$("button.btn.btn-sm.green").click(function() {
		var search_passwayName = $('#search_passwayName').val();
		var search_partner = $('#search_partner').val();
		var startDate = $('#startDate').val();
		var endDate = $('#endDate').val();
		console.log("startDate:" + startDate + " endDate:" + endDate);
		$('#startDate').val(startDate);
		$('#endDate').val(endDate);
		if (new Date(startDate).getTime() > new Date(endDate).getTime()) {
			alert("选择的时间范围不合理")
			return false;
		}
		queryData();
	
		
	})
	
	
	
	 $("button.btn.btn-sm.green.1").click(function(){
    	var search_passwayName = $("#searchForm").find("input[name='search_passwayName']").val();
    	var search_partner = $("#searchForm").find("input[name='search_partner']").val();
        var startDate = $("#searchForm").find("input[name='startDate']").val();
        var endDate = $("#searchForm").find("input[name='endDate']").val();
        var settlement_cycle = $("#searchForm").find("input[name='settlement_cycle']").val();
    	window.location.href= "xyout/Bill/export?search_passwayName="+search_passwayName+"&search_partner="+search_partner+"&startDate="+startDate+"&endDate="+endDate+"&settlement_cycle="+settlement_cycle;
    })

	function getPage() {
		if (event.keyCode == 13) {
			queryData();
			
		}
	}

	function queryData() {
		$("#searchForm").find("input[name='search_passwayName']").val($("div.row div.col-md-6.col-sm-6").find("input[name='search_passwayName']").val());
		$("#searchForm").find("input[name='search_partner']").val($("div.row div.col-md-6.col-sm-6").find("input[name='search_partner']").val());
		$("#searchForm").find("input[name='settlement_cycle']").val($("div.row div.col-md-6.col-sm-6").find("input[name='settlement_cycle']").val());
		if($('#startDate').val() != '' && $('#endDate').val() != ''){
			$("#searchForm").find("input[name='startDate']").val($('#startDate').val() + " 00:00:00");
			$("#searchForm").find("input[name='endDate']").val($('#endDate').val() + " 23:59:59");
		}
		       
        dataTable.fnDraw(); 
	}
	

	$('#startDate').daterangepicker(
			{
				singleDatePicker : true,
				locale : {
					format : "YYYY-MM-DD",
					separator : " - ",
					daysOfWeek : [ "日", "一", "二", "三", "四", "五", "六" ],
					monthNames : [ "一月", "二月", "三月", "四月", "五月", "六月", "七月",
							"八月", "九月", "十月", "十一月", "十二月" ]
				}
			});
	$('#endDate').daterangepicker(
			{
				singleDatePicker : true,
				locale : {
					format : "YYYY-MM-DD",
					separator : " - ",
					daysOfWeek : [ "日", "一", "二", "三", "四", "五", "六" ],
					monthNames : [ "一月", "二月", "三月", "四月", "五月", "六月", "七月",
							"八月", "九月", "十月", "十一月", "十二月" ]
				}
			});
	$('#startDate').val("");
	$('#endDate').val("");
	
	  
	
 
</script>
/**
 * jquery 插件整合
 * @since 2017年02月08日
 * @author Han.Sun
 */

/**
 * 整合dataTables
 */
(function ($) {
    $.fn.beeTables = function (params) {
        var table = $(this);
        var columns = [];
        var columnDefs = [];
        table.find("thead tr th").each(function (i) {
            var field = $(this).data("field");
            var render = $(this).data("render");
            var format = $(this).data("format");
            var dict = $(this).data("dict");
            var className = $(this).data("class-name");
            if (field) {
                var column = {};
                column.data = field.toString();
                column.defaultContent = '';
                if (format) {
                    column.render = function (data, type, row ) {
                        var date = new Date(data);
                        return date.Format(format)
                    };
                }
                if (render) {
                    column.render = function (data, type, row) {
                        return eval(render + "(data, type, row)");
                    };
                }
                if (dict) {
                    column.render = function (data, type, row) {
                        $.get("sys/dict/type/" + dict + "/" + data, {}, function (result) {
                            return result;
                        })
                    };
                }
                columns.push(column)

            }
            var columnDef = {};
            columnDef.targets = i;
            if (className) {
                columnDef.className = className;
            }
            if (render) {
                columnDef.render = function (data, type, row) {
                    return eval(render + "(data, type, row)");
                };
            }
            columnDefs.push(columnDef)
        });

       
        
        return  table.dataTable({
            "searching": false,
            
            "pagingType": "bootstrap_full_number",
            "autoWidth": false,
            "Sort":true,
            
            
            "Paginage":true,

            "Retrieve": true,
            "serverSide": true,
            "ajax": {
                "url": table.data("url"),
                "type": "post",
                "data": function (data) {
                	
                	
                    var param = {};
                    param.start = data.start;
                    param.length = data.length;

                    return $('#searchForm').serializeObject(param);
                }
               
       
        
            },
            "destroy":true,
            
            
            "createdRow": function (row, data) {
                /*if (data.check) {
                    $('td:eq(0)', row).html('<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">'
                        + '<input type="checkbox"  class="checkboxes" name="chx_default" value="' + data.id + '"/>'
                        + '<span></span>'
                        + '</label>');
                }*/
                if(table.attr("tableRowspan")){
                    $(row).children('td').eq(0).attr('style', 'text-align: center;vertical-align: middle;')
                }
            },
            "columns": columns,
            "columnDefs": columnDefs,  
//            "columns": [
//                {"data": "partner"},
//                {"data": "passway_name"},
//                {"data": "information"},
//                {"data": "settlement"},
//                {"data": "settlement_cycle"},
//                {"data": "income"},
//                {"data": "expend"},
//                {"data": "profit"},
//                {"data": "profitMargin"}
//              ],
             
            "drawCallback": function () {
                var drawCallback = table.data("drawCallback");
                if (drawCallback) {
                    if (drawCallback.indexOf(')') != -1) {
                        eval(drawCallback);
                    } else {
                        eval(drawCallback + "()");
                    }
                }
                if(table.attr("tableRowspan")){
                    tableRowspan(table);
                }
               
            },
          
            "initComplete": function () {
                var initComplete = table.data("initComplete");
                if (initComplete) {
                    if (initComplete.indexOf(')') != -1) {
                        eval(initComplete);
                    } else {
                        eval(initComplete + "()");
                    }
                }
                table.find('.group-checkable').change(function () {
                    var set = jQuery(this).attr("data-set");
                    var checked = jQuery(this).is(":checked");
                    jQuery(set).each(function () {
                        if (checked) {
                            $(this).prop("checked", true);
                            $(this).parents('tr').addClass("active");
                        } else {
                            $(this).prop("checked", false);
                            $(this).parents('tr').removeClass("active");
                        }
                    });
                });

                table.on('change', 'tbody tr .checkboxes', function () {
                    $(this).parents('tr').toggleClass("active");
                });
            },
            "language": {
                "emptyTable": "表中无指定条件数据存在！",
                "info": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录",
                "infoEmpty": "显示0到0条记录",
                "infoFiltered": "(数据表中共为 _MAX_ 条记录)",
                "lengthMenu": "每页显示 _MENU_ 条记录",
                "search": "搜索:",
                "zeroRecords": "表中无指定条件数据存在！",
                "paginate": {
                    "previous": "上一页",
                    "next": "下一页",
                    "last": "末页",
                    "first": "首页"
                }
            }

        });
    };
    
   
   
    $.fn.serializeObject = function (para) {
        var serializeObj = {}; // 目标对象
        var tempObj = {};//临时对象
        var array = this.serializeArray(); // 转换数组格式
        if (para != null && para != undefined) {
            $.each(para, function (name, value) {
                array.push({"name": name, "value": value});
            });
        }
        $(array).each(function () { // 遍历数组的每个元素 {name : xx , value : xxx}
            if (serializeObj[this.name]) { // 判断对象中是否已经存在 name，如果存在name
                if ($.isArray(serializeObj[this.name])) {
                    serializeObj[this.name].push(this.value); // 追加一个值 hobby : ['音乐','体育']
                } else {
// 将元素变为 数组 ，hobby : ['音乐','体育']
                    serializeObj[this.name] = [serializeObj[this.name], this.value];
                }
            } else {
                serializeObj[this.name] = this.value; // 如果元素name不存在，添加一个属性 name:value
            }
        });
        return serializeObj;
    };

    $.fn.toJSON = function () {
        var $elements = {};
        var $form = $(this);
        $form.find('input, select, textarea').each(function () {
            var name = $(this).attr('name');
            var type = $(this).attr('type');
            if (name) {
                var $value;
                if (type == 'radio') {
                    $value = $('input[name=' + name + ']:checked', $form).val()
                } else if (type == 'checkbox') {
                    $value = $(this).is(':checked')
                } else {
                    $value = $(this).val()
                }
                $elements[$(this).attr('name')] = $value
            }
        });
        return JSON.stringify($elements)
    };
    $.fn.beeForm = function (remoteUrl, callback) {
        var $form = $(this);
        $.get(remoteUrl, {}, function (data) {
            $.each(data.data, function (key, value) {
                var $ctrls = $form.find('[name=' + key + ']');
                if ($ctrls.is('select')) {
                    $('option', $ctrls).each(function () {
                        if (this.value == value)
                            this.selected = true;
                    });
                    $ctrls.trigger("change");
                } else if ($ctrls.is('textarea')) {
                    $ctrls.val(value);
                } else {
                    switch ($ctrls.attr("type"))   //input type
                    {
                        case "text":
                        case "hidden":
                            $ctrls.val(value);
                            break;
                        case "radio":
                            if ($ctrls.length >= 1) {
                                $.each($ctrls, function () {
                                    var elemValue = $(this).attr("value");
                                    if (elemValue == value) {
                                        $(this).prop('checked', true);
                                    } else {
                                        $(this).prop('checked', false);
                                    }
                                });
                            }
                            break;
                        case "checkbox":
                            if ($ctrls.length > 1) {
                                $.each($ctrls, function () {
                                    if (typeof value == 'undefined' || value == null) {
                                        return;
                                    }
                                    var elemValue = $(this).attr("value");
                                    var elemValueInData = undefined;
                                    var singleVal;
                                    var values = value.toString().split(',');
                                    for (var i = 0; i < values.length; i++) {
                                        singleVal = values[i];
                                        if (singleVal == elemValue) {
                                            elemValueInData = singleVal
                                        }
                                    }
                                    if (elemValueInData) {
                                        $(this).prop('checked', true);
                                    } else {
                                        $(this).prop('checked', false);
                                    }
                                });
                            } else if ($ctrls.length == 1) {
                                if (value) {
                                    $ctrls.prop('checked', true);
                                }
                                else {
                                    $ctrls.prop('checked', false);
                                }
                            }
                            break;
                    }
                }
            });

            if (callback) {
                callback(data);
            }
        });
    };

    /**
     * select2 全局插件。
     * Server Return Class List<KeyValue>
     */
    $.fn.beeSelect = function () {
        var el = $(this);
        var url = $(this).data("url");
        if (url != undefined) {
            $.get(url, {}, function (data) {
                el.select2({
                    data: data,
                    placeholder: {
                        id: '-1', // the value of the option
                        text: '请选择..'
                    }
                });
            });
        } else {
            el.select2({
                placeholder: {
                    id: '-1', // the value of the option
                    text: '请选择..'
                }
            });
        }

    };
    

    jQuery.fn.dataTableExt.oSort['chinese-sort-asc']  = function(s1,s2) {  
        return s1.localeCompare(s2);  
    };  
    jQuery.fn.dataTableExt.oSort['chinese-sort-desc'] = function(s1,s2) {  
        return s2.localeCompare(s1);  
    };

    /**
     * radio remote  全局插件。
     * Server Return Class List<KeyValue>
     */
    $.fn.beeCheck = function () {
        $(this).each(function (i, el) {
            var url = $(el).data("url");
            var name = $(el).data("name");
            var type = "checkbox";
            if (url != undefined) {
                $.get(url, {}, function (data) {
                    $.each(data, function (i, item) {
                        var option = '<label class="mt-checkbox col-md-6">' +
                            '<input type="' + type + '" id="' + name + '_' + item.id + '" name="' + name + '" value="' + item.id + '">' +
                            item.text +
                            '<span></span>' +
                            '</label>';
                        $(el).append(option);
                    })
                });
            }
        });

    };

    $.fn.beeRadio = function () {
        $(this).each(function (i, el) {
            var url = $(el).data("url");
            var name = $(el).data("name");
            var type = "radio";
            if (url != undefined) {
                $.get(url, {}, function (data) {
                    $.each(data, function (i, item) {
                        var option = '<label class="mt-radio">' +
                            '<input type="' + type + '" name="' + name + '" value="' + item.id + '">' +
                            item.text +
                            '<span></span>' +
                            '</label>';
                        $(el).append(option);
                    })
                });
            }
        });
    };
    $.fn.beeSearchableMulti = function () {
        var el = $(this);
        el.multiSelect({
            selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder=''>",
            selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder=''>",
            afterInit: function (ms) {
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                    .on('keydown', function (e) {
                        if (e.which === 40) {
                            that.$selectableUl.focus();
                            return false;
                        }
                    });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                    .on('keydown', function (e) {
                        if (e.which == 40) {
                            that.$selectionUl.focus();
                            return false;
                        }
                    });
            },
            afterSelect: function () {
                this.qs1.cache();
                this.qs2.cache();
            },
            afterDeselect: function () {
                this.qs1.cache();
                this.qs2.cache();
            }
        });
    }

    /**
     * 以指定的Json数据，初始化JStree控件
     * treeName 树div Id
     * url 数据源地址
     * checkbox 是否显示复选框
     * loadedFunction 加载完毕的回调函数
     */

    $.fn.beeJsTree = function () {

        var el = $(this);
        var url = el.data("url");
        var isCheck = el.data("check") || false; //设置checkbox默认值为false
        if (isCheck) {
            //复选框树的初始化
            $.getJSON(url, function (data) {
                el.jstree({
                    'plugins': ["checkbox"], //出现选择框
                    'checkbox': {cascade: "", three_state: false}, //不级联
                    "types": {
                        "default": {
                            "icon": "fa fa-file-o"
                        },
                        "file": {
                            "icon": "fa fa-file-o"
                        }
                    },
                    'core': {
                        'data': data,
                        "themes": {
                            "responsive": false
                        }
                    }
                }).bind('loaded.jstree', loadedFunction(data));
            });
        } else {
            //普通树列表的初始化
            $.getJSON(url, function (data) {
                el.jstree({
                    'core': {
                        'data': data,
                        "types": {
                            "default": {
                                "icon": "fa fa-file-o"
                            },
                            "file": {
                                "icon": "fa fa-file-o"
                            }
                        },
                        "themes": {
                            "responsive": false
                        }
                    }
                }).bind('loaded.jstree', loadedFunction(data));
            });
        }

        function loadedFunction(data) {
            var callback = el.data("callback");
            if (callback) {
                if (callback.indexOf(')') != -1) {
                    eval(callback(data));
                } else {
                    eval(callback + "(data)");
                }

            }
        }
    }
}(jQuery));

// 对Date的扩展，将 Date 转化为指定格式的String
// 月(M)、日(d)、小时(h)、分(m)、秒(s)、季度(q) 可以用 1-2 个占位符，
// 年(y)可以用 1-4 个占位符，毫秒(S)只能用 1 个占位符(是 1-3 位的数字)
// 例子：
// (new Date()).Format("yyyy-MM-dd hh:mm:ss.S") ==> 2006-07-02 08:09:04.423
// (new Date()).Format("yyyy-M-d h:m:s.S")      ==> 2006-7-2 8:9:4.18
Date.prototype.Format = function (fmt) { //author: meizz
    var o = {
        "M+": this.getMonth() + 1, //月份
        "d+": this.getDate(), //日
        "h+": this.getHours(), //小时
        "m+": this.getMinutes(), //分
        "s+": this.getSeconds(), //秒
        "q+": Math.floor((this.getMonth() + 3) / 3), //季度
        "S": this.getMilliseconds() //毫秒
    };
    if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
    for (var k in o)
        if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
    return fmt;
};

**Comment by ssy341** [comment]
@heyapeng123  你开启了服务器模式，参考这个参数"serverSide": true,  开启意味你需要接受DT封装的排序参数，然后通过自己的处理，传入到sql语句中进行排序，把排序好的数据返回给DT即可
