### ISSUE TITLE
排序的问题

### ISSUE THREAD

**Issue by BlinkZF** [ssy341/datatables-cn#434]
嗯嗯 好的  非常感谢您上次给出的建议，
我这边还有一些问题  不知道为什么
1、我的排序按钮不能显示出来，
2、我每次通过input重新请求数据的时候，出来的数据还是上一次的页面。也就是说他不会自动跳到第一页~~~
下面是我的DT代码，我刚开始接触DT，有的地方不是很懂，感谢你的帮助
-->
![d4b370797ec8547d6981898ea50d2c36](https://user-images.githubusercontent.com/38147870/49257751-2dfdfc80-f46e-11e8-86b7-e3fc2178dba9.png)
![ed03c1d41171ee37b918803865c1f473](https://user-images.githubusercontent.com/38147870/49257757-32c2b080-f46e-11e8-840f-785512ca0d19.png)

**Comment by occultskyrong** [comment]
0、先阅读一遍 [中文网的FAQ](http://datatables.club/faqs/)吧。

先参见 [1.10.x与1.9.x参数名对照表](http://datatables.club/upgrade/1.10-convert.html)把参数使用同一版本的，建议使用1.10.x版本参数

1、排序按钮出不来的原因有很多，你先看下你的icon文件是否已加载，查看`Network`中是否所有资源已加载
2、分页相关，先查看`Network`中分页参数是否正确，再来判断具体问题。
#388
