### ISSUE TITLE
出现这种报错：DataTables warning (table id = 'dataTable1')：Cannot reinitialise DataTable.

### ISSUE THREAD

**Issue by Alreadgo** [ssy341/datatables-cn#435]
#### 页面js部分如下：
```
 $('.table').each(function() {
      console.log('当前id：' + this.id);
      $("#" + this.id).dataTable({
        "sPaginationType": "full_numbers",
        aoColumnDefs: [
          {
            bSortable: false,
            aTargets: [0, -1]
          }
        ]
      });
      return $(".table #checkAll").click(function() {
        if ($(".table #checkAll").is(":checked")) {
          return $(".table input[type=checkbox]").each(function() {
            return $(this).prop("checked", true);
          });
        } else {
          return $(".table input[type=checkbox]").each(function() {
            return $(this).prop("checked", false);
          });
        }
      });
    });
```

#### 使用假数据进行模拟时，没有报错，但是从后台数据库中获取数据时就出现如下错误
![image](https://user-images.githubusercontent.com/31053192/49347974-8129b680-f6dd-11e8-8aba-00d6b4649c4f.png)

请问这是什么原因造成的呢，出现图片中问题的原因是什么？

**Comment by occultskyrong** [comment]
送分题啊

> Cannot reinitialise DataTable
>
> 使用假数据进行模拟时，没有报错，但是从后台数据库中获取数据时就出现如下错误

这不已经说明你数据格式有问题了？？
看下Network里面返回的数据格式是否有问题。。。

具体关于`数据格式`的说明，参见[中文网的FAQ](http://datatables.club/faqs/)

> 6，控制台报错 `Cannot read property 'length' of null `或者 `Cannot read property 'length' of undefined` 是怎么回事
> 这个一般是返回的数据有问题，比如应该返回`{data:[……]}`而不是`{tabledata:[……]}`，或者数据为空因该返回`{data:[]}` 而不是`{data:null}`、`{data:""}`，dt识别不了所以报此错误 正确返回的数据格式为 `{data:[{name:"datatables中文网",url:"datatables.club"}]}`

**Comment by occultskyrong** [comment]
查看[DataTables中文网FAQ](http://datatables.club/faqs/)

> 4，弹出提示` Cannot reinitialise DataTable` 或者是 `Cannot destroy DataTable `是怎么回事
> 加上`retrieve:true` 和` destroy:true` 两个参数即可 另见： [retrieve](http://datatables.club/reference/option/retrieve.html) [destroy](http://datatables.club/reference/option/destroy.html) 参数具体含义
