### ISSUE TITLE
datatables居中对齐

### ISSUE THREAD

**Issue by heather9829** [ssy341/datatables-cn#44]
![image](https://cloud.githubusercontent.com/assets/17474887/20166589/cb93c2b2-a750-11e6-9003-11c5221322bb.png)
我希望数据就是默认的左对齐就好，但是不知道为什么每一页第九行都居中对齐了，这个是什么问题

**Comment by Smaillife** [comment]
你的CSS污染了DT的CSS，要么就是你的哪个JS插件影响了table表格

**Comment by ssy341** [comment]
@heather9829 建议你贴上代码更好，你右键审查元素看下，td有那些css，根据这个可以找出什么css影响到了
