### ISSUE TITLE
复杂的多表头和拖动列不兼容，能否解决

### ISSUE THREAD

**Issue by huangjiaxiang** [ssy341/datatables-cn#440]
![image](https://user-images.githubusercontent.com/30235850/49857571-daa48a80-fe2d-11e8-93a8-60e0112041ea.png)

**Comment by DD118** [comment]
我想问那个合并表头是怎么实现的呢？

**Comment by huangjiaxiang** [comment]
> 我想问那个合并表头是怎么实现的呢？

在html里面写的表头..后台渲染的

**Comment by FeliciaLFF** [comment]
@huangjiaxiang 你好，拖动列如何实现
