### ISSUE TITLE
如何动态更新DataTables的表头

### ISSUE THREAD

**Issue by Cherry860** [ssy341/datatables-cn#446]
如何动态更新DataTables的表头

**Comment by mrleolg** [comment]
按照Datatables 所需要的格式，动态拼装列，然后在datatables初始化的时候赋值即可。
如下格式 💯  :)
var columns = {
     {
          title:123,
         data: 'abc'
      }, {
          title:456,
          data: 'def'
      },
...
}
var data = {
     'abc': 123,
     'def': 456
}

var table = $("#table").DataTable({
            data: data,
            columns: columns
})

**Comment by occultskyrong** [comment]
#398
