### ISSUE TITLE
请问Datatable js官网的版权页面遮住问题

### ISSUE THREAD

**Issue by robinnpca** [ssy341/datatables-cn#449]
<
不知道是不是我找不到位置
在datatables.js的官网任何文件页面
https://datatables.net/account/
右下角都会有一个标签挡住
在查文件时都看不到下面文件的内容
请问这个要如何去除?
一直很困扰 我也有登入了 但是该标签还是在遮住视线
https://imgur.com/a/DVcxE66

**Comment by occultskyrong** [comment]
应该是浏览器的问题吧？

换用chrome浏览器试下？

[分析数据指标.xlsx](https://github.com/ssy341/datatables-cn/files/2772108/default.xlsx)

你所说的应该是footer部分的内容，不知道为什么fix导致盖住文档。
