### ISSUE TITLE
【BUG】【扩展插件】滚动渲染器2个BUG

### ISSUE THREAD

**Issue by 49839013** [ssy341/datatables-cn#450]
1.在官方的demo
https://datatables.net/extensions/scroller/examples/initialisation/large_js_source.html
 当中，使用鼠标滚轮，向下滑动，到了80行的时候，会出现空白页面，80以后的数据无法加载出来。
注：是使用鼠标的滚轮进行滑动。

2.拉动界面到任何一行，然后删除其中一行，滚动滑轮，也会出现下方空白数据，无法加载的情况。
下面是我做的一个demo.
1.使用鼠标拖动到中间任何一行
2.看到当前行数，输入到删除的数字框中（随意删除一行当前能看到的），点击删除
3.在表格中滚动鼠标，滚动向下，会出现空白没有加载数据

 
// 此处填写格式化代码
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<title></title>
		<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
		<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/scroller/1.5.1/js/dataTables.scroller.min.js"></script>

	</head>

	<body>
		<h2>删除行</h2>
		<input id="deindex" />
		<button onclick="onDelete()">删除</button>
		<br/><br/><br/><br/>
		<table id="example" class="display nowrap" style="width:100%">
			<thead>
				<tr>
					<th>ID</th>
					<th>First name</th>
					<th>Last name</th>
					<th>ZIP / Post code</th>
					<th>Country</th>
				</tr>
			</thead>
		</table>
		<script>
			$(document).ready(function() {
				var data = [];
				for(var i = 0; i < 50000; i++) {
					data.push([i, i, i, i, i]);
				}

				$('#example').DataTable({
					data: data,
					deferRender: true,
					scrollY: 200,
					scrollCollapse: true,
					scroller: true
				});
			});

			function onDelete() {
				$('#example').DataTable().row($("#deindex").val()).remove();

				//更新视图
				$('#example').dataTable().fnDraw(false);

			}
		</script>

	</body>

</html>

#### 5. 错误信息或截图
![image](https://user-images.githubusercontent.com/24695465/51314524-d9005f00-1a8a-11e9-86ee-10682b312d0c.png)

**Comment by 49839013** [comment]
说明一下
//更新视图
$('#example').dataTable().fnDraw(false);
是为了停留在当前位置

**Comment by ssy341** [comment]
因该是操作data，对data进行删除后，重新赋值data，然后再调用draw方法，重新绘制表格

**Comment by occultskyrong** [comment]
See https://github.com/rstudio/DT/issues/371

**Comment by 49839013** [comment]
> 因该是操作data，对data进行删除后，重新赋值data，然后再调用draw方法，重新绘制表格

你能再我的上面代码修改试试看嘛，无法满足当前需求，需要删除后依旧保持当前位置

**Comment by 49839013** [comment]
> See [rstudio/DT#371](https://github.com/rstudio/DT/issues/371)

首先感谢恢复，我看了一下，依旧无法解决我的需求，我需要再拖动时，更新/删除操作的同时，保持在当前位置，setTimeout(function() { table.draw(true); },无法解决我当前的问题
