### ISSUE TITLE
请问可以在从服务端获取数据之后判断serverside参数是传true还是false吗

### ISSUE THREAD

**Issue by L2shao** [ssy341/datatables-cn#455]
是这样的  现在目前项目有一个需求 
一万条数据以下  分页和排序操作在前端进行
一条数据以上   在后端进行分页  不需要进行排序操作

**Comment by occultskyrong** [comment]
`const LINES=10000; `

先通过 `fatch` 或 `ajax` 请求后端 /count 接口获取数据行数 `count`

声明 `option` ， 写入除`serverSide` 和 `data` 以外的其他配置信息

判断 `LINES` 与 `count` 值大小

`LINES >= count` 时，后端分页，`option`中 `serverSide` 设置为 `false`， `data` 中填入对应的数据请求接口地址及其他处理内容。

`LINES < count` 时，前端分页，再使用 `fatch` 或 `ajax` 请求后端接口，拿到数据填充到 `data`中。

构造实例 ` $('#myTable').DataTable(option);` 加载对应的 `option` 配置

**Comment by L2shao** [comment]
> `const LINES=10000; `
> 
> 先通过 `fatch` 或 `ajax` 请求后端 /count 接口获取数据行数 `count`
> 
> 声明 `option` ， 写入除`serverSide` 和 `data` 以外的其他配置信息
> 
> 判断 `LINES` 与 `count` 值大小
> 
> `LINES >= count` 时，后端分页，`option`中 `serverSide` 设置为 `false`， `data` 中填入对应的数据请求接口地址及其他处理内容。
> 
> `LINES < count` 时，前端分页，再使用 `fatch` 或 `ajax` 请求后端接口，拿到数据填充到 `data`中。
> 
> 构造实例 ` $('#myTable').DataTable(option);` 加载对应的 `option` 配置



谢谢老哥   我现在就是这种方式
第一次请求获取长度    长度超过一万   就传入ajax
不过问题就在于需要请求两次
现在后端没有开放单独查询长度的接口
我查询长度也是用的当前数据查询接口   如果数据量太大    两次请求时间就会很长
