### ISSUE TITLE
能否为导出excel的按钮指定数据源

### ISSUE THREAD

**Issue by s209392599** [ssy341/datatables-cn#458]
extend: 'excelHtml5',  能否为导出excel的按钮指定数据源
我这边的是后台纯分页，只有点击下一页，下一页的数据才能加载，
现在的问题是，点击导出按钮，要把全部表格数据打印出来，所以需要重新设定数据源，是否能做到？

**Comment by occultskyrong** [comment]
https://github.com/ssy341/datatables-cn/issues/6#issuecomment-449798500
