### ISSUE TITLE
通过什么API动态设置表格的列名称？

### ISSUE THREAD

**Issue by ILoveMyJay** [ssy341/datatables-cn#46]
因为要根据不同的查询条件更换列名，使用jQuery动态设置表格title后，导出的csv还是修改之前的标题

**Comment by ssy341** [comment]
@ILoveMyJay 你是怎么更改列名的呢？把代码贴出来

**Comment by ILoveMyJay** [comment]
<th class="displayTh">展示数</th>

if( $('#adType').val()=="video"){
        $(".displayTh").html("展示完成数");
    }else{
     $(".displayTh").html("展示数");
 }

用jquery改的，改完并reload之后虽然页面显示变了，但导出的title还是之前的。
我试了一下，不用reload或者load，我把datable destroy掉再重新init导出的title就正确了


2016-11-11 19:03 GMT+08:00 Keith <notifications@github.com>:

**Comment by ssy341** [comment]
@ILoveMyJay 明白了，不能直接用jQuery去修改dom的内容，因为dt有内部数据，dom只是展示的，他内部处理的时候获取的是内部对象，所以你修改没有效果，我帮你查询了下，没有api去修改标题的，但是你可以参考如下代码，看能不能类似的改变：
```javascript
//初始化表格
var oTable = $("#example").DataTable({
    ajax: {
        url: "dataList.action",
        data: {
            args1: "我是固定传参的值，在服务器接收参数[args1]"
        }
    }
});
 
//当你需要多条件查询，你可以调用此方法，动态修改参数传给服务器
function reloadTable() {
    var name = $("#seName").val();
    var admin = $("#seAdmin").val();
    var param = {
        "obj.name": name,
        "obj.admin": admin
    };
    oTable.settings()[0].ajax.data = param;
    oTable.ajax.reload();
}
```
这个是动态修改参数，关键在于 `  oTable.settings()[0] ` 

[怎么获取列标题](https://datatables.net/reference/api/column().header())

**Comment by ILoveMyJay** [comment]
我试了下， var idx = table.cell( this ).index().column;
    var title = table.column( idx ).header();
可以获取header，但不能赋值。还是destroy后再重新datatable才行。


条件查询大多都是GET请求，我一般都把参数拼到url里了。比如点击submit后，按条件查询，类似这种：
$('#submit').on('click',function(){
      var text=[];
        $(".search-input").each(function() {
            if ($(this).val()){
                text.push($(this).attr("id") +"="+ $(this).val());
            }
        });
        data_table.ajax.url( searchUrl +"?"+text.join("&")).load();
})

谢谢你这么及时的回答问题😁



在 2016年11月14日 上午10:33，Keith <notifications@github.com>写道：

**Comment by ssy341** [comment]
@ILoveMyJay destroy后可以是肯定的，已经是另一个表格了，这个没有疑问，期待其他小伙伴的回答吧
