### ISSUE TITLE
datatables 能做纵向列表吗？

### ISSUE THREAD

**Issue by China-KJQ** [ssy341/datatables-cn#461]
最近在做一个用户留存表附带查询、分页等功能，第一时间想到了用datatables来做，不过查了很久的资料没有思路了。。。。

**Comment by ssy341** [comment]
有截图么？什么叫纵向列表？@China-KJQ

**Comment by China-KJQ** [comment]
就是这种的图表，目前用jquery.easyui.min.js实现了
