### ISSUE TITLE
控制台报错.

### ISSUE THREAD

**Issue by MingLiuHN** [ssy341/datatables-cn#468]
已经引入jquery/DataTables CSS/DataTables.js但是控制台还是报错!
![image](https://user-images.githubusercontent.com/34367398/58394169-79d3dc00-8074-11e9-9dfe-a65b6523eddc.png)

**Comment by occultskyrong** [comment]
怎么引入的，源代码贴一下，创建Issue时候的信息，填完整。

**Comment by occultskyrong** [comment]
#### 1. 使用DataTables的源（CDN地址、本地源文件）

#### 2. DataTables的版本

#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）

#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图

#### 6. 其他你认为可以帮助解决问题的信息

**Comment by MingLiuHN** [comment]
不好意思,已解决.原因是表头有<th></th>列,但是表中没有列.
