### ISSUE TITLE
DataTables-1.10.12版本fnUpdate怎么使用？

### ISSUE THREAD

**Issue by wenbindf** [ssy341/datatables-cn#47]
我更换了DataTables-1.10.12 这个版本之后，fnUpdate函数失效了，之前是使用dataTable 初始化的，新版本使用的是DataTable初始化，怎么来调用fnUpdate？

**Comment by ssy341** [comment]
fnUpdate 在1.10版之后 改为 [row().data()](https://datatables.net/reference/api/row().data())  [cell().data()](https://datatables.net/reference/api/cell().data())
