### ISSUE TITLE
dataTables 设置复杂表头，使用下载表格功能，无法正常显示所设置的表格

### ISSUE THREAD

**Issue by killuam** [ssy341/datatables-cn#471]
<table border="" id="compTable">
            <thead>
                <tr>
                    <th rowspan="2">分类</th>
                    <th colspan="2">类别1</th>
                    <th colspan="2">类别2</th>
                    <th colspan="2">类别3</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>1</th>
                    <th>2</th>
                    <th>2</th>
                    <th>3</th>
                    <th>3</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

#### 1. 使用DataTables的源（CDN地址、本地源文件）
//cdn.datatables.net/1.10.0/css/jquery.dataTables.min.css
//cdn.datatables.net/1.10.0/css/jquery.dataTables.min.css
#### 2. DataTables的版本
1.10.0
#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）
JQuery
#### 4. 使用DataTables的配置信息
```
<table border="" id="compTable">
            <thead>
                <tr>
                    <th rowspan="2">分类</th>
                    <th colspan="2">类别1</th>
                    <th colspan="2">类别2</th>
                    <th colspan="2">类别3</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>1</th>
                    <th>2</th>
                    <th>2</th>
                    <th>3</th>
                    <th>3</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
$('#compTable').DataTable({
                    "orderCellsTop": true,
                    paging: false,
                    dom: 'Bfrtip',
                    ordering: false,
                    buttons: [
                        {
                            text:'Save',//按钮上显示的文字
                            title:"test",//给创建文件的文件名
                            extension:'.xlsx',//给创建文件的文件名后缀
                            extend: 'excelHtml5',
                            customize: function( xlsx ) {
                                var sheet = xlsx.xl.worksheets['sheet1.xml'];
                            }
                        }
                    ]
                });

```
#### 5. 错误信息或截图
设置了复杂表头 运用内置的表格下载功能 点击下载表格 无法正常完整显示复杂表头的内容，只能显示第二行的内容

**Comment by tianfengjie** [comment]
老哥解决了这个问题没有啊？ 我也遇到这个问题了  我看导出的exportOptions--format--header就只有下面那一行 找不到上面第一行表头。求分享解决办法
