### ISSUE TITLE
Datables 如何对后端传过来的HTML元素进行转义 比如 数据中有XSS脚本

### ISSUE THREAD

**Issue by python-ljn** [ssy341/datatables-cn#479]
### Datatable后端传过来的数据如果有XSS脚本 怎么解决 求大佬帮忙
比如 <img src="#">会显示图片

**Comment by hexsean** [comment]
我刚想问和你一样的问题,允许存,但是让显示转义

**Comment by python-ljn** [comment]
> 我刚想问和你一样的问题,允许存,但是让显示转义

你好  加我  联系 微信或者QQ1342278185    我不知道你是否和我的问题一样  我的问题有了解决的办法了

**Comment by snailsmail** [comment]
请问下你的解决办法是什么,可以分享吗 @StanleyLe

**Comment by python-ljn** [comment]
> 请问下你的解决办法是什么,可以分享吗 @StanleyLe

在datatable渲染的时候进行转义  你可以加我联系详细咨询1342278185

**Comment by hexsean** [comment]
没有,最后因为时间问题我还是在后台进行了过滤,前端没有处理数据




------------------ 原始邮件 ------------------
发件人: "snailsmail"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 下午3:26
收件人: "ssy341/datatables-cn"<datatables-cn@noreply.github.com>;
抄送: "我知道"<1286848541@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ssy341/datatables-cn] Datables 如何对后端传过来的HTML元素进行转义 比如 数据中有XSS脚本 (#479)




请问下你的解决办法是什么,可以分享吗
