### ISSUE TITLE
total取值

### ISSUE THREAD

**Issue by s209392599** [ssy341/datatables-cn#481]
![image](https://user-images.githubusercontent.com/30439969/61357655-414dc300-a8ab-11e9-9160-775fb174770e.png)
···
i.children().append(a.oLanguage.sLengthMenu.replace("_MENU_", e[0].outerHTML));
···
上面进行_MENU_替换的时候能不能在这个元素后面加一个共多少条记录，项目中改dom的配置太慢，几千个表格

**Comment by s209392599** [comment]
function ob(a) {
    	var numLen = a.json.data.length;

**Comment by occultskyrong** [comment]
参考 

> https://datatables.net/reference/option/language

`lengthMenu`/`info` 应该能解决，不需要用replace，直接替换通用的`language`配置即可
