### ISSUE TITLE
datatables可以不以表格形式显示列表吗

### ISSUE THREAD

**Issue by lvjw1991** [ssy341/datatables-cn#489]
#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）
java
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图
类似这样
![图片](https://user-images.githubusercontent.com/29093438/63761269-6d6d5280-c8f3-11e9-88d2-2ef8b33e256f.png)

**Comment by occultskyrong** [comment]
可以认为这也是一种表格，只不过样式需要调整下。
你用`DataTables`写比较麻烦，还不如自己用 `<li>` 自己拼接html。

***

用 DataTables 也可以实现，只不过css要把对应的单元格的border自己去掉。
然后在col的render里面把多个数据组装起来。

参考 

> https://datatables.net/reference/option/columns.render

`columns.render` 支持富文本的方式去拼接 col里面的内容。
所以你可以把 你的主要内容当成3列qu去处理
![image](https://user-images.githubusercontent.com/8370006/63772252-4b7fca00-c90b-11e9-8ec4-2264f43d2443.png)

***

用DataTables的好处是简单，但是需要自己写col里面的内容
自己用li的坏处就是你需要自己写`paginator`

**Comment by lvjw1991** [comment]
> 
> 
> 可以认为这也是一种表格，只不过样式需要调整下。
> 你用`DataTables`写比较麻烦，还不如自己用 `<li>` 自己拼接html。
> 
> 用 DataTables 也可以实现，只不过css要把对应的单元格的border自己去掉。
> 然后在col的render里面把多个数据组装起来。
> 
> 参考
> 
> > https://datatables.net/reference/option/columns.render
> 
> `columns.render` 支持富文本的方式去拼接 col里面的内容。
> 所以你可以把 你的主要内容当成3列qu去处理
> ![image](https://user-images.githubusercontent.com/8370006/63772252-4b7fca00-c90b-11e9-8ec4-2264f43d2443.png)
> 
> 用DataTables的好处是简单，但是需要自己写col里面的内容
> 自己用li的坏处就是你需要自己写`paginator`

谢谢大神
