### ISSUE TITLE
dataTables之前还可以用，我也没改代码突然就报错了

### ISSUE THREAD

**Issue by zhubin1992** [ssy341/datatables-cn#49]
dataTables.editor.min.js:651 报错
Uncaught TypeError: Cannot set property 'dom' of undefined

**Comment by ssy341** [comment]
@zhubin1992 贴上你的初始化代码

**Comment by zhubin1992** [comment]
是加载dataTables.editor.min.js的时候就报错了，是因为试用期到了吗。。有免费的吗

**Comment by ssy341** [comment]
@zhubin1992 你得贴上代码哦？editor插件，DataTables中文网不提供免费的
