### ISSUE TITLE
jquery datatable 行列转置

### ISSUE THREAD

**Issue by yellowYiFeng** [ssy341/datatables-cn#490]
<table id="table_id" class="display">
            <thead>
                <tr>
                    <th>th1</th>
                    <th>th2</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>11</td>
                    <td>12</td>
                </tr>
                <tr>
                    <td>21</td>
                    <td>22</td>
                </tr>
            </tbody>
        </table>

jquery datatable 如何设置能够将行列转置  网上查都是c#的方法，有没有js或者jquery的方法

**Comment by occultskyrong** [comment]
参考下这个？

> https://stackoverflow.com/questions/53441755/how-to-transpose-rows-and-columns-in-datatable-js

> https://www.jqueryscript.net/table/Transpose-Table-jQuery-Plugin.html

**Comment by yellowYiFeng** [comment]
> 参考下这个？
> 
> > https://stackoverflow.com/questions/53441755/how-to-transpose-rows-and-columns-in-datatable-js
> 
> > https://www.jqueryscript.net/table/Transpose-Table-jQuery-Plugin.html

解决了，非常感谢
