### ISSUE TITLE
请问下这个数据格式如何加载到表格中

### ISSUE THREAD

**Issue by cnweng** [ssy341/datatables-cn#492]
[
{deviceid='92', devicename='北路南口', DeviceType='交通', DeviceModel='左/直', DeviceAttribute='1',  ServiceDate='20190427', Longitude='121.688336081614', Dimension='29.9630513657787', RelayStau='0'}, 
{deviceid='93', devicename='金丰路东口',  DeviceType='交通', DeviceModel='左/直', DeviceAttribute='1',  ServiceDate='20190427', Longitude='121.664088574075', Dimension='29.9508880719741', RelayStau='0'}, 
{deviceid='94', devicename='镇骆东路西口', DeviceType='交通', DeviceModel='左/直', DeviceAttribute='1',  ServiceDate='20190427', Longitude='121.669769139349', Dimension='29.9551323630162', RelayStau='0'}, 
{deviceid='95', devicename='南二路南口', DeviceType='交通', DeviceModel='左/直', DeviceAttribute='1',  ServiceDate='20190427', Longitude='121.598502977071', Dimension='29.9770801858234', RelayStau='0'}, 
{deviceid='96', devicename='金华北路东口', DeviceType='交通', DeviceModel='左/直', DeviceAttribute='1',  ServiceDate='20190427', Longitude='121.594552979875', Dimension='29.9692554515641', RelayStau='0'}, 
{deviceid='97', devicename='镇海大道北口', DeviceType='交通', DeviceModel='左/直', DeviceAttribute='1', ServiceDate='20190427', Longitude='121.598229214889', Dimension='29.9696619813367', RelayStau='0'}
]
后台返回的数据是这样一个数组，请问如何导入到表格中，我查了下官方的例子没这种格式。

**Comment by occultskyrong** [comment]
方便说下后端的开发语言么？
***
第一次看到这种数据结构。

本身`DataTables`是前端基于JavaScript的工具，所以对`JSON`的支持比较美好，建议还是转为`json`格式来处理。

***
最简单的，用 `String.replace` 将 `=` 替换为 `:` ，然后用 `JSON.parse`格式化为标准的json格式

> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
