### ISSUE TITLE
DataTables前端post请求提交ajax，后端无法获取的问题

### ISSUE THREAD

**Issue by xysfycy** [ssy341/datatables-cn#493]
#### 1. 使用DataTables的源（CDN地址、本地源文件）
https://github.com/puikinsh/gentelella   用的这个框架里的DataTables
#### 2. DataTables的版本
DataTables 1.10.12
#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）
java
#### 4. 使用DataTables的配置信息
function creatTable(DTname, url) {
			    //将创建的表格存放到tables变量中
			    var tables = $(DTname).DataTable({
			        //控制分页、搜索、每页显示数量、显示信息等四个插件的dom
			 
			        //数据传入
			        "ajax" : {
						"url"   		: url,
			            "type" 			: "POST",
    					"dataType"		: "json",
			            "contentType"	: "application/json; charset=UTF-8",
			            "data"	  		: JSON.stringify({
					    	"customer_name" 	: $('#customerName').val() == "" ? null : $('#customerName').val(),
							"dealerID"			: $('#distributor').val() == "" ? null : $('#distributor').val(),
							"bus_opp_name"  	: $('#busOppName').val() == "" ? null : $('#busOppName').val(),
							"bus_opp_code"		: $('#busOppCode').val() == "" ? null : $('#busOppCode').val(),
							"reporter" 			: $('#reporter').val() == "" ? null : $('#reporter').val(),
							"bus_opp_status"	: $('#busOppState').val() == "" ? null : $('#busOppState').val()
						})
			        },

			        "lengthMenu": [10, 20, 30],
			        //允许重建
			        "destroy": true,
			        //自定义列宽
			        "bAutoWidth": false, 
			        "dom": "Blfrtip",
					"buttons": [
						{
						  "extend": "copy",
						  "className": "btn-sm"
						},
						{
						  "extend": "csv",
						  "className": "btn-sm"
						},
						{
						  "extend": "excel",
						  "className": "btn-sm"
						},
						{
						  "extend": "print",
						  "className": "btn-sm"
						},
					],
					"responsive": true,
			        //设置兼容空值
			        "columnDefs": [
						{
							"defaultContent": "",
							"targets": "_all"
						}
					],
			        //设置列数据
			        "columns": [
			            {
			                "data": "customer_name",
			                "title": "客户名称",
			                "width":"80px",
			            },
			            {
			                "data": "industry",
			                "title": "所属行业",
			                "width":"80px",
			            },
			            {
			                "data": "dealerID",
			                "title": "所属经销商",
			                "width":"80px",
			            },
			            {
			                "data": "bus_opp_name",
			                "title": "商机名称",
			                "width":"200px",
			            },
			            {
			                "data": "reporter",
			                "title": "报备人",
			                "width":"80px",
			            }, 
			            {
			                "data": "auditor",
			                "title": "审核人",
			                "width":"80px",
			            }, 
			            {
			                "data": "reviewer",
			                "title": "复核人",
			                "width":"80px",
			            }, 
			            {
			                "data": "bus_opp_status",
			                "title": "商机状态",
			                "width":"80px",
			                "render": function (data, type, row) {
			                    switch (data) {
			                        case "0":
			                            return "未审核";
			                            break;
			                        case "1":
			                            return "审核不通过";
			                            break;
			                        case "2":
			                            return "审核通过";
			                            break;
			                        case "3":
			                            return "已驳回";
			                            break;
			                        case "4":
			                            return "已同意";
			                            break;
			                        case "5":
			                            return "已分派";
			                            break;
			                        case "6":
			                            return "未成单";
			                            break;
			                        case "7":
			                            return "签约订单";
			                            break;
			                    }
			 
			                }
						},
			        ],
			        //设置排序
			        "order": [[1, 'asc']],
			        language: {  
			        	//将英文转换为中文
			        	"sProcessing": "处理中...",
			        	"sLengthMenu": "显示 _MENU_ 项结果",
			        	"sZeroRecords": "没有匹配结果",
			        	"sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
			        	"sInfoFiltered": "(由 _MAX_ 项结果过滤)",
			        	"sInfoPostFix": "",  
			        	"sSearch": "搜索:",  
			        	"sUrl": "",
			        	"sEmptyTable": "表中数据为空",
			        	"sLoadingRecords": "载入中...",
			        	"sInfoThousands": ",",  
			        	"oPaginate": { 
			        		"sFirst": "首页", 
			        		"sPrevious": "上页",
			        		"sNext": "下页", 
			        		"sLast": "末页"
			        		},  
			        	"oAria": {  
			        		"sSortAscending": ": 以升序排列此列", 
			        		"sSortDescending": ": 以降序排列此列"
			        		} 
			        	}
			    });
			}
```
// 此处填写格式化代码

```
	@RequestMapping(value = "/selectBusOpp", method = RequestMethod.POST)
	@ResponseBody
	public List<BusOpp> selectBusOpp(@RequestBody Map<String, Object> bus_opp_map) {
		return busOppService.selectBusOpp(bus_opp_map);
	}	

#### 5. 错误信息或截图
报错400
POST http://localhost:8080/ChenLongCloud/selectBusOpp.do 400 ()
#### 6. 其他你认为可以帮助解决问题的信息
后台接收方式换了单个参数，实体，map等多种接收方式，都无法实现

**Comment by occultskyrong** [comment]
DataTables本身作为一个前端表格化工具，本身的request是由ajax方式实现的。
***
你先使用 `postman` 来确保你的接口是可以访问的，再来查看是否是DataTables导致了前端不可用。
***
400报错多数是由后端的路由解析出错引起的，先排查后端逻辑吧

**Comment by xysfycy** [comment]
后端代码我也附上了，还试过单个参数接收，和用实体接收，都是报400，所以才想问问看是否是前端ajax的参数写法有问题

**Comment by occultskyrong** [comment]
你用 `postman` 请求的结果也是400？
如果是400，那这个肯定跟前端没啥关系。
如果不是，浏览器打开开发者调试工具 切换到network的tab，可以看到所有前端发送的请求，查看下DataTables发送的请求里面的params

**Comment by xysfycy** [comment]
我最开始用的是
`"ajax" : {
						"url"   		: "selectBusOpp.do",
			            "type" 			: "POST",
    					"dataType"		: "json",
			            "contentType"	: "application/json; charset=UTF-8",
			            "data"	  		: JSON.stringify(data)
			        },`
报错400，我改成
`"ajax":function(data, callback, settings){
						$.ajax({
							cache 			: true,
							async 			: true,
							url   			: "selectBusOpp.do",
				            type  			: "POST",
	    					dataType		: "json",
				            contentType		: "application/json; charset=UTF-8",
				            data	  		: JSON.stringify(data),
				            success: function (result) {
		                        if (result.errorCode) {
		                            alert("查询失败。错误码：" + result.errorCode);
		                            return;
		                        }
		                        callback(result);
		                    },
		                    error: function (XMLHttpRequest, textStatus, errorThrown) {
		                        alert("查询失败");
		                    }
						});
					},`
请求成功了，但是callback（result）不能显示到表格，报Uncaught TypeError: Cannot read property 'length' of undefined。所以应该不是后端的问题，但是前端的配置不知道该如何改

**Comment by Neumann97** [comment]
兄嘚，换下get传，或许就ok了
