### ISSUE TITLE
FQ看这里，输入我的邀请码 LKWP6W 额外获得三个月的蓝灯专业版

### ISSUE THREAD

**Issue by ssy341** [ssy341/datatables-cn#5]
# 输入我的邀请码 LKWP6W 额外获得三个月的蓝灯专业版
## 人人可享的开放网络

Lantern是一个免费的应用程序。它能帮助你随时随地快速、可靠、安全地访问互联网。
### Lantern 是如何工作的？

Lantern 是一个互联网代理工具。它能帮助你访问被封锁的网站。

[蓝灯免墙下载地址](https://github.com/getlantern/lantern)

[常见问题](https://getlantern.org/faq/index.html)

**Comment by occultskyrong** [comment]
哈哈，我又来捣乱了，几个性价比不错的vps，自己搭个shadowsocks，0.0.0
https://lowendbox.com/blog/hostus-openvz-vps-plans-starting-at-12year-in-us-eu-and-asia/

**Comment by ssy341** [comment]
@occultskyrong 可以翻墙，管他什么办法，只要好用就行了，谢谢分享

**Comment by Lucky-dj** [comment]
哈哈哈哈，我来磳免费的

**Comment by ssy341** [comment]
[老司机带你科学上网](http://www.laosijivpn.com/)
