### ISSUE TITLE
datatables 表格中添加colspan 就会弹出报错，请问怎么解决？

### ISSUE THREAD

**Issue by Lx2219** [ssy341/datatables-cn#504]
datatables 表格中添加colspan 就会弹出下面的报错，怎么才能加上colspan 不报错？

DataTables warning: table id=DataTables_Table_0 - Requested unknown parameter '1' for row 13. For more information about this error, please see http://datatables.net/tn/4

**Comment by yixuan-bb** [comment]
[日本藤素](http://www.yegogo.com/goods.php?id=4)
[陰莖增大](http://www.yegogo.com/goods.php?id=30)
[犀利士藥局](http://www.yegogo.com/goods.php?id=19)
[美國黑金](http://www.yegogo.com/goods.php?id=5)
[必利勁](http://www.yegogo.com/goods.php?id=27)
[持久液](http://www.yegogo.com)

**Comment by bbjsor** [comment]
Try this:
There is a colspan or rowspan in the tbody of the table, which is not supported by DataTables.
Using columns or columnDefs you have specified more columns than there are in the HTML

**Comment by ssy341** [comment]
@Lx2219 你可以再进一步提供下你的代码还有什么需求要使用colspan
