### ISSUE TITLE
有2000多条数据客户端分页的时候，左下角信息中出现了undefined。。。

### ISSUE THREAD

**Issue by ledel037** [ssy341/datatables-cn#505]
#### 1. 使用DataTables的源（CDN地址、本地源文件）
本地
#### 2. DataTables的版本
1.10.15
#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）
java
#### 4. 使用DataTables的配置信息
 $('#branchdetail').DataTable({
            "order": [
                [0, "desc"]
            ],
            "columnDefs": [{
                "targets": [4],
                "searchable": false
            },
            {
                "targets": [4],
                "type": "html-num"
            }],
            "info": false
        });
```
// 此处填写格式化代码

```

#### 5. 错误信息或截图
有2000多条数据客户端分页的时候，左下角信息中出现了undefined。。。
![image](https://user-images.githubusercontent.com/49937123/67170904-16619680-f3e7-11e9-8fcc-8eec737508a8.png)

![image](https://user-images.githubusercontent.com/49937123/67170924-38f3af80-f3e7-11e9-909a-3da89bb773e3.png)

**Comment by Neumann97** [comment]
应该是language配置中出了问题
