### ISSUE TITLE
table.row(tr).data()为undefined

### ISSUE THREAD

**Issue by jianghong3** [ssy341/datatables-cn#509]
#### 1. 使用DataTables的源（CDN地址、本地源文件）
本地文件
#### 2. DataTables的版本
DataTables 1.10.18
#### 3. 开发语言、框架（Java/NodeJs/PHP、Vue/Ng2/React/JQuery）
Python  JQuery
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

#### 5. 错误信息或截图
打印table.row(tr).data()为undefined

#### 6. 其他你认为可以帮助解决问题的信息

**Comment by yixuan-bb** [comment]
[url=http://www.yegogo.com/goods.php?id=4]藤素[/url]，
[url=http://www.yegogo.com/goods.php?id=5]美國黑金[/url]，
[url=http://www.yegogo.com/goods.php?id=54]雙效威而鋼 [/url]，
[url=http://www.yegogo.com/]持久液[/url]，
[url=http://www.yegogo.com/goods.php?id=27]必利勁[/url]，
[url=http://www.yegogo.com/goods.php?id=38]2h2d金尊版[/url]，

**Comment by yixuan-bb** [comment]
[日本藤素](http://www.yegogo.com/goods.php?id=4)
[陰莖增大](http://www.yegogo.com/goods.php?id=30)
[犀利士藥局](http://www.yegogo.com/goods.php?id=19)
[美國黑金](http://www.yegogo.com/goods.php?id=5)
[必利勁](http://www.yegogo.com/goods.php?id=27)
[持久液](http://www.yegogo.com)
