### ISSUE TITLE
很抱歉的通知大家，此项目已暂停维护（继续维护更新时间2020年5月31日）

### ISSUE THREAD

**Issue by occultskyrong** [ssy341/datatables-cn#512]
首先感谢大家能够选择 `ssy341` 的这个项目 `datatables-cn` 来反馈、询问问题。

但牵涉到某些个人工作原因，原作者 `ssy341` 在短期内无法继续维护此项目，亦无法继续解决 `Issue`内的问题。
我个人`occultskyrong` 因个人精力主要处理`NodeJS`后端业务，也没太有经验来实操`DT`项目，有些`Issue`不实操的情况下，很难去把控和找到出现这个问题的原因。

故，很抱歉的通知大家，此项目及`Issue`板块，即日起，（341和我）已暂停维护。

`Issue`内亦有其他小伙伴，帮助大家在解决问题，如果任何人有兴趣 想要参与此项目`Issue`的维护，可以在本`Issue`留言，并`at我`，我尽可能来给予权限的帮助。

再次，抱歉。

***

勿忘初心，方得始终。

望大家在`code`的世界里寻找自己的兴趣。

**Comment by zzwT1** [comment]
好 牛！！！

**Comment by jiazehua** [comment]
帮助很大 谢谢长久的付出

**Comment by OldSevenQ** [comment]
谢谢你们的付出，帮助很大

**Comment by etyero** [comment]
感谢大佬们的分享！

**Comment by Jean-Jacques-Nuoan** [comment]
感谢，另外问下群现在还能加么，我申请了好几遍都没有回复

**Comment by occultskyrong** [comment]
> 感谢，另外问下群现在还能加么，我申请了好几遍都没有回复

341应该没时间看群申请。
那个群也很久没人发信息了。

**Comment by little-leaf-oops** [comment]
刚刚来到这个地方  然后就停止维护了......

**Comment by chrisxxp** [comment]
刚来

**Comment by ssy341** [comment]
如果github上回复不及时，还可以加入到QQ群里：20779435

**Comment by ssy341** [comment]
@occultskyrong 在这里感谢你一直以来的付出，相信你在以后的路上也会越走越好，再次感谢！！
