### ISSUE TITLE
两列数据进行比较，大的字显示红色，小的字显示蓝色

### ISSUE THREAD

**Issue by xxssjj119922** [ssy341/datatables-cn#519]
```
            姓名              A        B
1          小张             10       12
2          小王             13        5
3          小红              5         5
```
我希望A列第一行显示蓝色，A列第二行显示红色，代码该怎么写，在这感谢大神回复了

**Comment by ssy341** [comment]
@xxssjj119922 这里我理解的意思是A列根据不同的值显示不同的颜色，也就是A列的单元格的背景颜色或者字体颜色不一样，你可以使用`createdCell`来处理，详细参考：http://datatables.club/reference/option/columns.createdCell
```javascript
$('#example').DataTable( {
   "columnDefs": [ {
       "targets": 3,
       "createdCell": function (td, cellData, rowData, row, col) {
         //自己定义一个区间，值在某个区间用什么颜色
         if ( cellData < 1 ) {
           $(td).css('color', 'red')
         }
       }
     } ]
} );
```

**Comment by xxssjj119922** [comment]
感谢，我用columns解决了这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Keith <notifications@github.com&gt;
发送时间: 2020年8月31日 15:50
收件人: ssy341/datatables-cn <datatables-cn@noreply.github.com&gt;
抄送: xxssjj119922 <xxssjj119922@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[ssy341/datatables-cn] 两列数据进行比较，大的字显示红色，小的字显示蓝色 (#519)





 
@xxssjj119922 这里我理解的意思是A列根据不同的值显示不同的颜色，也就是A列的单元格的背景颜色或者字体颜色不一样，你可以使用createdCell来处理，详细参考：http://datatables.club/reference/option/columns.createdCell
 $('#example').DataTable( {    "columnDefs": [ {        "targets": 3,        "createdCell": function (td, cellData, rowData, row, col) {          //自己定义一个区间，值在某个区间用什么颜色          if ( cellData < 1 ) {            $(td).css('color', 'red')          }        }      } ] } );
