### ISSUE TITLE
服务器分页模式

### ISSUE THREAD

**Issue by z65877424** [ssy341/datatables-cn#52]
我用服务器分页模式，但返回的json比较复杂，只有其中一个节点是符合datatables格式的，我该用什么方法解决。

**Comment by ssy341** [comment]
@z65877424 [option ajax dataSrc （下） 对返回数据进行处理](http://datatables.club/manual/daily/2016/04/20/option-ajax-dataSrc2.html)

**Comment by zhouzxiang** [comment]
@ssy341 打扰啦，这样确实可以获取到正确的data部分数据，但是采用服务端分页的时候，"draw"，"recordsTotal"，"recordsFiltered"等信息没法获取到，我F12调试发现分页的参数还是从ajax返回的数据中直接json[draw]，而不是在dataSrc 返回的数据中获取，请问这种情况如何解决呢？谢谢！

**Comment by ssy341** [comment]
@zhouzxiang 因为DataTables要求服务器模式返回的数据有draw, recordsTotal 和recordsFiltered必须是以下这种格式：
```javascript

{
draw:1,
recordsTotal:50,
recordsFiltered:50,
......
}
```
也就是说必须是顶级，如果你服务器返回的格式不是这样，那么你在指定data的数据之后，还需要把这三个参数重新指定下，如下所示：
```javascript
dataSrc: function(json){
   json.draw = json.data.draw;
   json.recordsTotal = json.data.recordsTotal;
   json.recordsFiltered = json.data.recordsFiltered;

   return json.data.data;
}
```
参考 [自定义返回数据的格式](https://stackoverflow.com/questions/32941913/custom-data-source-property-datasrc-and-pagination-issue)

**Comment by zhouzxiang** [comment]
@ssy341 谢谢，已经得到解决！更新到ajax.dataSrc让后面的童鞋少走弯路！
