### ISSUE TITLE
請問如何載入多個Datatables的資料，以另一檔顯示？

### ISSUE THREAD

**Issue by nelsonip** [ssy341/datatables-cn#533]
問題描述： 有3個html，各自有一個 JQuery Datatables，格式相同，資料數量不同。現在想用第4 個html檔顯示前3個的資料合併。即是若果A、B、C檔 各有十行DATA，現在想用D檔顯示晒30行資料！
    
使用CDN地址，jquery-1.11.3， DataTables 1.10.23， 只用 HTML，CSS，JS，JQuery 沒用其它技術。

可以提供完整例子供下載體驗嗎？

**Comment by ssy341** [comment]
@nelsonip 思路是获取这三个表格的data，合并为一个data，获取表格数据使用api[data()](https://datatables.net/reference/api/data()),然后直接赋值到第四个表格的[data](https://datatables.net/reference/option/data)属性
