### ISSUE TITLE
点击下一页，请求数据正常，但页标和页面数据不切换，左上角一直显示处理中...

### ISSUE THREAD

**Issue by ufowwe** [ssy341/datatables-cn#54]
大家有遇到这种情况吗，本地没问题，发布到测试环境所有表格就都这样

**Comment by ssy341** [comment]
@ufowwe 这个你得提供你的代码还有你发送请求后的返回数据，根据你的描述，问题应该是返回的数据是有问题才会出现一直加载等待这种情况，你仔细看看浏览器的控制台
