### ISSUE TITLE
Buttons官网下载的示例不能显示按钮？？

### ISSUE THREAD

**Issue by Liyf160823** [ssy341/datatables-cn#55]
下载的DataTables-1.10.12新包，进入DataTables-1.10.12\extensions\Buttons\examples目录，以Google Chrome或firefox打开示例，都显示不了按钮，这是怎么回事？

**Comment by Liyf160823** [comment]
搞清楚了，jquery.js没有正常下载

**Comment by ssy341** [comment]
button的例子可以参考
[番茄工作法（简单易行的时间管理方法）- DataTables实现(介绍篇)](http://datatables.club/blog/2016/06/09/datatables-for-tomato.html)
