### ISSUE TITLE
vue配合datatable开发问题

### ISSUE THREAD

**Issue by var-zhangbao** [ssy341/datatables-cn#56]
vue循环数据出来的操作按钮,@click事件不执行

**Comment by ssy341** [comment]
@var-zhangbao 没用过vue，根据描述和是用经验来看，可能是你的绑定顺序有关系，比方说，在元素还没有生成的时候，你就给元素绑定了事件。如果是这个情况，参考如下jQuery代码:
```javascript
$("#example tobdy").on("click","tr",function(){
     //do something
})
```
这样代码写在任何地方，事件都能监听上
希望对你有所帮助
