### ISSUE TITLE
表格在请求数据未返回时，点击排序，数据请求中断

### ISSUE THREAD

**Issue by niuchunling** [ssy341/datatables-cn#57]
表格显示正在加载数据，点击任意的排序按钮，表格就显示没有，其实表格应该是有数据的

**Comment by niuchunling** [comment]
表格的数据最后是能缓冲出来的，只不过一天排序，会让人误以为没有数据，这个提示有专门针对排序的吗

**Comment by ssy341** [comment]
@niuchunling 你说的这个问题有点奇怪，按理来说这个不会发生，你提供下两次请求的返回数据估计会有一点帮助，第一次为DT初始化加载的时候的请求，第二个请求为你点击了排序后的请求
