### ISSUE TITLE
使用服务器返回数据，点击下一页时请求完毕后台数据，页面数据未刷新，页数也没变。

### ISSUE THREAD

**Issue by SillyBird-Github** [ssy341/datatables-cn#58]
今天刚刚使用datatables，在做一个分页例子的时候遇到的问题：页面首次加载时便调用后台，查询出的数据可以在页面中正常显示，分页也正常。但是点击下一页时，后台数据已经请求完毕，页面还是一直显示正在处理。。。在网上看了一下API和例子，没有发现问题出在哪里，刚开始使用，求指导~~~
例子的页面，一直显示正在处理：
![jsp](https://cloud.githubusercontent.com/assets/21074696/21288314/a4ac53c6-c4ba-11e6-9752-ecafdd6ebed7.jpg)
HTML和JS代码：
![html js](https://cloud.githubusercontent.com/assets/21074696/21288322/f650fda8-c4ba-11e6-8572-7fdffd3d9286.png)
后台模拟分页查询：
![server](https://cloud.githubusercontent.com/assets/21074696/21288332/20fb98b0-c4bb-11e6-8e66-5b1d7e193768.jpg)
这是返回的数据：
    {
        "draw":1,
        "iTotalRecords":"17",
        "iTotalDisplayRecords":"17",
        "data":[
            {
                "description":"DESCRIPTION-11",
                "title":"TITLE-11"
            },
            {
                "description":"DESCRIPTION-12",
                "title":"TITLE-12"
            },
            {
                "description":"DESCRIPTION-13",
                "title":"TITLE-13"
            },
            {
                "description":"DESCRIPTION-14",
                "title":"TITLE-14"
            },
            {
                "description":"DESCRIPTION-15",
                "title":"TITLE-15"
            },
            {
                "description":"DESCRIPTION-16",
                "title":"TITLE-16"
            },
            {
                "description":"DESCRIPTION-17",
                "title":"TITLE-17"
            }
        ]
    }

**Comment by ssy341** [comment]
@SillyBird-Github 你的问题出在draw上，这个值为前台传过来的值，你接受到多少，直接返回即可，看你的代码是写死了传的1，这是不对的，更详细的文档参考：[服务器处理(server-side) 手册 Datatables中文网](http://datatables.club/manual/server-side.html)

**Comment by SillyBird-Github** [comment]
看来还是我没仔细看文档，谢谢了~！

**Comment by SillyBird-Github** [comment]
@ssy341 非常感谢，我还是应该仔细的看一边文档再动手呀
