### ISSUE TITLE
根据datatables对象怎么获得Id

### ISSUE THREAD

**Issue by 792225193** [ssy341/datatables-cn#63]
$(doc).ready( function() {
            var tableId="233"
            var dataobj=eval("dataObj"+tableId)
            aa=$('#'+tableId).DataTable( {
                "columns":dataobj.columns,
                "order" :dataobj.defaultSort,
                "processing": true ,
                "serverSide": dataobj.serverSide, 
                dom: 'flrtip';        
                autoWidth :true,
                "ajax":  {
                    "url": "http://localhost:8080/msbase/table/dt.json",
                    "type": "POST",
                    "data": function ( d ) {
                        return {
                            'tableData':JSON.stringify(d),
                            'ajaxData' :dataobj.ajaxData
                        };
                    }
                }
            });
根据aa获得Id：233

**Comment by YangHuangYao** [comment]
@ssy341 :$.fn.dataTable.tables()这个方法可用用来获取选中行的ID吗？

**Comment by ssy341** [comment]
@YangHuangYao [$.fn.dataTable.tables()]($.fn.dataTable.tables() 获取该页面上所有的DataTables实例 文档(Options & API) DataTables中文网:http://datatables.club/reference/api/$.fn.dataTable.tables().html)
