### ISSUE TITLE
datatables 如何改变行的颜色？？？

### ISSUE THREAD

**Issue by fjdgl** [ssy341/datatables-cn#64]
datatables 如何改变行的颜色？？？

**Comment by ssy341** [comment]
@fjdgl  参考文档 [createdRow](http://datatables.club/reference/option/createdRow.html#)
应用实例：  [番茄工作法（简单易行的时间管理方法）- DataTables实现(介绍篇)](http://datatables.club/blog/2016/06/09/datatables-for-tomato.html)
源码： [tomato](http://datatables.club/blog/js/tomato.js)

关键代码：
```javascript
$("#example").DataTable({
"createdRow": rowCallback,
    "rowCallback": rowCallback
});

function rowCallback(row, data, index) {
    $(row).css('background-color', replaceColor(data.color));
    var flag = dataManager.getVisibleForRow();
    if (data.done && !flag) {
        $(row).css("display", "none");
    } else {
        $(row).css("display", "");
    }
}
```

**Comment by fjdgl** [comment]
tks,
I‘ll try it first.
