### ISSUE TITLE
怎么设置列中每行字数过多自动换行或者隐藏？

### ISSUE THREAD

**Issue by 666jjl** [ssy341/datatables-cn#66]
自动列宽的缘故，某列的内容长短不一，内容短还行，换到内容长还不换行的页的时候，会挤压其他列导致行高特别长，所以问一下怎么过长自动换行或隐藏或者是设置特定列固定宽度

**Comment by Smaillife** [comment]
改TD的CSS样式，加上换行的CSS代码就可以了

**Comment by 666jjl** [comment]
@Smaillife 请问具体是在哪里改呢，我对css不是很动呀

**Comment by ssy341** [comment]
@666jjl [render](http://datatables.club/manual/daily/2016/04/25/option-columns-render1.html) 把这系列看完，很多问题都能解决，文档看少了
