### ISSUE TITLE
ashx+jquery datatables,ajax返回json字符串(格式为“[{},{},...]”)，html前台<table>显示为null,如何解决？

### ISSUE THREAD

**Issue by ccz202** [ssy341/datatables-cn#69]
ashx页面返回json字符串的部分代码：          
            string JsonStr =jss.Serialize(list_Type);
            context.Response.Write(JsonStr);
html页面javascript代码：
 $("#t_Stock").dataTable({
                   .....
                    "ajax": {
                        url: "/App_Normal/WZGL/showStock.ashx",
                        data: { "s_Id": sId, "t_Id": tId },
                        type: "POST",
                        dataType: "json",
                    },
                    "data": "data",
                    "columns":
                        [                              
                             { "data": "Type_Id" },
                             .....                           
                        ]
                }); 
运行后 <table>显示：
标题行.....
null    null    null    null    null    null    null    null    null    null    null    null    null    null    
显示 1 到 4 ，共 4 条
上一页1下一页

**Comment by ssy341** [comment]
```javascript
{data:[
{},
{},
……
]}
```
这才是正确的返回格式
@ccz202
