### ISSUE TITLE
怎么通过按钮过滤指定数据

### ISSUE THREAD

**Issue by isaak-zmg** [ssy341/datatables-cn#71]
比如我从服务器拉取了数据 数据里面有条属性是角色 角色分两种
我怎么通过按钮的形式展示其中一种角色的数据并过滤掉另外一种角色的数据
（数据暂时不能再服务器端做过滤）

**Comment by ssy341** [comment]
@isaak-zmg 参考首页的[例子](http://datatables.club/)，这个是切换url来实现，或者使用方法
```javascript
dt.columns(0).search("角色一").draw();
```
[参考：DataTables 多条件查询、多列搜索](http://datatables.club/blog/2016/06/10/multiple-columns-search.html)
