### ISSUE TITLE
关于服务器分页接收ajax请求的问题

### ISSUE THREAD

**Issue by 666jjl** [ssy341/datatables-cn#73]
js如下：
 "fnServerData": function ( sSource, aoData, fnCallback ) {
                    	$.ajax( {
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": JSON.stringify(aoData), //以json格式传递
                        "success": function(resp) {
                        	console.log(resp);
//             				fnCallback(resp); 
            			},
                    	"error": function(e){
             			   console.log(e.responseText);	
             			}
                      } );
      } 
php如下（用的CI）：
		$a = json_decode($this->input->post('sEcho'));
		echo json_encode($a);
运行结果console只输出null，我猜可能是js写错了导致没有数据传到服务器，身陷囹圄又不造哪里错了，请大神赐教

**Comment by lizhouyang** [comment]
你在chrome里面运行，摁F12打开开发工具，在NetWork里面看发出的请求。不就知道请求的参数是怎么样的了？

**Comment by lizhouyang** [comment]
你在chrome里面运行，摁F12打开开发工具，在NetWork里面看发出的请求。不就知道请求的参数是怎么样的了？

**Comment by ssy341** [comment]
@666jjl 可以使用1.10版以上的DT么，这个是1.9的写法，不推荐，服务器模式参考
[服务器处理(server-side) 手册 Datatables中文网](http://datatables.club/manual/server-side.html)
[服务器简单处理 服务器处理 示例 Datatables中文网](http://datatables.club/example/server_side/simple.html)
