### ISSUE TITLE
服务器模式下单列搜索失效

### ISSUE THREAD

**Issue by 666jjl** [ssy341/datatables-cn#76]
经测试html模式时单列搜索和全局模糊搜索都有效切作用叠加，但是在服务器模式时单列搜索就失效了，
参照的是官网https://datatables.net/examples/api/multi_filter.html 不知有否先生能帮忙解决下燃眉之急

**Comment by ssy341** [comment]
@666jjl  服务器模式下的分页搜索排序需后台自行处理，[参考](http://datatables.club/manual/server-side.html)

**Comment by 666jjl** [comment]
@ssy341 您好，怪我没讲清楚。html模式下可以单列搜索，服务器模式时查了下请求发现只发了全局搜索的search[value]，单列搜索的search[value]为空，不知道这是为何

**Comment by ssy341** [comment]
@666jjl 需要你提供代码

**Comment by 666jjl** [comment]
$(document).ready(function() {
	 $('#GoodsList tfoot th').each( function () {
	        var title = $('#GoodsList thead th').eq( $(this).index() ).text();
	        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
	    } );
	 table=$('#GoodsList').dataTable(
{
                "processing": true, //开启读取服务器数据时显示正在加载中……特别是大数据量的时候，开启此功能比较好
                "serverSide": true, //开启服务器模式
                "ajax": {
                    "url": "<?php echo site_url('loadpages/load_data').'/GoodsList';?>", //给服务器发请求的url
                    "type": "POST",                 
                  }
              });
		table.columns().every( function () {
	        var that = this;
	 
	        $( 'input', this.footer() ).on( 'keydown', function (ev) {
	            if ( ev.keyCode == 13 ) {
	                that
	                    .search( this.value )
	                    .draw();
	            }
	        } );
	    } );
});
</script>

**Comment by 666jjl** [comment]
@ssy341 就是这样，参照的官网[这个](https://datatables.net/examples/api/multi_filter.html)，但是服务器模式就没用了.....

**Comment by ssy341** [comment]
@666jjl  部分代码需要做修改，加入columns列信息配置，代码如下：
```
table = $('#GoodsList').dataTable({
    "processing": true, //开启读取服务器数据时显示正在加载中……特别是大数据量的时候，开启此功能比较好
    "serverSide": true, //开启服务器模式
    "ajax": {
        "url": "<?php echo site_url('loadpages/load_data').'/GoodsList';?>", //给服务器发请求的url
        "type": "POST",
    },
    columns: [
        {
            data: "name"
        },
        {
            data: "age"
        },
        {
            data: "sex"
        },
        {
            data: "position"
        }
        //补全你的列配置
 
    ]
});
```
这个例子应该是针对客户端的，服务器模式的搜索，如果你不给columns配置，dt不知道会有那些列，当然也不会发送字段到后台

**Comment by 666jjl** [comment]
@ssy341 您好，我也想过用关联数组，只是表格列名是中文与传过来的关联数组的key不同导致data无法在表格中输出，搜了好一会儿也没找到不需要改数组的key也能对号入座的法子。。。不知大神有何高见

**Comment by ssy341** [comment]
@666jjl 麻烦贴出你返回的数据是什么样的？

**Comment by 666jjl** [comment]
@ssy341 
本来是这样的
{
    "data": [
        {
            "name": 1,
            "age": 2,
            "sex": 3,
            "position": 4
        },
        {
            "name": 1,
            "age": 2,
            "sex": 3,
            "position": 4
        },
        {
             "name": 1,
            "age": 2,
            "sex": 3,
            "position": 4
        }
    ]
}
但是由于列名是姓名、年龄这类的中文，错误提示找不到对应的name、age列于是表格中就没有显示数据，于是就改这样的
{
    "data": [
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]
    ]
}

**Comment by ssy341** [comment]
@666jjl 列名这些还是用英文吧，不知道你是出于什么原因，由于没有这样写过，暂时不清楚你这个情况需要怎么处理

**Comment by huangjiaxiang** [comment]
想知道这个解决了吗 
 if (this.checked.length == 0) {
                this.checkcol.style.color = 'black';
                $('#' + this.tableid).DataTable().column(this.checkcol.parentNode).search("").draw();
            }
            else {
                this.checkcol.style.color = 'red';
                $('#' + this.tableid).DataTable().column(this.checkcol.parentNode).search("^" + this.checked.join("$|^") + "$", true, true).draw();
            }
我是通过column.search()进行对应列筛选，在服务器端分页是  参数columns参数里的每一列的search.vaule都是null
