### ISSUE TITLE
Datetables分页显示的数量下拉框，想要去掉变成input框人为输入页面的显示数量，怎么搞？

### ISSUE THREAD

**Issue by liudong01** [ssy341/datatables-cn#77]

**Comment by ssy341** [comment]
@liudong01 自己写input框，使用dom自定义布局，去掉或者隐藏默认的‘l’，input框触发 [page.len()](http://datatables.club/reference/api/page.len())方法即可
[控制Datatables元素的位置(dom)](http://datatables.club/reference/option/dom.html)
[dom定位](http://datatables.club/example/basic_init/dom.html)
