### ISSUE TITLE
表格列搜索怎么不保存数据呢

### ISSUE THREAD

**Issue by tkj4570** [ssy341/datatables-cn#80]
```javascript
  $('#search').click(function(){
		var username=$('input[name="username"]').val();
		if(!username){
			layer.msg('请填写用户名', {
	      icon: 5,
	    });
		}else{
			myTable.column(2).search(username).draw();
		}
  })
```
查询完数据是对的 问题刷新了还是查询完的数据 数据怎么变回原来的

**Comment by ssy341** [comment]
@tkj4570 检查是否加了 stateSave参数
参考：
[关于 DataTables 本地储存那点事，又爱又恨 (stateSave参数应用)](http://datatables.club/blog/2016/09/30/about-localStorage-of-stuff-for-DataTables.html)
