### ISSUE TITLE
datables多个ajax请求

### ISSUE THREAD

**Issue by mrxiaosen** [ssy341/datatables-cn#81]
我这边有这样一个需求，我想在一个页面同时进行分页查询，修改，添加，新建得功能，并且都通过ajax实现。问题是问也查询的请求是GET，其余的都是POST，而且他们传的参数也不一样。我知道在调用$（）.dataTables（）方法得时候可以对ajax得type和data进行一次初始化。但是我没有找到方法如何在初始化之后，来修改请求方式(get.post)，和设置请求所需要得数据(data)

**Comment by mrxiaosen** [comment]
得方法，我尝试重新初始化dataTables，但是提醒我，只能初始化一次。所以我来这里咨询一下，有什么好的办法？感激不尽

**Comment by ssy341** [comment]
@mrxiaosen [retrieve](http://datatables.club/reference/option/retrieve.html)参考这个，当dt多次被调用（初始化）时，加上此属性，比如下方代码需要在多个地方调用
```javascript
$("#dt").DataTable({
        "retrieve": true,
        //其他配置属性
    });
```
`$("#dt").DataTable({....})`代表对表格初始化，如果你多次调用这个方法，相当于不停的在初始化，这在逻辑上是不推荐的，所以作者使用retrieve属性来判断你时候需要使用已经初始化过的实例，而不是新的实例。
关于ajax的type设置，参考如下代码：
```javascript
$("#dt").DataTable({
        "ajax":{
                "type":"post",
                "url":"url"
         },
        //其他配置属性
    });
``` 
用法和jQuery的ajax类似，具体参考 [ajax](http://datatables.club/reference/option/ajax.html#)
