### ISSUE TITLE
datatables 渲染之后的数据如果得到?

### ISSUE THREAD

**Issue by qiuyoo** [ssy341/datatables-cn#89]
datatables 渲染之后的数据如果得到?

**Comment by occultskyrong** [comment]
最好自己看下dt的api列表。
https://datatables.net/reference/api/

获取单行数据使用
https://datatables.net/reference/api/row().data()

**Comment by ssy341** [comment]
@qiuyoo 参考
[cell().render()](https://datatables.net/reference/api/cell().render())
[cells().render()](https://datatables.net/reference/api/cells().render())
