### ISSUE TITLE
dataTables渲染数据时，怎么根据数据的不同设置当前单元格的class

### ISSUE THREAD

**Issue by chtic123** [ssy341/datatables-cn#90]

**Comment by chtic123** [comment]
比如说，我的数据有一个事件等级，如果事件等级是高级，我就给当前这个单元格添加一个danger的class，如果是中级，我就添加一个warning的class

**Comment by ssy341** [comment]
@chtic123 [番茄工作法（简单易行的时间管理方法）- DataTables实现(介绍篇):](http://datatables.club/blog/2016/06/09/datatables-for-tomato.html)

[源码](http://runjs.cn/code/dirmx2mi)

**Comment by chtic123** [comment]
@ssy341 我没明白。。。没看到这个里面有我要的效果啊

**Comment by ssy341** [comment]
@chtic123 
···JavaScript
//关键代码，行创建回调
 "createdRow": rowCallback,

//在这个方法里可以修改row对象，根据自己的需要
function rowCallback(row, data, index) {
    $(row).css('background-color', replaceColor(data.color));
    var flag = dataManager.getVisibleForRow();
    if (data.done && !flag) {
        $(row).css("display", "none");
    } else {
        $(row).css("display", "");
    }
}

``

同样有单元格创建的回调，[参考 createdCell](https://datatables.net/reference/option/columns.createdCell)
或者参考 [option columns.render 渲染列](http://datatables.club/manual/daily/2016/04/25/option-columns-render1.html)`
