### ISSUE TITLE
无法更新数据(Can't update my data)

### ISSUE THREAD

**Issue by MrCuire** [ssy341/datatables-cn#92]
var t= $("#data").dataTable({
        data: <?echo json_encode($res)?>,
        columns: [
            {data:null,title:"<input type='checkbox' name='checklist' id='checkall' />"},
            {data: 'team_name',title:'团队名称'},
            {data: 'username',title:'创建者'},
            {data:'member_num',title:'团队人数'} ,
            {data:null,title:'操作'}
        ],
        columnDefs: [
            {
                //   指定第一列，从0开始，0表示第一列，1表示第二列……
                targets: 0,
                render: function(data, type, row, meta) {
                    return '<input type="checkbox" name="checklist" value="'+data.team_id+'"/>';
                }

            },
            {
                targets:4,
                render:function(data){
                    return '<button class="btn btn-success access" title="通过审核" index="'+data.team_id+'"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button> '+
                        '<button class="btn btn-danger deny" title="拒绝通过" index="'+data.team_id+'"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>';
                }
            }
        ],

        language: {
            "sProcessing": "处理中...",
            "sLengthMenu": "显示 _MENU_ 项结果",
            "sZeroRecords": "没有匹配结果",
            "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
            "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
            "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
            "sInfoPostFix": "",
            "sSearch": "搜索:",
            "sUrl": "",
            "sEmptyTable": "表中数据为空",
            "sLoadingRecords": "载入中...",
            "sInfoThousands": ",",
            "oPaginate": {
                "sFirst": "首页",
                "sPrevious": "上页",
                "sNext": "下页",
                "sLast": "末页"
            },
            "oAria": {
                "sSortAscending": ": 以升序排列此列",
                       "sSortDescending": ": 以降序排列此列"
            }
        }

    });
   //审核通过
   $('body').on('click','.access',function(){
       var id= $(this).attr('index');
       $.ajax({
           type:'post',
           url:'?m=team_management&c=team_management&a=access&pc_hash=CwgaDT',
           data:{id:id},
           success:function(data){
               if(data){
                   alert('修改成功');
                   t.ajax.reload(null,false);
               }
           }
       });
   });
there is my code , I use php to print data by json type.And after I successfully operated database by Ajax ,JS alert a message .then I need table to update data at the same time. but I tired a lot of ways and it keep report error which is 'Cannot read property 'reload' of undefined'.  【 t.ajax.reload(null,false);】 i don't know how to use this codes.I got another way to resolve this problem ,but I wanna figure it out in dataTable way.Thanks (my English is terrible, and i do my best to make it clear. :) )
以上是我的代码 数据源是直接用php输出 ,在我用ajax成功操作完数据库之后,js弹一个提示信息，然后我想要表格也一起更新数据，但是我试了很多方法也搞不定，它一直报错，像什么Cannot read property 'reload' of undefined，【 t.ajax.reload(null,false);】 我不知道怎么用这段代码，我有其他方法去解决这个问题，但是我很想用dataTable的方法解决这个问题。感谢~

**Comment by ssy341** [comment]
@MrCuire 
```javascript
 var table = $("#data").DataTable({……});

//需要的地方调用如下代码
table.ajax.reload(null,false);
```
注意区别 $("#data").DataTable({……}); 和 $("#data").dataTable({……}); 前者返回的是DT的api实例，后者返回的是jQuery对象，[参考](http://datatables.club/reference/api/)
