### ISSUE TITLE
如何通过拖拽改变列的顺序

### ISSUE THREAD

**Issue by jmuchch** [ssy341/datatables-cn#94]
如何通过拖拽改变列的顺序，比如一共有one two three 三列，如何实现鼠标拖动第一列one，放到three列的后面？

**Comment by jmuchch** [comment]
I have find the answer ,see this follow:
https://datatables.net/extensions/colreorder/examples/initialisation/simple.html

**Comment by ssy341** [comment]
@jmuchch yep,you're right
