### ISSUE TITLE
datatable 动态替换原理，能不能自定义动态替换模版

### ISSUE THREAD

**Issue by meacial** [ssy341/datatables-cn#96]
language模版中，_TOTAL_和后端recordsTotal对应，是怎么对应的？
能加入自定义的动态替换嘛？比如自定义的一个 cnt 对应后端返回的 cnt?

**Comment by ssy341** [comment]
@meacial 这个可以通过回调方法处理 [option infoCallback 表格概要信息显示回调](http://datatables.club/manual/daily/2016/08/30/option-infoCallback.html)
