### ISSUE TITLE
How to change the width of column by mouse dragging   如何通过鼠标拖动改变列的宽度？

### ISSUE THREAD

**Issue by jmuchch** [ssy341/datatables-cn#97]
How to change the width of column by mouse dragging 
 如何通过鼠标拖动改变列的宽度？
找不到相关的示例
I can not find the API or example about it;

**Comment by ssy341** [comment]
@jmuchch There is an example  [link](http://datatables.club/example/user_share/yuui.html)

**Comment by Gabrielkaliboy** [comment]
@jmuchch 请问你的问题是否解决了
