### ISSUE TITLE
datatables在ie8下会多出一列null，是什么原因，求大神解答。。

### ISSUE THREAD

**Issue by TZonly** [ssy341/datatables-cn#99]
引用datatable 获取显示数据时，其他浏览器都没有问题，但是ie8会报出table id=table-Requested unknown parameter ' 6'  for row 0  的错，并且显示一列null的数据，该怎样解决

**Comment by ssy341** [comment]
@TZonly 需要提供代码

**Comment by TZonly** [comment]
已经解决了 ，谢谢！
